//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//


@interface AddressBookArchive
{
    NSMutableSet *phones;	// 8 = 0x8
    NSMutableSet *emails;	// 16 = 0x10
}

+ (void)initialize;
@property(retain, nonatomic) NSMutableSet *emails; // @synthesize emails;
@property(retain, nonatomic) NSMutableSet *phones; // @synthesize phones;

- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)getValueTypeTable;

@end

