//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  3 2016 20:04:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface CacheFileInfo : NSObject
{
    _Bool isNewYearMode;
    unsigned int bDebugMode;
    NSString *appid;
    unsigned long long version;
    NSString *subPath;
    unsigned long long offset;
    unsigned long long size;
    NSString *pkgFilePath;
}

@property(nonatomic) _Bool isNewYearMode; // @synthesize isNewYearMode;
@property(copy, nonatomic) NSString *pkgFilePath; // @synthesize pkgFilePath;
@property(nonatomic) unsigned int bDebugMode; // @synthesize bDebugMode;
@property(nonatomic) unsigned long long size; // @synthesize size;
@property(nonatomic) unsigned long long offset; // @synthesize offset;
@property(copy, nonatomic) NSString *subPath; // @synthesize subPath;
@property(nonatomic) unsigned long long version; // @synthesize version;
@property(copy, nonatomic) NSString *appid; // @synthesize appid;
- (void).cxx_destruct;

@end

