//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  3 2016 20:04:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface EnterpriseConnectorContext : NSObject
{
    NSString *_contextBrand;
    NSString *_contextEnterpriseChat;
}

@property(retain, nonatomic) NSString *contextEnterpriseChat; // @synthesize contextEnterpriseChat=_contextEnterpriseChat;
@property(retain, nonatomic) NSString *contextBrand; // @synthesize contextBrand=_contextBrand;
- (void).cxx_destruct;

@end

