//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  3 2016 20:04:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSData, NSMutableArray;

__attribute__((visibility("hidden")))
@interface HWFrameBuffer : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSData *rawBuf; // @dynamic rawBuf;
@property(retain, nonatomic) NSMutableArray *sampleSize; // @dynamic sampleSize;
@property(nonatomic) int samplesCount; // @dynamic samplesCount;
@property(retain, nonatomic) NSMutableArray *timeInfo; // @dynamic timeInfo;

@end

