//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  3 2016 20:04:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMKernelExt-Protocol.h"
#import "MMService-Protocol.h"

@class NSMutableArray, NSRecursiveLock, NSString;

__attribute__((visibility("hidden")))
@interface IDCHostMgr : MMService <MMService, MMKernelExt>
{
    NSMutableArray *m_idcHostItemList;
    NSRecursiveLock *m_oLock;
}

- (void).cxx_destruct;
- (void)GetIDCHostFromVoicePrintLogin:(id)arg1 Delegate:(id)arg2;
- (void)GetIDCHostFromBindMobile:(id)arg1 Delegate:(id)arg2;
- (void)HandleIPListFromPB:(id)arg1 PortList:(id)arg2 TimeOutList:(id)arg3;
- (void)HandleHostListFromPB:(id)arg1;
- (void)SaveIDCHost;
- (void)LoadIDCHost;
- (id)GetRealHostFromHost:(id)arg1;
- (void)SaveIDCHostForReg:(id)arg1 AuthIP:(id)arg2 Delegate:(id)arg3;
- (void)SaveIDCHost:(id)arg1 FromAuth:(_Bool)arg2 AuthIP:(id)arg3;
- (void)SaveIDCHost:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

