//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  3 2016 20:04:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class EmotionRewardResponseInfo, NSString;

@protocol IStoreEmotionRewardExt

@optional
- (void)onStoreEmotionRewardCompleteOkWithPid:(NSString *)arg1 RewardInfo:(EmotionRewardResponseInfo *)arg2;
- (void)onGetEmotionRewardFinishedWithPid:(NSString *)arg1 RewardInfo:(EmotionRewardResponseInfo *)arg2;
@end

