//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  3 2016 20:04:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class SKBuiltinBuffer_t;

__attribute__((visibility("hidden")))
@interface LoginQRCodeNotifyPkg : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) SKBuiltinBuffer_t *notifyData; // @dynamic notifyData;
@property(nonatomic) unsigned int opcode; // @dynamic opcode;

@end

