//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  3 2016 20:04:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMUIView.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface SummaryItemView : MMUIView
{
    UILabel *_leftLabel;
    UILabel *_rightLabel;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)getUserDisplayName:(id)arg1;
- (void)updateWithSummaryFeedItem:(id)arg1;

@end

