//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  3 2016 20:04:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MMService.h"

#import "MMService-Protocol.h"

@class NSObject, NSString, WCNewClickPageStatData;
@protocol OS_dispatch_queue;

__attribute__((visibility("hidden")))
@interface WCNewClickDataCheckMgr : MMService <MMService>
{
    WCNewClickPageStatData *_pageStatData;
    NSObject<OS_dispatch_queue> *_queue;
}

- (void).cxx_destruct;
- (_Bool)removeStatFile;
- (id)getPageStatAttr:(id)arg1;
- (_Bool)reportData;
- (_Bool)isNeedToReport;
- (_Bool)saveStatData:(id)arg1;
- (void)recordPage:(id)arg1 startTime:(unsigned int)arg2 endTime:(unsigned int)arg3;
- (void)onServiceEnterBackground;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

