//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  3 2016 20:04:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

@protocol WCPayBalanceSaveMoneyViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface WCPayBalanceSaveMoneyViewController : WCPayBaseViewController
{
    _Bool m_bNeedBindCard;
    id <WCPayBalanceSaveMoneyViewControllerDelegate> m_delegate;
}

- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)refreshViewWithData:(id)arg1;
- (void)onSubscribeAppBtn:(id)arg1;
- (void)reloadTableView;
- (void)selectNeedBindCard:(id)arg1;
- (void)initNavigationBar;
- (void)internalPushViewController:(id)arg1 animated:(_Bool)arg2;
- (void)OnHistoryOrderDetailBack;
- (void)setDelegate:(id)arg1;
- (id)init;

@end

