//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  3 2016 20:04:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface WCPayAlertItem : NSObject
{
    NSString *_alertTitle;
    NSString *_leftButtonWording;
    NSString *_rightButtonWording;
    NSString *_rightButtonUrl;
}

@property(retain, nonatomic) NSString *rightButtonUrl; // @synthesize rightButtonUrl=_rightButtonUrl;
@property(retain, nonatomic) NSString *rightButtonWording; // @synthesize rightButtonWording=_rightButtonWording;
@property(retain, nonatomic) NSString *leftButtonWording; // @synthesize leftButtonWording=_leftButtonWording;
@property(retain, nonatomic) NSString *alertTitle; // @synthesize alertTitle=_alertTitle;
- (void).cxx_destruct;

@end

