//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct  3 2016 20:04:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextField.h>

__attribute__((visibility("hidden")))
@interface WCUITextField : UITextField
{
    _Bool m_bRestrictShareMenu;
    double m_fPlaceholderFontSize;
}

@property(nonatomic) double m_fPlaceholderFontSize; // @synthesize m_fPlaceholderFontSize;
@property(nonatomic) _Bool m_bRestrictShareMenu; // @synthesize m_bRestrictShareMenu;
- (void)dealloc;
- (void)drawPlaceholderInRect:(struct CGRect)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (id)init;

@end

