//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MDViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MDPersonalProfile, NSString, UIDatePicker, UILabel, UITableView;

@interface AgeEditorViewController : MDViewController <UITableViewDelegate, UITableViewDataSource>
{
    MDPersonalProfile *personalProfile;
    UITableView *table;
    UILabel *hView;
    UIDatePicker *picker;
    int lanMode;
    CDUnknownBlockType completion;
}

@property(nonatomic) int lanMode; // @synthesize lanMode;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion;
@property(retain, nonatomic) UIDatePicker *picker; // @synthesize picker;
@property(retain, nonatomic) UITableView *table; // @synthesize table;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)changeDate:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (_Bool)navigationBar:(id)arg1 shouldPopItem:(id)arg2;
- (void)viewDidLoad;
- (id)initWithNibNameAndData:(id)arg1 data:(id)arg2 bundle:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)initWithNibNameAndData:(id)arg1 data:(id)arg2 bundle:(id)arg3;
- (id)initWithLanguageMode:(int)arg1 andPersonlProfile:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

