//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MFSimpleDatabase, NSMutableDictionary;

@interface DBFeedDraftProvider : NSObject
{
    MFSimpleDatabase *mfdb;
    NSMutableDictionary *dbCache;
}

+ (id)providerWithMFDB:(id)arg1;
- (void)clearAllBeforeDb;
- (id)fieldDictFromParam:(id)arg1;
- (id)paramFromDbRow:(id)arg1;
- (id)getAllParam;
- (void)removeParam:(id)arg1 type:(int)arg2;
- (void)setParam:(id)arg1;
- (id)getParam:(id)arg1 type:(int)arg2;
- (void)ensureDbTables;
- (void)dealloc;
- (id)initWithMFDB:(id)arg1;

@end

