//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MDViewController.h"

#import "EmotionStoreIAdManagerDelegate.h"
#import "MDBadgeSegmentControlDelegate.h"
#import "MDEmotionShopDelegate.h"
#import "MDSearchControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class EmotionStoreIAdManager, MDBadgeSegmentControl, MDEmotionShop, NSString, UITableView, UIView;

@interface EmotionStoreViewController : MDViewController <UITableViewDataSource, UITableViewDelegate, MDEmotionShopDelegate, MDBadgeSegmentControlDelegate, MDSearchControllerDelegate, EmotionStoreIAdManagerDelegate>
{
    UITableView *_listTableView;
    MDEmotionShop *emotionShop;
    MDBadgeSegmentControl *_segmentControl;
    long long rowsCount;
    NSString *presentationUserId;
    UIView *_headView;
    int specifiedType;
    EmotionStoreIAdManager *_iadsManager;
    long long _entranceType;
}

@property(retain, nonatomic) MDBadgeSegmentControl *segmentControl; // @synthesize segmentControl=_segmentControl;
@property(nonatomic) long long entranceType; // @synthesize entranceType=_entranceType;
@property(retain, nonatomic) UIView *headView; // @synthesize headView=_headView;
@property(retain, nonatomic) EmotionStoreIAdManager *iadsManager; // @synthesize iadsManager=_iadsManager;
@property(copy, nonatomic) NSString *presentationUserId; // @synthesize presentationUserId;
@property(retain, nonatomic) UITableView *listTableView; // @synthesize listTableView=_listTableView;
- (void)didClickEmotionCategory:(id)arg1;
- (void)enableSubViewEndSearch;
- (void)disableSubViewBeginSearch;
- (void)beginLoadData;
- (void)didSelectItemView:(id)arg1;
- (void)emotionShopDataLodingWithError:(id)arg1;
- (void)emotionShopDataDidFinishLoading;
- (void)refreshLoadMoreButtonState;
- (void)loadMoreData;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)didReceiveMemoryWarning;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)showiAdView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)badgeSegmentControl:(id)arg1 didSelectSegmentIndex:(unsigned long long)arg2;
- (void)autoLoadEmotions;
- (id)initializeButtonWithImage:(id)arg1 title:(id)arg2;
- (void)configTitleAndBarButtonItems;
- (void)enterAccountBalanceAction;
- (void)enterMyEmotionAction;
- (void)closeAction;
- (void)dealloc;
- (id)initWithEmotionSourceType:(int)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

