//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIActionSheetDelegate.h"
#import "UITextFieldDelegate.h"
#import "UITextViewDelegate.h"
#import "iConsoleDelegate.h"

@class NSMutableArray, NSString, UIButton, UIColor, UITextField, UITextView;

@interface iConsole : UIViewController <UITextFieldDelegate, UIActionSheetDelegate, UITextViewDelegate, iConsoleDelegate>
{
    _Bool _enabled;
    _Bool _saveLogToDisk;
    _Bool _simulatorShakeToShow;
    _Bool _deviceShakeToShow;
    _Bool _animating;
    int _logLevel;
    unsigned long long _maxLogItems;
    id <iConsoleDelegate> _delegate;
    unsigned long long _simulatorTouchesToShow;
    unsigned long long _deviceTouchesToShow;
    NSString *_infoString;
    NSString *_inputPlaceholderString;
    NSString *_logSubmissionEmail;
    UIColor *_backgroundColor;
    UIColor *_textColor;
    long long _indicatorStyle;
    NSMutableArray *_log;
    NSMutableArray *_itemArray;
    UITextView *_consoleView;
    UITextField *_inputField;
    UIButton *_actionButton;
}

+ (void)hide;
+ (void)show;
+ (void)clear;
+ (void)crash:(id)arg1;
+ (void)error:(id)arg1;
+ (void)warn:(id)arg1;
+ (void)info:(id)arg1;
+ (void)log:(id)arg1;
+ (void)log:(id)arg1 arguments:(char *)arg2;
+ (id)sharedConsole;
+ (void)load;
@property(nonatomic) _Bool animating; // @synthesize animating=_animating;
@property(retain, nonatomic) UIButton *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) UITextField *inputField; // @synthesize inputField=_inputField;
@property(retain, nonatomic) UITextView *consoleView; // @synthesize consoleView=_consoleView;
@property(retain, nonatomic) NSMutableArray *itemArray; // @synthesize itemArray=_itemArray;
@property(retain, nonatomic) NSMutableArray *log; // @synthesize log=_log;
@property(nonatomic) long long indicatorStyle; // @synthesize indicatorStyle=_indicatorStyle;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(copy, nonatomic) NSString *logSubmissionEmail; // @synthesize logSubmissionEmail=_logSubmissionEmail;
@property(copy, nonatomic) NSString *inputPlaceholderString; // @synthesize inputPlaceholderString=_inputPlaceholderString;
@property(copy, nonatomic) NSString *infoString; // @synthesize infoString=_infoString;
@property(nonatomic) _Bool deviceShakeToShow; // @synthesize deviceShakeToShow=_deviceShakeToShow;
@property(nonatomic) _Bool simulatorShakeToShow; // @synthesize simulatorShakeToShow=_simulatorShakeToShow;
@property(nonatomic) unsigned long long deviceTouchesToShow; // @synthesize deviceTouchesToShow=_deviceTouchesToShow;
@property(nonatomic) unsigned long long simulatorTouchesToShow; // @synthesize simulatorTouchesToShow=_simulatorTouchesToShow;
@property(nonatomic) __weak id <iConsoleDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) int logLevel; // @synthesize logLevel=_logLevel;
@property(nonatomic) unsigned long long maxLogItems; // @synthesize maxLogItems=_maxLogItems;
@property(nonatomic) _Bool saveLogToDisk; // @synthesize saveLogToDisk=_saveLogToDisk;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
- (void).cxx_destruct;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)handleLogArray:(id)arg1 isLoadMore:(_Bool)arg2;
- (void)loadMoreLog;
- (void)dismiss;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)runTest;
- (void)testHttpsError:(id)arg1;
- (void)testHttpsFail:(id)arg1;
- (void)testHttpsSuccess:(id)arg1;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (id)URLEncodedString:(id)arg1;
- (_Bool)textFieldShouldClear:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)showDomainCommandHelp;
- (void)handleDomainCommand:(id)arg1;
- (void)handleDeleteEmotionWithCommands:(id)arg1;
- (void)handleConsoleCommand:(id)arg1;
- (void)logOnMainThread:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)resizeView:(id)arg1;
- (void)rotateView:(id)arg1;
- (void)consoleHidden;
- (void)hideConsole;
- (void)consoleShown;
- (void)showConsole;
- (struct CGRect)offscreenFrame;
- (struct CGRect)onscreenFrame;
- (struct CGAffineTransform)viewTransform;
- (void)infoAction;
- (_Bool)findAndResignFirstResponder:(id)arg1;
- (void)saveSettings;
- (void)resetLog;
- (void)setConsoleText;
- (id)mainWindow;
- (void)switchLogOption:(id)arg1;
- (void)showHelpMessage:(id)arg1;
- (void)showApiStatus:(id)arg1;
- (void)showIMJStatus:(id)arg1;
- (void)showTrafficFlow:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

