//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MBProgressHUDDelegate.h"

@class MBProgressHUD, NSString;

@interface IndicateTool : NSObject <MBProgressHUDDelegate>
{
    id <IndicateToolDelegate> _delegate;
    MBProgressHUD *_currentHUD;
}

@property(retain, nonatomic) MBProgressHUD *currentHUD; // @synthesize currentHUD=_currentHUD;
@property(nonatomic) id <IndicateToolDelegate> delegate; // @synthesize delegate=_delegate;
- (void)showGlobalMessageWithText:(id)arg1 timeOut:(double)arg2 showEmotion:(_Bool)arg3 goodOrNot:(_Bool)arg4 onAppWindow:(_Bool)arg5;
- (void)showGlobalMessageWithText:(id)arg1 timeOut:(double)arg2 showEmotion:(_Bool)arg3 goodOrNot:(_Bool)arg4;
- (void)removeLockedHUDAnimated:(_Bool)arg1;
- (void)showLockedHUDAnimated:(_Bool)arg1;
- (id)createOKHudInView:(id)arg1 WithText:(id)arg2;
- (void)hideAndFreeHUD:(id)arg1;
- (id)showHUDAddedTo:(id)arg1 animated:(_Bool)arg2;
- (void)hudWasHidden:(id)arg1;
- (void)showTipInView:(id)arg1 withText:(id)arg2 timeOut:(double)arg3 offsetY:(double)arg4;
- (void)showTipInView:(id)arg1 withText:(id)arg2 timeOut:(double)arg3;
- (void)showAlertInView:(id)arg1 withText:(id)arg2 timeOut:(double)arg3 offsetY:(double)arg4;
- (void)showAlertInView:(id)arg1 withText:(id)arg2 timeOut:(double)arg3;
- (void)showWarningInView:(id)arg1 withText:(id)arg2 timeOut:(double)arg3;
- (void)showOKInView:(id)arg1 withText:(id)arg2 timeOut:(double)arg3 offsetY:(double)arg4;
- (void)showOKInView:(id)arg1 withText:(id)arg2 timeOut:(double)arg3;
- (void)showNormalInView:(id)arg1 withText:(id)arg2;
- (void)removePreHudFromView:(id)arg1;
- (void)labelAttributeInit:(id)arg1;
- (void)resizeLabelFrame:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

