//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "EtaModel.h"

@class NSString;

@interface MDBlueInfoModel : EtaModel
{
    NSString *_ID;
    NSString *_text;
    NSString *_desc;
    NSString *_gotoAction;
    long long _type;
}

+ (id)eta_jsonKeyPathsByProperty;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *gotoAction; // @synthesize gotoAction=_gotoAction;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(copy, nonatomic) NSString *ID; // @synthesize ID=_ID;
- (void).cxx_destruct;

@end

