//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MKBridgeBase.h"

@class MomoKitShareHandler;

@interface MDBridgeShare : MKBridgeBase
{
    MomoKitShareHandler *_sharePlugin;
}

@property(retain, nonatomic) MomoKitShareHandler *sharePlugin; // @synthesize sharePlugin=_sharePlugin;
- (void).cxx_destruct;
- (void)toApp:(id)arg1;
- (void)showPanel:(id)arg1;
- (void)setInfo:(id)arg1;

@end

