//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "MDChatTableCellDelegate.h"

@class MDMixItem, NSString, UILabel;

@interface MDChatTimeStampCell : UITableViewCell <MDChatTableCellDelegate>
{
    MDMixItem *_item;
    UILabel *_timeLabel;
    UILabel *_distanceLabel;
}

@property(retain, nonatomic) UILabel *distanceLabel; // @synthesize distanceLabel=_distanceLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) MDMixItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)setDistance:(id)arg1;
- (void)setTime:(id)arg1;
- (void)bindModel:(id)arg1;
- (void)resetToDefault;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

