//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MDChatBaseLayout.h"

@class MDImageNode, MDLabelNode;

@interface MDChatAudioLayout : MDChatBaseLayout
{
    MDImageNode *_nodePlayStatus;
    MDLabelNode *_nodeDuration;
    MDImageNode *_nodeSeparator;
    MDLabelNode *_nodeVoiceToText;
}

@property(retain, nonatomic) MDLabelNode *nodeVoiceToText; // @synthesize nodeVoiceToText=_nodeVoiceToText;
@property(retain, nonatomic) MDImageNode *nodeSeparator; // @synthesize nodeSeparator=_nodeSeparator;
@property(retain, nonatomic) MDLabelNode *nodeDuration; // @synthesize nodeDuration=_nodeDuration;
@property(retain, nonatomic) MDImageNode *nodePlayStatus; // @synthesize nodePlayStatus=_nodePlayStatus;
- (void).cxx_destruct;
- (long long)calculateBubbleWidth:(long long)arg1;
- (void)layoutTail:(double)arg1;
- (void)layoutVoiceToText;
- (void)layoutDuration;
- (void)layoutPlayStatus;
- (void)setupVoiceToText;
- (void)setupSeparator;
- (void)setupDuration;
- (void)setupPlayStatus;
- (void)layout;
- (void)setupSubNodes;

@end

