//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MDChatBaseCell.h"

@interface MDChatActionCell : MDChatBaseCell
{
}

- (void)clickAction;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)updateAllProperty:(id)arg1;
- (void)updateContentText:(id)arg1;
- (void)updateContentImage:(id)arg1;
- (void)updateBubbleImage:(id)arg1;
- (void)updateStatus:(id)arg1;
- (void)bindModel:(id)arg1;
- (Class)chatLayoutClass;
- (void)resetToDefault;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

