//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "MDChatSessionCellDelegate.h"

@class MDBadgeView, MDChatSessionMessageView, MUAvatarView, NSString, UIButton, UILabel;

@interface MDChatSessionBaseCell : UITableViewCell <MDChatSessionCellDelegate>
{
    int _sessionType;
    int _showCate;
    NSString *_sessionKey;
    NSString *_targetid;
    id <MDChatSessionCellProtocol> _mdDelegate;
    MUAvatarView *_headAvatar;
    UIButton *_headButton;
    UILabel *_labelName;
    MDBadgeView *_badgeView;
    MDChatSessionMessageView *_messageAyscView;
    UILabel *_labelMessage;
    UILabel *_labelTime;
}

@property(retain, nonatomic) UILabel *labelTime; // @synthesize labelTime=_labelTime;
@property(retain, nonatomic) UILabel *labelMessage; // @synthesize labelMessage=_labelMessage;
@property(retain, nonatomic) MDChatSessionMessageView *messageAyscView; // @synthesize messageAyscView=_messageAyscView;
@property(retain, nonatomic) MDBadgeView *badgeView; // @synthesize badgeView=_badgeView;
@property(retain, nonatomic) UILabel *labelName; // @synthesize labelName=_labelName;
@property(retain, nonatomic) UIButton *headButton; // @synthesize headButton=_headButton;
@property(retain, nonatomic) MUAvatarView *headAvatar; // @synthesize headAvatar=_headAvatar;
@property(nonatomic) __weak id <MDChatSessionCellProtocol> mdDelegate; // @synthesize mdDelegate=_mdDelegate;
@property(nonatomic) int showCate; // @synthesize showCate=_showCate;
@property(nonatomic) int sessionType; // @synthesize sessionType=_sessionType;
@property(retain, nonatomic) NSString *targetid; // @synthesize targetid=_targetid;
@property(retain, nonatomic) NSString *sessionKey; // @synthesize sessionKey=_sessionKey;
- (void).cxx_destruct;
- (void)didDragedBageView;
- (void)didClickedHead;
- (void)setupBottomLine;
- (void)setupBageView;
- (void)setupHeadBtn;
- (void)updateBadgeView:(id)arg1;
- (void)resetDefault;
- (void)bindModel:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

