//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSString;

@interface MDCreateRoomModel : NSObject
{
    NSString *_categoryId;
    NSString *_categoryName;
    NSString *_categoryIconURL;
    NSString *_notice;
    NSArray *_randomTopicList;
    NSMutableArray *_filterList;
    NSString *_question;
    NSMutableArray *_answerList;
    NSString *_limitDesc;
}

+ (id)createRoomModelFromDict:(id)arg1;
@property(retain, nonatomic) NSString *limitDesc; // @synthesize limitDesc=_limitDesc;
@property(retain, nonatomic) NSMutableArray *answerList; // @synthesize answerList=_answerList;
@property(retain, nonatomic) NSString *question; // @synthesize question=_question;
@property(retain, nonatomic) NSMutableArray *filterList; // @synthesize filterList=_filterList;
@property(retain, nonatomic) NSArray *randomTopicList; // @synthesize randomTopicList=_randomTopicList;
@property(retain, nonatomic) NSString *notice; // @synthesize notice=_notice;
@property(retain, nonatomic) NSString *categoryIconURL; // @synthesize categoryIconURL=_categoryIconURL;
@property(retain, nonatomic) NSString *categoryName; // @synthesize categoryName=_categoryName;
@property(retain, nonatomic) NSString *categoryId; // @synthesize categoryId=_categoryId;
- (void).cxx_destruct;

@end

