//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSFileManagerDelegate.h"

@class NSString;

@interface MDDirectoryTransferUtil : NSObject <NSFileManagerDelegate>
{
}

+ (id)sharedInstance;
- (_Bool)fileManager:(id)arg1 shouldProceedAfterError:(id)arg2 copyingItemAtPath:(id)arg3 toPath:(id)arg4;
- (_Bool)fileManager:(id)arg1 shouldCopyItemAtPath:(id)arg2 toPath:(id)arg3;
- (_Bool)hasTransferEmotions;
- (void)moveEmotionsToApplicationSupport;
- (_Bool)IfNeededMoveEmotionImage;
- (void)moveChatBackImageToApplicationSupport;
- (_Bool)hasTransferChatBackImage;
- (_Bool)IfNeededMoveChatBackImage;
- (void)moveChatBackImageToApplicationSupportIfNeeded;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

