//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class SingleAnimEmojiView;

@interface MDEmojiDisplayItemCell : UICollectionViewCell
{
    SingleAnimEmojiView *_aniView;
}

@property(retain, nonatomic) SingleAnimEmojiView *aniView; // @synthesize aniView=_aniView;
- (void).cxx_destruct;
- (void)updateCellWithModel:(id)arg1;
- (void)layoutSubviews;

@end

