//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MDFileReceiverDelegate.h"

@class NSMutableDictionary, NSString;

@interface MDFileReceiverManager : NSObject <MDFileReceiverDelegate>
{
    NSMutableDictionary *fileReceivers;
    NSMutableDictionary *fileReceiverDelegateQueue;
}

- (_Bool)existReceiver:(id)arg1;
- (void)fileReceive:(id)arg1 setProgress:(float)arg2 total:(float)arg3;
- (void)fileReceiveCancel:(id)arg1;
- (void)fileReceiveFail:(id)arg1;
- (void)fileReceiveFinish:(id)arg1;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1 forKey:(id)arg2;
- (void)addReceiver:(id)arg1 forKey:(id)arg2;
- (void)removeReceiver:(id)arg1;
- (void)cancelReceiver:(id)arg1;
- (void)addReceiver:(id)arg1 delegate:(id)arg2 path:(id)arg3 needProgress:(_Bool)arg4 fileType:(int)arg5 userInfo:(id)arg6 identifier:(id)arg7;
- (id)filePath:(id)arg1 name:(id)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

