//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MDViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, UITableView, UIView;

@interface MDFriendRadarViewController : MDViewController <UITableViewDataSource, UITableViewDelegate>
{
    UIView *_noNoticeTipView;
    UITableView *_listTableView;
    NSArray *_listArray;
    unsigned long long _lastNoticeCount;
}

@property(retain, nonatomic) UIView *noNoticeTipView; // @synthesize noNoticeTipView=_noNoticeTipView;
@property(nonatomic) unsigned long long lastNoticeCount; // @synthesize lastNoticeCount=_lastNoticeCount;
@property(retain, nonatomic) NSArray *listArray; // @synthesize listArray=_listArray;
@property(retain, nonatomic) UITableView *listTableView; // @synthesize listTableView=_listTableView;
- (void)unreadCounterHasBeenClean:(id)arg1;
- (void)unreadCounter:(id)arg1 countChanged:(unsigned long long)arg2 forKey:(id)arg3;
- (void)unreadCounterInited:(id)arg1;
- (void)didRecvFriendRadarNoticePacket:(id)arg1;
- (void)strangerInfoBatchRequestFinished:(id)arg1;
- (void)requestBtnPressed:(id)arg1;
- (void)userIconBtnPressed:(id)arg1;
- (double)caculateCellHeight:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)closeAction;
- (void)checkLoadMoreStatus;
- (void)loadMoreData;
- (void)configTitleAndBarButtonItems;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

