//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UIImageView, UILabel, UIView;

@interface MDGroupNegativeMemberCell : UITableViewCell
{
    id <MDGroupNegaticveMemberCellDelegate> _delegate;
    UIImageView *_iconImageView;
    UILabel *_nameLabel;
    UIImageView *_ageImageView;
    UIImageView *_levelImageView;
    UILabel *_lastSpokenLabel;
    UIButton *_removeButton;
    UIView *_lineView;
}

@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UIButton *removeButton; // @synthesize removeButton=_removeButton;
@property(retain, nonatomic) UILabel *lastSpokenLabel; // @synthesize lastSpokenLabel=_lastSpokenLabel;
@property(retain, nonatomic) UIImageView *levelImageView; // @synthesize levelImageView=_levelImageView;
@property(retain, nonatomic) UIImageView *ageImageView; // @synthesize ageImageView=_ageImageView;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(nonatomic) __weak id <MDGroupNegaticveMemberCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setupView;
- (void)handleRemoveInactiveMember:(id)arg1;
- (void)bindModel:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

