//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MDCacheUnreadCounter.h"

#import "MDUnreadCounter.h"

@class MFSimpleDatabase, NSString;

@interface MDHelloUnreadCounter : MDCacheUnreadCounter <MDUnreadCounter>
{
    MFSimpleDatabase *mfdb;
    id <MDUnreadCounterDelegate> sessDelegate;
}

- (void)cleanAllGiftSessionUnread;
- (void)cleanAllLiveSessionUnread;
- (void)cleanAllNormalSessionUnread;
- (void)setAllSessionRead;
- (unsigned long long)dbUnreadCountForSession:(id)arg1;
- (void)setDbUnreadCount:(unsigned long long)arg1 forSession:(id)arg2;
- (void)initDbUnreadCount;
- (void)cleanAll;
- (void)cleanForKey:(id)arg1;
- (void)setCount:(unsigned long long)arg1 forKey:(id)arg2;
- (void)removeDelegate;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void)dealloc;
- (id)initWithDatabase:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

