//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "MDImageFliterSelectViewDelegate.h"

@class GPUImageOutput<GPUImageInput>, GPUImagePicture, GPUImageView, MDImageFliterSelectView, NSString, UIActivityIndicatorView, UIButton, UIImage;

@interface MDImageFliterViewController : UIViewController <MDImageFliterSelectViewDelegate>
{
    MDImageFliterSelectView *fliterSelectView;
    GPUImagePicture *staticPicture;
    GPUImageView *mainView;
    GPUImageOutput<GPUImageInput> *filter;
    unsigned long long imageViewRotationMode;
    UIImage *defatuleImage;
    _Bool shouldSave;
    id <MDImageFliterDelegate> aDelegate;
    NSString *currentGUID;
    UIButton *cancelBtn;
    UIButton *rotateBtn;
    UIButton *confirmBtn;
    UIActivityIndicatorView *_indicatorView;
    long long presentenceStyle;
    _Bool _enableFilter;
}

@property(nonatomic) _Bool enableFilter; // @synthesize enableFilter=_enableFilter;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(nonatomic) long long presentenceStyle; // @synthesize presentenceStyle;
@property(copy, nonatomic) GPUImageView *mainView; // @synthesize mainView;
@property(copy, nonatomic) NSString *currentGUID; // @synthesize currentGUID;
@property(nonatomic) _Bool shouldSave; // @synthesize shouldSave;
@property(retain, nonatomic) GPUImageOutput<GPUImageInput> *filter; // @synthesize filter;
@property(nonatomic) id <MDImageFliterDelegate> aDelegate; // @synthesize aDelegate;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)imageFliterSelectMode:(int)arg1;
- (void)didReceiveMemoryWarning;
- (void)clickCircle:(id)arg1;
- (void)doneFliterImage:(id)arg1;
- (void)clickOK:(id)arg1;
- (void)clickReturn:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)getImageWithGUID;
- (void)fileReceiveFail:(id)arg1;
- (void)fileReceiveFinish:(id)arg1;
- (void)downloadImageWithGUID:(id)arg1;
- (void)dealloc;
- (id)initWithGUID:(id)arg1;
- (id)initWithImage:(id)arg1;

@end

