//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MDLBAApi, NSMutableDictionary;

@interface MDLBAShopFeedManager : NSObject
{
    NSMutableDictionary *shopFeedDict;
    MDLBAApi *_lbaApi;
}

@property(retain, nonatomic) MDLBAApi *lbaApi; // @synthesize lbaApi=_lbaApi;
@property(retain, nonatomic) NSMutableDictionary *shopFeedDict; // @synthesize shopFeedDict;
- (void).cxx_destruct;
- (void)getFeedWithFeedId:(id)arg1 andCallBackBlock:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (void)fetchFeedError:(id)arg1;
- (void)fetchFeedFail:(id)arg1;
- (void)fetchFeedSuccess:(id)arg1;
- (void)asyncFetchFeed:(id)arg1;
- (id)getShopFeedById:(id)arg1;
- (id)getShopFeeds:(id)arg1;
- (void)removeShopFeed:(id)arg1;
- (id)insertShopFeed:(id)arg1 feed:(id)arg2;
- (id)setShopFeed:(id)arg1 feed:(id)arg2;
- (id)justModelingShopFeeds:(id)arg1;
- (id)modelingShopFeeds:(id)arg1 shopId:(id)arg2;
- (id)init;

@end

