//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface MDLikeEachNotice : NSObject
{
    NSString *_likeid;
    NSString *_avatar;
    NSDate *_time;
    NSString *_nickName;
    NSString *_targetid;
    NSString *_gender;
    long long _level;
    NSString *_text;
}

@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(nonatomic) long long level; // @synthesize level=_level;
@property(copy, nonatomic) NSString *gender; // @synthesize gender=_gender;
@property(copy, nonatomic) NSString *targetid; // @synthesize targetid=_targetid;
@property(copy, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(retain, nonatomic) NSDate *time; // @synthesize time=_time;
@property(copy, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(copy, nonatomic) NSString *likeid; // @synthesize likeid=_likeid;
- (void).cxx_destruct;
- (id)initWithPacket:(id)arg1;

@end

