//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class MDEmojiLabel, MDFeedComment, MDRTTruncationView, UIImageView, UILabel;

@interface MDMyCommentCell : UITableViewCell
{
    MDFeedComment *comment;
    UIImageView *_backView;
    UIImageView *_headImageView;
    UILabel *_nameLabel;
    UIImageView *_sexImageView;
    UILabel *_timeLabel;
    UIImageView *_feedImageView;
    MDRTTruncationView *_rtView;
    MDEmojiLabel *_contentLabel;
    id <MDMyCommentCellDelegate> _delegate;
}

@property(nonatomic) id <MDMyCommentCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) MDEmojiLabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) MDRTTruncationView *rtView; // @synthesize rtView=_rtView;
@property(retain, nonatomic) UIImageView *feedImageView; // @synthesize feedImageView=_feedImageView;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UIImageView *sexImageView; // @synthesize sexImageView=_sexImageView;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *headImageView; // @synthesize headImageView=_headImageView;
@property(retain, nonatomic) UIImageView *backView; // @synthesize backView=_backView;
@property(retain, nonatomic) MDFeedComment *comment; // @synthesize comment;
- (void)dealloc;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)clickHeadGoProfile;
- (void)longPressGestureHappened:(id)arg1;
- (void)resetToDefault;
- (void)decorateCommentCell:(id)arg1 content:(id)arg2;
- (void)awakeFromNib;

@end

