//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSDictionary, UIButton, UIImageView, UILabel;

@interface MDNearbyCommonGuideView : UIView
{
    id <MDNearbyCommonGuideViewDelegate> _delegate;
    UIImageView *_iconView;
    UILabel *_titleLabel;
    UILabel *_descLabel;
    UIButton *_closeButton;
    UIButton *_actionButton;
    UIImageView *_backgroudView;
    NSDictionary *_guideInfo;
}

+ (id)nearbyCommonGuideView;
@property(retain, nonatomic) NSDictionary *guideInfo; // @synthesize guideInfo=_guideInfo;
@property(retain, nonatomic) UIImageView *backgroudView; // @synthesize backgroudView=_backgroudView;
@property(retain, nonatomic) UIButton *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(nonatomic) __weak id <MDNearbyCommonGuideViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)closeButtonClicked:(id)arg1;
- (void)actionButtonClicked:(id)arg1;
- (void)decorateNearbyCommonGuideView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

