//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MDViewController.h"

#import "MDRoamButtonDelegate.h"
#import "MDRoamHandleDelegate.h"
#import "MKMapViewDelegate.h"
#import "UIAccelerometerDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UISearchBarDelegate.h"
#import "UISearchDisplayDelegate.h"

@class CLGeocoder, ClickMoreView, MBProgressHUD, MDRoamButton, MDRoamHandler, MDRoamStartView, MKMapView, MMUISearchBar, NSString, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UISearchDisplayController, UITableView;

@interface MDRoamViewController : MDViewController <MKMapViewDelegate, MDRoamHandleDelegate, UIAccelerometerDelegate, UIAlertViewDelegate, MDRoamButtonDelegate, UISearchBarDelegate, UISearchDisplayDelegate>
{
    MDRoamStartView *holdView;
    UITableView *table;
    MKMapView *map;
    MDRoamHandler *myHandler;
    UIActivityIndicatorView *act;
    UIImageView *imageShadow;
    UIImageView *imageLoc;
    UILabel *siteTextLabel;
    UILabel *vipRoamNoticeLabel;
    ClickMoreView *loadMoreButton;
    UIImageView *siteBackView;
    UIButton *backButton;
    MDRoamButton *roamButton;
    int showType;
    CLGeocoder *myGeocoder;
    NSString *noticeString;
    NSString *roamString;
    double lat;
    double lng;
    double vipLat;
    double vipLng;
    double RoamVigor;
    double roamPress;
    unsigned long long RoamShakeCount;
    _Bool isRoamed;
    _Bool isVipRoam;
    unsigned long long loadFromIdx;
    int roamSourceType;
    MBProgressHUD *hud;
    UISearchDisplayController *searchController;
    MMUISearchBar *search;
}

@property(nonatomic) int roamSourceType; // @synthesize roamSourceType;
@property(retain, nonatomic) ClickMoreView *loadMoreButton; // @synthesize loadMoreButton;
@property(retain, nonatomic) MMUISearchBar *search; // @synthesize search;
@property(retain, nonatomic) UISearchDisplayController *searchController; // @synthesize searchController;
@property(retain, nonatomic) CLGeocoder *myGeocoder; // @synthesize myGeocoder;
@property(retain, nonatomic) NSString *noticeString; // @synthesize noticeString;
@property(retain, nonatomic) NSString *roamString; // @synthesize roamString;
@property(retain, nonatomic) MBProgressHUD *hud; // @synthesize hud;
@property(retain, nonatomic) UILabel *vipRoamNoticeLabel; // @synthesize vipRoamNoticeLabel;
@property(retain, nonatomic) MDRoamButton *roamButton; // @synthesize roamButton;
@property(retain, nonatomic) UIImageView *siteBackView; // @synthesize siteBackView;
@property(retain, nonatomic) MDRoamStartView *holdView; // @synthesize holdView;
@property(retain, nonatomic) UIButton *backButton; // @synthesize backButton;
@property(nonatomic) double vipLng; // @synthesize vipLng;
@property(nonatomic) double vipLat; // @synthesize vipLat;
@property(nonatomic) double lng; // @synthesize lng;
@property(nonatomic) double lat; // @synthesize lat;
@property(retain, nonatomic) UIImageView *imageShadow; // @synthesize imageShadow;
@property(retain, nonatomic) UIImageView *imageLoc; // @synthesize imageLoc;
@property(retain, nonatomic) UIActivityIndicatorView *act; // @synthesize act;
@property(retain, nonatomic) UILabel *siteTextLabel; // @synthesize siteTextLabel;
@property(retain, nonatomic) MKMapView *map; // @synthesize map;
@property(retain, nonatomic) MDRoamHandler *myHandler; // @synthesize myHandler;
@property(retain, nonatomic) UITableView *table; // @synthesize table;
@property(nonatomic) int showType; // @synthesize showType;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)removeHud;
- (void)showHud;
- (void)backTo;
- (void)animationBegin;
- (void)roamBegin:(double)arg1;
- (void)refreshList;
- (void)stopLoadMore;
- (void)addLoadMoreIndex;
- (void)roamByLocation:(int)arg1 ShowString:(id)arg2;
- (void)roamByShake:(int)arg1 ShowString:(id)arg2;
- (void)getSiteName:(int)arg1 ShowString:(id)arg2;
- (void)siteNameChange:(id)arg1;
- (void)changeRoamSiteName:(id)arg1 isVipRoam:(_Bool)arg2;
- (void)setVipLatAndLng:(double)arg1:(double)arg2;
- (void)setLatAndLng:(double)arg1:(double)arg2;
- (void)resetTheImageLoc;
- (void)imageLocBeginAnimation;
- (void)changeMap;
- (void)getNewLocation;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(_Bool)arg2;
- (void)reviseLocationFinish;
- (void)setLocationRegion:(int)arg1;
- (void)showSearchList;
- (void)hideSearchList;
- (void)addMapAndTable;
- (void)setNavLeftButton:(_Bool)arg1;
- (void)setNavRightButton:(_Bool)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showNotVipAlert;
- (void)checkAndDone;
- (void)chooseLocationToRoam;
- (void)loadMore;
- (void)clickRightButton;
- (void)clickBackButton;
- (void)beginRoamAnimation;
- (void)setRoamNotice:(id)arg1;
- (void)changeUI;
- (void)adjustForVipCenter;
- (void)viewDidLoad;
- (void)viewDidAppear:(_Bool)arg1;
- (void)clickMap;
- (void)mapView:(id)arg1 didSelectAnnotationView:(id)arg2;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)addAnnotationArray:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

