//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MDSearchHandler.h"

#import "MDFavoriteApiOperationDelegate.h"

@class MDFavoriteApiOperation, MDFavoriteItem, NSString;

@interface MDSearchFavoriteHandler : MDSearchHandler <MDFavoriteApiOperationDelegate>
{
    NSString *_searchKeyWord;
    MDFavoriteApiOperation *_apiOperation;
    long long _selectedIndex;
    MDFavoriteItem *_selectedItem;
}

@property(retain, nonatomic) MDFavoriteItem *selectedItem; // @synthesize selectedItem=_selectedItem;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(retain, nonatomic) MDFavoriteApiOperation *apiOperation; // @synthesize apiOperation=_apiOperation;
@property(retain, nonatomic) NSString *searchKeyWord; // @synthesize searchKeyWord=_searchKeyWord;
- (void)searchFavoriteFinishedWithStatus:(int)arg1 errmsg:(id)arg2 itemList:(id)arg3;
- (void)sendSearchWording:(id)arg1;
- (void)searchFavoriteWithKeyword:(id)arg1 index:(long long)arg2;
- (void)deleteFavoriteWithId:(id)arg1;
- (void)addFavoriteWithItem:(id)arg1;
- (_Bool)isAddable;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)beginSearch;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1 tableView:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

