//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MDApiBase.h"

@class MDAPICached;

@interface MDSecurityApi : MDApiBase
{
    MDAPICached *_apiCache;
}

@property(retain, nonatomic) MDAPICached *apiCache; // @synthesize apiCache=_apiCache;
- (void).cxx_destruct;
- (void)checkPayPassWordCodeWithParams:(id)arg1 andResponseCallback:(CDUnknownBlockType)arg2;
- (void)getChangePwdSafePhoneCodeTarget:(id)arg1 okSelector:(SEL)arg2 errSelector:(SEL)arg3 failSelector:(SEL)arg4;
- (void)bindPhoneWithUrl:(id)arg1 postParam:(id)arg2 target:(id)arg3 okSelector:(SEL)arg4 errSelector:(SEL)arg5 failSelector:(SEL)arg6;
- (void)resetPwdOldApiWithPostParams:(id)arg1 target:(id)arg2 okSelector:(SEL)arg3 errSelector:(SEL)arg4 failSelector:(SEL)arg5;
- (void)resetPwdWithPostParams:(id)arg1 target:(id)arg2 okSelector:(SEL)arg3 errSelector:(SEL)arg4 failSelector:(SEL)arg5;
- (void)checkVerifyCodeWithUrl:(id)arg1 postParam:(id)arg2 target:(id)arg3 okSelector:(SEL)arg4 errSelector:(SEL)arg5 failSelector:(SEL)arg6;
- (void)fetchVerifyCodeWithUrl:(id)arg1 postParam:(id)arg2 target:(id)arg3 okSelector:(SEL)arg4 errSelector:(SEL)arg5 failSelector:(SEL)arg6;
- (void)setPwdByEmailwithAccount:(id)arg1 token:(id)arg2 target:(id)arg3 okSelector:(SEL)arg4 errSelector:(SEL)arg5 failSelector:(SEL)arg6;
- (void)checkMomoAccount:(id)arg1 token:(id)arg2 target:(id)arg3 okSelector:(SEL)arg4 errSelector:(SEL)arg5 failSelector:(SEL)arg6;
- (void)bindIdCardCheck:(id)arg1 okSelector:(SEL)arg2 errSelector:(SEL)arg3 failSelector:(SEL)arg4;
- (void)bindIdCardCheckPhoneCode:(id)arg1 verifyCode:(id)arg2 okSelector:(SEL)arg3 errSelector:(SEL)arg4 failSelector:(SEL)arg5;
- (void)bindIdCardGetPhoneCode:(id)arg1 okSelector:(SEL)arg2 errSelector:(SEL)arg3 failSelector:(SEL)arg4;
- (void)bindIDCard:(id)arg1 name:(id)arg2 idCard:(id)arg3 idCardImage:(id)arg4 groupImage:(id)arg5 okSelector:(SEL)arg6 errSelector:(SEL)arg7 failSelector:(SEL)arg8;
- (void)phoneCheckIDCard:(id)arg1 name:(id)arg2 idCard:(id)arg3 idCardImage:(id)arg4 groupImage:(id)arg5 account:(id)arg6 okSelector:(SEL)arg7 errSelector:(SEL)arg8 failSelector:(SEL)arg9;
- (void)securityCenterInfo:(id)arg1 okSelector:(SEL)arg2 errSelector:(SEL)arg3 failSelector:(SEL)arg4;

@end

