//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MDPersonalProfileCellModel.h"

@class NSArray, NSString;

@interface MDSettingCellModel : MDPersonalProfileCellModel
{
    _Bool _showBandageNew;
    _Bool _showAlertTip;
    _Bool _isDetailPhoneNum;
    int _badgeCount;
    int _tag;
    NSString *_iconName;
    NSString *_iconURL;
    NSString *_badgeText;
    NSString *_badgeString;
    id _modelInfo;
    NSArray *_iconNameArray;
}

+ (id)cellModelWithTitle:(id)arg1 detail:(id)arg2 iconName:(id)arg3;
@property(retain, nonatomic) NSArray *iconNameArray; // @synthesize iconNameArray=_iconNameArray;
@property(retain, nonatomic) id modelInfo; // @synthesize modelInfo=_modelInfo;
@property(copy, nonatomic) NSString *badgeString; // @synthesize badgeString=_badgeString;
@property(nonatomic) _Bool isDetailPhoneNum; // @synthesize isDetailPhoneNum=_isDetailPhoneNum;
@property(nonatomic) int tag; // @synthesize tag=_tag;
@property(nonatomic) _Bool showAlertTip; // @synthesize showAlertTip=_showAlertTip;
@property(nonatomic) _Bool showBandageNew; // @synthesize showBandageNew=_showBandageNew;
@property(nonatomic) int badgeCount; // @synthesize badgeCount=_badgeCount;
@property(copy, nonatomic) NSString *badgeText; // @synthesize badgeText=_badgeText;
@property(copy, nonatomic) NSString *iconURL; // @synthesize iconURL=_iconURL;
@property(copy, nonatomic) NSString *iconName; // @synthesize iconName=_iconName;
- (void)dealloc;
- (id)initWithTitle:(id)arg1 detail:(id)arg2 iconName:(id)arg3;

@end

