//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MDSNSInviteFriendsHandler.h"

#import "UIAlertViewDelegate.h"

@class NSString;

@interface MDSinaInviteFriendsHandler : MDSNSInviteFriendsHandler <UIAlertViewDelegate>
{
}

- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)didClickInviteButtonInAddCell:(id)arg1;
- (id)cellWithSinaContact:(id)arg1 tableView:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)refreshDataAfterInvite;
- (id)lastLoadFromServerDate;
- (void)bindSNSID;
- (void)reloadWeiboFriendDataFinished:(id)arg1;
- (void)processFriendListDataWithArray:(id)arg1;
- (void)loadFriendsListFromServer;
- (void)loadFriendsListFromCache;
- (id)getChatSource;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

