//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MDDisplayTaskDelegate.h"

@class NSMutableArray, NSString, UIColor, UIView;

@interface MDViewNode : NSObject <MDDisplayTaskDelegate>
{
    _Bool _hidden;
    _Bool _asyncComposed;
    MDViewNode *_superNode;
    NSMutableArray *_subNodes;
    long long _contentMode;
    long long _tag;
    UIColor *_backgroundColor;
    UIColor *_borderColor;
    double _borderWidth;
    double _cornerRadius;
    CDUnknownBlockType _viewBlock;
    struct CGRect _frame;
}

@property(copy, nonatomic) CDUnknownBlockType viewBlock; // @synthesize viewBlock=_viewBlock;
@property(nonatomic) _Bool asyncComposed; // @synthesize asyncComposed=_asyncComposed;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) double borderWidth; // @synthesize borderWidth=_borderWidth;
@property(copy, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(copy, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) long long tag; // @synthesize tag=_tag;
@property(nonatomic) _Bool hidden; // @synthesize hidden=_hidden;
@property(nonatomic) long long contentMode; // @synthesize contentMode=_contentMode;
@property(retain, nonatomic) NSMutableArray *subNodes; // @synthesize subNodes=_subNodes;
@property(nonatomic) __weak MDViewNode *superNode; // @synthesize superNode=_superNode;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
- (void).cxx_destruct;
- (id)createDisplayTask;
- (void)updateUI;
- (_Bool)isTouchMeWithTouch:(id)arg1 inNode:(id)arg2;
- (_Bool)isTouchMeWithTouch:(id)arg1;
- (_Bool)isTouchMe:(struct CGPoint)arg1;
@property(readonly, nonatomic) UIView *view;
- (void)drawSubNodesInContext:(struct CGContext *)arg1 cancel:(CDUnknownBlockType)arg2;
- (void)drawContentInContext:(struct CGContext *)arg1 drawRect:(struct CGRect)arg2 cancel:(CDUnknownBlockType)arg3;
- (void)drawInContext:(struct CGContext *)arg1 cancel:(CDUnknownBlockType)arg2;
- (id)dispalyImage;
- (struct CGRect)frameConverToRootNode;
- (struct CGPoint)originConverToSuperNode:(id)arg1 point:(struct CGPoint)arg2;
- (void)sendSubNodeToBack:(id)arg1;
- (void)bringSubNodeToFront:(id)arg1;
- (void)insertSubNode:(id)arg1 atIndex:(long long)arg2;
- (void)addSubNode:(id)arg1;
- (void)removeAllSubNodes;
- (void)removeFromSuperNode;
@property(nonatomic) double centerY;
@property(nonatomic) double centerX;
@property(nonatomic) struct CGPoint center;
@property(nonatomic) double height;
@property(nonatomic) double width;
@property(nonatomic) struct CGSize size;
@property(nonatomic) double bottom;
@property(nonatomic) double right;
@property(nonatomic) double top;
@property(nonatomic) double left;
@property(nonatomic) struct CGPoint origin;
@property(nonatomic) struct CGRect bounds;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

