//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSMutableSet;

@interface MFTableMigrationBase : NSObject
{
    CDUnknownBlockType _queryTableBlock;
    CDUnknownBlockType _createTableBlock;
    NSArray *_removeKeys;
    NSDictionary *_replaceKeys;
    NSMutableSet *_tableNameSet;
}

+ (_Bool)createTableWithDatabase:(id)arg1 tableName:(id)arg2;
+ (void)alterTableWithTableName:(id)arg1 database:(id)arg2;
+ (void)recordErrorWithContent:(id)arg1;
+ (_Bool)createHelloSessionTableWithDatabase:(id)arg1;
+ (void)dropTableNameAndEnsureWithType:(int)arg1 targetid:(id)arg2;
+ (id)tableNameAndEnsureWithType:(int)arg1 targetid:(id)arg2 db:(id)arg3;
+ (id)migrationTableName;
+ (id)migrationClassArray;
@property(retain, nonatomic) NSMutableSet *tableNameSet; // @synthesize tableNameSet=_tableNameSet;
@property(retain, nonatomic) NSDictionary *replaceKeys; // @synthesize replaceKeys=_replaceKeys;
@property(retain, nonatomic) NSArray *removeKeys; // @synthesize removeKeys=_removeKeys;
@property(copy, nonatomic) CDUnknownBlockType createTableBlock; // @synthesize createTableBlock=_createTableBlock;
@property(copy, nonatomic) CDUnknownBlockType queryTableBlock; // @synthesize queryTableBlock=_queryTableBlock;
- (void).cxx_destruct;
- (id)iDsFromSessionWithDatabase:(id)arg1 type:(int)arg2 range:(struct _NSRange)arg3 alias:(id)arg4;
- (_Bool)realMigrationWithDatabase:(id)arg1 model:(unsigned long long)arg2;
- (_Bool)migrationCurrentTableWithDatabase:(id)arg1 model:(unsigned long long)arg2;
- (id)init;
- (void)dealloc;

@end

