//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

@interface MLAllStarRankHeaderView : UIView
{
    UILabel *_titleLabel;
    UILabel *_midLabel;
    UILabel *_bottomLabel;
    CDUnknownBlockType _closeHandler;
}

@property(copy, nonatomic) CDUnknownBlockType closeHandler; // @synthesize closeHandler=_closeHandler;
@property(nonatomic) __weak UILabel *bottomLabel; // @synthesize bottomLabel=_bottomLabel;
@property(nonatomic) __weak UILabel *midLabel; // @synthesize midLabel=_midLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)didClickClose:(id)arg1;

@end

