//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@protocol MLConferenceSelectViewDelegate <NSObject>
- (void)masterConferenceLocalSwitchStatus:(_Bool)arg1;
- (void)showUserCardWithMomoid:(NSString *)arg1;
- (void)closeConferenceWithAlertForMomoid:(NSString *)arg1 completion:(void (^)(_Bool))arg2;
- (void)confirmConferenceWithMomoid:(NSString *)arg1 name:(NSString *)arg2 charmsNum:(long long)arg3 fortuneNum:(long long)arg4 avatar:(NSString *)arg5 thumbs:(unsigned long long)arg6 rankingPhoto:(NSArray *)arg7;
@end

