//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSString;

@interface MLPBDownSet_UserCharmLevelUp : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) int charmLevel; // @dynamic charmLevel;
@property(nonatomic) _Bool hasCharmLevel; // @dynamic hasCharmLevel;
@property(nonatomic) _Bool hasStarid; // @dynamic hasStarid;
@property(nonatomic) _Bool hasUserImg; // @dynamic hasUserImg;
@property(copy, nonatomic) NSString *starid; // @dynamic starid;
@property(copy, nonatomic) NSString *userImg; // @dynamic userImg;

@end

