//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MLPlayerDelegate.h"

@class MLPlayerConfiguration, MLPlayerStatistic, MLVideoLoadingView, NSArray, NSString, UIView;

@interface MLPlayerManager : NSObject <MLPlayerDelegate>
{
    _Bool _isDidRender;
    _Bool _isRendered;
    _Bool _needsReplayForInterruption;
    id <MLPlayerManagerDelegate> _delegate;
    UIView *_view;
    unsigned long long _state;
    MLPlayerConfiguration *_configuration;
    NSArray *_subVideoDisplayFrames;
    UIView *_renderView;
    MLVideoLoadingView *_stallingView;
    UIView *_lastVideoFrameView;
    id <MLPlayer> _player;
    MLPlayerStatistic *_currentStatistic;
}

+ (id)sharedManager;
@property(retain, nonatomic) MLPlayerStatistic *currentStatistic; // @synthesize currentStatistic=_currentStatistic;
@property(retain, nonatomic) id <MLPlayer> player; // @synthesize player=_player;
@property(retain, nonatomic) UIView *lastVideoFrameView; // @synthesize lastVideoFrameView=_lastVideoFrameView;
@property(retain, nonatomic) MLVideoLoadingView *stallingView; // @synthesize stallingView=_stallingView;
@property(retain, nonatomic) UIView *renderView; // @synthesize renderView=_renderView;
@property(nonatomic) _Bool needsReplayForInterruption; // @synthesize needsReplayForInterruption=_needsReplayForInterruption;
@property(retain, nonatomic) NSArray *subVideoDisplayFrames; // @synthesize subVideoDisplayFrames=_subVideoDisplayFrames;
@property(nonatomic) _Bool isRendered; // @synthesize isRendered=_isRendered;
@property(retain, nonatomic) MLPlayerConfiguration *configuration; // @synthesize configuration=_configuration;
@property(nonatomic) _Bool isDidRender; // @synthesize isDidRender=_isDidRender;
@property(nonatomic) unsigned long long state; // @synthesize state=_state;
@property(retain, nonatomic) UIView *view; // @synthesize view=_view;
@property(nonatomic) __weak id <MLPlayerManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)getConferencesDisplayFrames;
- (void)setConferences:(id)arg1;
- (_Bool)isPlayerOfConfiguration:(id)arg1;
- (void)recordAudio:(_Bool)arg1;
- (void)stopPlaying;
- (_Bool)startPlayingByConfiguration:(id)arg1;
@property(readonly, copy, nonatomic) NSString *roomID;
- (void)player:(id)arg1 didChangeFramesOfConference:(id)arg2;
- (void)playerEndStalling:(id)arg1;
- (void)playerStartStalling:(id)arg1;
- (void)playerFailed:(id)arg1;
- (void)playerDidFinish:(id)arg1;
- (void)playerStartRendering:(id)arg1;
- (void)startPlayingFailed;
- (void)startPlayingStalled;
- (void)cleanStartPlayingDeadline;
- (void)setupStartPlayingDeadline;
- (void)cleanLastVideoFrame;
- (void)snapshotLastVideoFrame;
- (void)setStallingTextHidden:(_Bool)arg1;
- (void)dismissStallingView;
- (void)showStallingView;
- (void)observeAudioSessionEnd:(id)arg1;
- (void)observeAudioSessionBegin:(id)arg1;
- (void)observeApplicationDidBecomeActive:(id)arg1;
- (void)observeAudioSessionInterruption:(id)arg1;
- (void)dealloc;
- (id)init;
- (void)markStreamToConferenceRefetchFailedForRoomID:(id)arg1;
- (void)markStreamToConferenceRefetchEndForRoomID:(id)arg1;
- (void)markStreamToConferenceRefetchStartForRoomID:(id)arg1;
- (_Bool)isSwitchingStreamToConferenceForRoomID:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

