//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel;

@interface MLRankPositionView : UIView
{
    CDUnknownBlockType _didTapRankPositionView;
    UIImageView *_levelImageView;
    UIImageView *_arrowImageView;
    UILabel *_label;
}

+ (Class)layerClass;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(retain, nonatomic) UIImageView *levelImageView; // @synthesize levelImageView=_levelImageView;
@property(copy, nonatomic) CDUnknownBlockType didTapRankPositionView; // @synthesize didTapRankPositionView=_didTapRankPositionView;
- (void).cxx_destruct;
- (void)setWithPositionChangedModel:(id)arg1;
- (void)setWithText:(id)arg1;
- (void)setWithText:(id)arg1 charmLevel:(long long)arg2;
- (void)setWithPosition:(long long)arg1 charmLevel:(long long)arg2;
- (void)didClickView;
- (void)addTapGesture;
- (id)gradientColorArrayWithCharmLevel:(long long)arg1;
- (id)labelColorWithPostion:(long long)arg1;
- (void)addArrowImageView;
- (void)addLabel;
- (void)addImageView;
- (id)gradientLayer;
- (id)initWithFrame:(struct CGRect)arg1;

@end

