//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSLayoutConstraint, UILabel;

@interface MLUserRankHeaderView : UIView
{
    UILabel *_titleLabel;
    UILabel *_subTitleLabel;
    NSLayoutConstraint *_titleCenterYConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *titleCenterYConstraint; // @synthesize titleCenterYConstraint=_titleCenterYConstraint;
@property(nonatomic) __weak UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;

@end

