//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (JSONKitSerializingBlockAdditions)
- (id)MDJSONStringWithOptions:(unsigned long long)arg1 serializeUnsupportedClassesUsingBlock:(CDUnknownBlockType)arg2 error:(id *)arg3;
- (id)MDJSONDataWithOptions:(unsigned long long)arg1 serializeUnsupportedClassesUsingBlock:(CDUnknownBlockType)arg2 error:(id *)arg3;
@end

