//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol RecorderBusDelegate
- (void)sendPcmCancel;
- (void)sendPcmOver;
- (void)sendPcm:(void *)arg1 byteSize:(unsigned int)arg2;
- (void)sendPcmPrepareWithASBD:(struct AudioStreamBasicDescription)arg1;
@end

