//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MDViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSDictionary, NSMutableArray, NSString, UIImageView, UILabel, UITableView;

@interface SecurityCenterViewController : MDViewController <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _isFirst;
    UITableView *myTableview;
    NSMutableArray *cellModelArray;
    UILabel *securityLabel;
    UILabel *descriptionLabel;
    UIImageView *securityGradeImageView;
    NSDictionary *_contentDict;
}

+ (void)fetchSecurityInfoFail:(id)arg1;
+ (void)fetchSecurityInfoError:(id)arg1;
+ (void)fetchSecurityInfoSuccess:(id)arg1;
+ (void)pustToSecurityCenter;
@property(nonatomic) _Bool isFirst; // @synthesize isFirst=_isFirst;
@property(retain, nonatomic) NSDictionary *contentDict; // @synthesize contentDict=_contentDict;
@property(retain, nonatomic) UIImageView *securityGradeImageView; // @synthesize securityGradeImageView;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel;
@property(retain, nonatomic) UILabel *securityLabel; // @synthesize securityLabel;
@property(retain, nonatomic) NSMutableArray *cellModelArray; // @synthesize cellModelArray;
@property(retain, nonatomic) UITableView *myTableview; // @synthesize myTableview;
- (void)didReceiveMemoryWarning;
- (void)viewDidUnload;
- (void)forceRefreshData;
- (void)resetDetailLabelTextColor:(id)arg1 cell:(id)arg2;
- (void)refreshHeaderViewContent;
- (long long)getAccreditDeviceState;
- (long long)getBindIdInfo;
- (id)getBindPhone;
- (long long)getPasswordIntensity;
- (long long)getSecurityLevel;
- (void)checkIfNeedUpdateSafeLevel;
- (void)getSecurityInfoSuccess:(id)arg1;
- (void)getSecurityInfo;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)accreditedDeviceCellModel;
- (id)idInfoCellModel;
- (id)phoneAccountCellModel;
- (id)passwordSettingCellModel;
- (void)setupCellModelArray;
- (void)initHeaderView;
- (void)initTableView;
- (void)retunButtonClicked;
- (void)initNavBar;
- (void)accreditedDeviceCellClicked;
- (void)idInfoCellClicked;
- (void)phoneAccountCellClicked;
- (void)passwordSettingCellClicked;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

