//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface SKGCDTimerManager : NSObject
{
    NSMutableDictionary *_timerContainer;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *timerContainer; // @synthesize timerContainer=_timerContainer;
- (void).cxx_destruct;
- (void)cancelAllTimer;
- (void)cancelTimerWithName:(id)arg1;
- (void)scheduledDispatchTimerWithName:(id)arg1 timeInterval:(double)arg2 delay:(double)arg3 queue:(id)arg4 repeats:(_Bool)arg5 action:(CDUnknownBlockType)arg6;

@end

