//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (SKHex)
+ (id)sk_colorFromHexString:(id)arg1;
+ (void)sk_colorWithHex:(unsigned int)arg1 red:(int *)arg2 green:(int *)arg3 blue:(int *)arg4 alpha:(int *)arg5;
+ (id)sk_colorWithARGBHex:(unsigned int)arg1;
+ (id)sk_colorWithHex:(unsigned int)arg1;
+ (id)sk_colorWithRed:(double)arg1 green:(double)arg2 blue:(double)arg3;
+ (id)sk_colorWithRed:(double)arg1 green:(double)arg2 blue:(double)arg3 alpha:(double)arg4;
+ (id)sk_colorWithHexString:(id)arg1;
@end

