//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface UIViewController (Growing_private)
- (_Bool)isBigEnoughForAPage;
- (void)GROW_setViewControllerState:(long long)arg1;
@end

