//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class NSArray;

@interface ASHighlightOverlayLayer : CALayer
{
    NSArray *_rects;
    CALayer *_targetLayer;
}

+ (id)defaultActionForKey:(id)arg1;
+ (_Bool)needsDisplayForKey:(id)arg1;
+ (id)defaultValueForKey:(id)arg1;
@property __weak CALayer *targetLayer; // @synthesize targetLayer=_targetLayer;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1;
- (void)drawInContext:(struct CGContext *)arg1;
- (id)initWithRects:(id)arg1 targetLayer:(id)arg2;
- (id)initWithRects:(id)arg1;

// Remaining properties
@property(retain) struct CGColor *highlightColor; // @dynamic highlightColor;

@end

