//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JDBaseToastViewDelegate.h"

@class JDStoreNetwork, NSString;

@interface BrowserCommManager : NSObject <JDBaseToastViewDelegate>
{
    JDStoreNetwork *_networkGenToken;
    JDStoreNetwork *_networkGetToken;
    NSString *_userAgent;
    NSString *_secretAgentString;
    NSString *_internalThreadSafeUserAgent;
}

+ (id)sharedBrowserCommManager;
+ (void)webGame_showFullScreenWithURL:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
@property(copy) NSString *internalThreadSafeUserAgent; // @synthesize internalThreadSafeUserAgent=_internalThreadSafeUserAgent;
@property(copy, nonatomic) NSString *secretAgentString; // @synthesize secretAgentString=_secretAgentString;
@property(copy, nonatomic) NSString *userAgent; // @synthesize userAgent=_userAgent;
- (void).cxx_destruct;
- (void)genTokenFinishedWithWebViewController:(id)arg1 urlString:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)pushWebviewContorller:(id)arg1 requestAction:(int)arg2 actionName:(id)arg3 params:(id)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
- (void)pushWebviewContorllerWithSubClassName:(id)arg1 requestAction:(int)arg2 actionName:(id)arg3 params:(id)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
- (void)pushWebviewContorllerWithRequestAction:(int)arg1 actionName:(id)arg2 params:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)getTokenValue:(id)arg1;
- (void)didCancelInToastView:(id)arg1;
- (void)didFinishInToastView:(id)arg1;
- (void)payWithPayId:(id)arg1 type:(long long)arg2;
- (id)currentNavigationController;
- (void)callChannelTokenWithRequestActionByBlock:(int)arg1 actionName:(id)arg2 params:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (int)checkAction:(id)arg1;
- (id)getParamsStrWithParams:(id)arg1;
- (void)stopMCommunication;
- (void)stopHandle;
- (id)descriptionOfNetworkStatus:(unsigned long long)arg1;
- (id)updateWebViewUserAgent;
- (id)customWebViewUserAgent;
- (id)threadSafeUserAgent;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

