//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class JDButton, JDPromotionModel, NSArray, NSMutableArray;

@interface CartPromotionCell : UITableViewCell
{
    struct CGRect radioRect;
    NSArray *_models;
    JDPromotionModel *_promotionModel;
    CDUnknownBlockType _selectionBlock;
    JDButton *_radioButton;
    NSMutableArray *_accessElements;
}

@property(retain, nonatomic) NSMutableArray *accessElements; // @synthesize accessElements=_accessElements;
@property(retain, nonatomic) JDButton *radioButton; // @synthesize radioButton=_radioButton;
@property(copy, nonatomic) CDUnknownBlockType selectionBlock; // @synthesize selectionBlock=_selectionBlock;
@property(retain, nonatomic) JDPromotionModel *promotionModel; // @synthesize promotionModel=_promotionModel;
@property(retain, nonatomic) NSArray *models; // @synthesize models=_models;
- (void).cxx_destruct;
- (void)hideSeperateLine;
- (void)changeStateSelected:(_Bool)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (_Bool)isSelected;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

