//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDViewController.h"

#import "ProductCategorySelectionDelegate.h"
#import "SDWebImageManagerDelegate.h"

@class CameraImageHelper, JDStoreNetwork, NSCondition, NSMutableArray, NSMutableDictionary, NSString, NSTimer, UIButton, UIImageView, UIView;

@interface ColorBuyViewController : JDViewController <SDWebImageManagerDelegate, ProductCategorySelectionDelegate>
{
    JDStoreNetwork *dao_;
    _Bool capturePause;
    int downloadIndex;
    _Bool bRun;
    UIButton *btCamera_;
    UIView *videoView_;
    UIView *viewBar_;
    UIView *viewFrame_;
    NSString *networkType_;
    UIImageView *imgPormpt_;
    NSTimer *tmPhoto_;
    NSCondition *condition_;
    CameraImageHelper *cameraImageHelper_;
    UIButton *rightButton_;
    NSMutableDictionary *modelWithUrlDic_;
    NSMutableArray *modelOnShowArray_;
    NSMutableArray *modelWaitingArray_;
    NSMutableArray *searchCategory;
    UIButton *rightButtonView;
}

- (void)didSelectCategory:(id)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)showTimerFired:(id)arg1;
- (void)webImageManager:(id)arg1 didFailWithError:(id)arg2 forURL:(id)arg3;
- (void)webImageManager:(id)arg1 didFinishWithImage:(id)arg2 forURL:(id)arg3;
- (_Bool)isInList:(id)arg1;
- (void)didFinishResponseWitRequestSetup:(id)arg1 components:(id)arg2 msg:(id)arg3;
- (void)reconnect;
- (void)searchProduct:(id)arg1;
- (void)searchColorImage:(id)arg1;
- (void)colorImage:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)selectCameraButton:(id)arg1;
- (void)enterForceGround;
- (void)enterBackGround;
- (void)viewDidLoad;
- (void)showProductCategory;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

