//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString;

@interface FinalSearchChannelTitleView : UIView
{
    NSString *_title;
}

@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)willMoveToSuperview:(id)arg1;
- (void)hiddenChannelTitleView;
- (void)willHiddenChannelTitleView;
- (void)createLineViewWithOrginY:(double)arg1;
- (void)createChannelTitleView;
- (id)initWithFrame:(struct CGRect)arg1 title:(id)arg2;

@end

