//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDFinderTableViewCell.h"

@class NSMutableArray;

@interface FinderInventoryDetailSkuCell : JDFinderTableViewCell
{
    CDUnknownBlockType _clickSku;
    NSMutableArray *_viewArray;
}

@property(retain, nonatomic) NSMutableArray *viewArray; // @synthesize viewArray=_viewArray;
@property(copy, nonatomic) CDUnknownBlockType clickSku; // @synthesize clickSku=_clickSku;
- (void).cxx_destruct;
- (void)tapSku:(id)arg1;
- (void)assignValue:(id)arg1;
- (void)layoutSubviews;
- (void)setupViews;

@end

