//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FinderCellModelProtocol.h"

@class NSString;

@interface FinderLastPageModel : NSObject <FinderCellModelProtocol>
{
    NSString *_alertText;
    NSString *_backColor;
}

@property(copy, nonatomic) NSString *backColor; // @synthesize backColor=_backColor;
@property(copy, nonatomic) NSString *alertText; // @synthesize alertText=_alertText;
- (void).cxx_destruct;
@property(readonly, nonatomic) double cellHeight;
- (_Bool)isValidModel;
- (id)initWithArticleDetail:(id)arg1 backColor:(id)arg2;
- (id)initWithArticleDetail:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

