//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface FinderCategoryContentTabModel : NSObject
{
    long long _typeId;
    NSString *_name;
    long long _page;
    long long _pageSize;
    NSString *_lastTopArticleTime;
    NSString *_lastEndArticleTime;
    NSString *_updatedNum;
    NSMutableArray *_listArray;
    struct CGPoint _moveOffSet;
}

@property(retain, nonatomic) NSMutableArray *listArray; // @synthesize listArray=_listArray;
@property(copy, nonatomic) NSString *updatedNum; // @synthesize updatedNum=_updatedNum;
@property(copy, nonatomic) NSString *lastEndArticleTime; // @synthesize lastEndArticleTime=_lastEndArticleTime;
@property(copy, nonatomic) NSString *lastTopArticleTime; // @synthesize lastTopArticleTime=_lastTopArticleTime;
@property(nonatomic) struct CGPoint moveOffSet; // @synthesize moveOffSet=_moveOffSet;
@property(nonatomic) long long pageSize; // @synthesize pageSize=_pageSize;
@property(nonatomic) long long page; // @synthesize page=_page;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) long long typeId; // @synthesize typeId=_typeId;
- (void).cxx_destruct;
- (void)resetRequestData;
- (void)initLastTime;
- (void)updateListData:(id)arg1;
- (id)initWithTypeId:(long long)arg1 name:(id)arg2;

@end

