//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "HomePageChannelDisplayItem.h"
#import "HomePageChannelInteractiveItem.h"

@class HomePageChannelDiscountItemViewLayoutManager, HomePageChannelProductMarkView, HomePageChannelProductOutOfStockLabel, HomePageChannelProductTagsView, JDImageView, NSString, UIButton, UILabel, UITapGestureRecognizer;

@interface HomePageChannelDiscountItemView : UIView <HomePageChannelDisplayItem, HomePageChannelInteractiveItem>
{
    JDImageView *_imageView;
    HomePageChannelProductMarkView *_markView;
    HomePageChannelProductOutOfStockLabel *_outOfStockLabel;
    UILabel *_operatingPhraseLabel;
    UILabel *_nameLabel;
    HomePageChannelProductTagsView *_tagsView;
    UILabel *_priceLabel;
    UILabel *_referencePriceLabel;
    UIButton *_addToCartButton;
    UIView *_separator;
    HomePageChannelDiscountItemViewLayoutManager *_layoutManager;
    UITapGestureRecognizer *_tapGestureRecognizer;
}

+ (struct CGSize)calculateSizeWithData:(id)arg1 constrainedToSize:(struct CGSize)arg2;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(retain, nonatomic) HomePageChannelDiscountItemViewLayoutManager *layoutManager; // @synthesize layoutManager=_layoutManager;
@property(retain, nonatomic) UIView *separator; // @synthesize separator=_separator;
@property(retain, nonatomic) UIButton *addToCartButton; // @synthesize addToCartButton=_addToCartButton;
@property(retain, nonatomic) UILabel *referencePriceLabel; // @synthesize referencePriceLabel=_referencePriceLabel;
@property(retain, nonatomic) UILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(retain, nonatomic) HomePageChannelProductTagsView *tagsView; // @synthesize tagsView=_tagsView;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UILabel *operatingPhraseLabel; // @synthesize operatingPhraseLabel=_operatingPhraseLabel;
@property(retain, nonatomic) HomePageChannelProductOutOfStockLabel *outOfStockLabel; // @synthesize outOfStockLabel=_outOfStockLabel;
@property(retain, nonatomic) HomePageChannelProductMarkView *markView; // @synthesize markView=_markView;
@property(retain, nonatomic) JDImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)handleActionBlock:(CDUnknownBlockType)arg1 withData:(id)arg2;
- (void)populateWithData:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

