//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class HomePage_FastBuy_StatusView, JDBoxSkuRushModel, JDImageView, UIImageView, UILabel;

@interface Homepage_FastBuy_BoxView : UIView
{
    JDImageView *_backImage;
    UIView *_topImage;
    UILabel *_numLabel;
    UILabel *_remainingTimeLabel;
    UIView *_maskView;
    UILabel *_titleLabel;
    UILabel *_priceLabel;
    HomePage_FastBuy_StatusView *_statusButtonView;
    UIView *_sellOutView;
    UIView *_sellOutCenterView;
    UIImageView *_tomorowPreImageView;
    double _currentTimerInterval;
    JDBoxSkuRushModel *_rushModel;
}

@property(retain, nonatomic) JDBoxSkuRushModel *rushModel; // @synthesize rushModel=_rushModel;
- (id)safeObject:(id)arg1 AtIndex:(long long)arg2;
- (id)processPrice:(id)arg1;
- (id)dateStringFromInterval:(double)arg1;
- (void)updateHeadViewFrame;
- (void)inBuyIng:(double)arg1;
- (void)updateTimeInterval:(double)arg1;
- (void)fillData:(id)arg1;
- (void)buttonPressed:(int)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

