//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSDictionary, UIImageView, UILabel;

@interface HomePageView1 : UIView
{
    UIImageView *_star;
    UIImageView *_redLine;
    UIImageView *_title;
    UILabel *_wareName;
    UILabel *_upText;
    UILabel *_downText;
    UIImageView *_leftCircle;
    UIImageView *_rightCircle;
    UIImageView *_upLine;
    UIImageView *_downLine;
    UIImageView *_phone;
    UIImageView *_clock;
    NSDictionary *_model;
    _Bool stopAnimation;
    long long count;
    id <HomePageView1> _delegate;
}

@property(nonatomic) id <HomePageView1> delegate; // @synthesize delegate=_delegate;
- (void)viewAnimation;
- (void)viewWillAnimation;
- (id)initWithModel:(id)arg1;
- (void)dealloc;

@end

