//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDBoxBaseModel.h"

@class NSNumber, NSString;

@interface JDBoxTagModel : JDBoxBaseModel
{
    NSString *_name;
    NSNumber *_nId;
    NSNumber *_tagType;
    NSString *_tagText;
    NSNumber *_startTime;
    NSNumber *_endTime;
    NSNumber *_isActivatedUser;
    NSString *_activationText;
    NSString *_activationUrl;
    NSNumber *_categoryKind;
}

@property(retain, nonatomic) NSNumber *categoryKind; // @synthesize categoryKind=_categoryKind;
@property(copy, nonatomic) NSString *activationUrl; // @synthesize activationUrl=_activationUrl;
@property(copy, nonatomic) NSString *activationText; // @synthesize activationText=_activationText;
@property(retain, nonatomic) NSNumber *isActivatedUser; // @synthesize isActivatedUser=_isActivatedUser;
@property(retain, nonatomic) NSNumber *endTime; // @synthesize endTime=_endTime;
@property(retain, nonatomic) NSNumber *startTime; // @synthesize startTime=_startTime;
@property(copy, nonatomic) NSString *tagText; // @synthesize tagText=_tagText;
@property(retain, nonatomic) NSNumber *tagType; // @synthesize tagType=_tagType;
@property(copy, nonatomic) NSNumber *nId; // @synthesize nId=_nId;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void)setDataWithDic:(id)arg1;
- (void)dealloc;

@end

