//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel;

@interface JDCategoryUnitView : UIView
{
    UILabel *m_titleLabel;
    UIImageView *m_tipImageView;
    UILabel *m_pointLabel;
    UIImageView *lineImage;
}

@property(retain, nonatomic) UIImageView *lineImage; // @synthesize lineImage;
@property(retain, nonatomic) UILabel *pointLabel; // @synthesize pointLabel=m_pointLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=m_titleLabel;
- (void)setTrendPoint:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

