//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDModel.h"

@class NSString;

@interface JDJPIntAirFlightClassModel : JDModel
{
    NSString *classCode;
    int seats;
    int rowNumber;
}

@property(nonatomic) int rowNumber; // @synthesize rowNumber;
@property(nonatomic) int seats; // @synthesize seats;
@property(retain, nonatomic) NSString *classCode; // @synthesize classCode;
- (void)dealloc;
- (void)setDataWithDic:(id)arg1;
- (id)init;

@end

