//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, UIButton, UIImageView, UILabel;

@interface JDJPDetailBoardersTableViewCell : UITableViewCell
{
    UIButton *deleteButton;
    UILabel *nameLabel;
    UILabel *ticketTypeLabel;
    UILabel *certTypeLabel;
    UILabel *certNoLabel;
    UIImageView *separatorLine;
    NSString *_certNo;
}

@property(retain, nonatomic) NSString *certNo; // @synthesize certNo=_certNo;
@property(retain, nonatomic) UIImageView *separatorLine; // @synthesize separatorLine;
@property(retain, nonatomic) UILabel *ticketTypeLabel; // @synthesize ticketTypeLabel;
@property(retain, nonatomic) UILabel *certNoLabel; // @synthesize certNoLabel;
@property(retain, nonatomic) UILabel *certTypeLabel; // @synthesize certTypeLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel;
- (void)layoutSubviews;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)didFinishInToastView:(id)arg1;
- (void)deleteButtonClicked;

@end

