//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDModel.h"

@class NSArray, NSString;

@interface JDJPIntAirPriceInfoModel : JDModel
{
    NSArray *baggages;
    long long ticketPriceAmount;
    long long supplierPrice;
    long long taxAmount;
    long long platformPrice;
    NSString *passengerType;
    NSString *passengerIdentity;
    NSString *ticketRuleRQ;
    NSString *ticketRuleRes;
    NSString *policyInfo;
    long long _totalPrice;
}

@property(nonatomic) long long totalPrice; // @synthesize totalPrice=_totalPrice;
@property(retain, nonatomic) NSString *policyInfo; // @synthesize policyInfo;
@property(retain, nonatomic) NSString *ticketRuleRes; // @synthesize ticketRuleRes;
@property(retain, nonatomic) NSString *ticketRuleRQ; // @synthesize ticketRuleRQ;
@property(retain, nonatomic) NSString *passengerIdentity; // @synthesize passengerIdentity;
@property(retain, nonatomic) NSString *passengerType; // @synthesize passengerType;
@property(nonatomic) long long platformPrice; // @synthesize platformPrice;
@property(nonatomic) long long taxAmount; // @synthesize taxAmount;
@property(nonatomic) long long supplierPrice; // @synthesize supplierPrice;
@property(nonatomic) long long ticketPriceAmount; // @synthesize ticketPriceAmount;
@property(retain, nonatomic) NSArray *baggages; // @synthesize baggages;
- (void)dealloc;
- (void)setDataWithDic:(id)arg1;
- (id)init;

@end

