//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDViewController.h"

#import "JDBaseToastViewDelegate.h"
#import "UIAlertViewDelegate.h"

@class JDLoginInputView, NSString, ThirdLoginView, UIButton, UIImageView, UIScrollView, UITapGestureRecognizer;

@interface JDLoginViewController : JDViewController <UIAlertViewDelegate, JDBaseToastViewDelegate>
{
    JDLoginInputView *input_;
    UIButton *loginButton_;
    UIButton *registerMobile_;
    UIButton *findPwd_;
    UIScrollView *contentView_;
    _Bool _showCaptchaAlert;
    ThirdLoginView *third_;
    UIImageView *head_;
    UITapGestureRecognizer *tapGesture_;
    _Bool _isLayoutThird;
}

- (void).cxx_destruct;
- (void)didFinishInToastView:(id)arg1;
- (id)persistButtonsForFile:(id)arg1 ofType:(id)arg2;
- (void)cancelLogin;
- (void)resetPasswordAction:(id)arg1;
- (void)registerAction:(id)arg1;
- (void)didFinishLogin:(id)arg1;
- (void)qqLoginAction;
- (void)wechatLoginAction;
- (void)wxLoginResp:(id)arg1;
- (void)loginAction:(id)arg1;
- (void)captchaWillChange;
- (void)captchaException:(id)arg1;
- (void)requestCaptcha:(id)arg1;
- (void)layoutSubviews;
- (void)userLoginNeedCaptcha:(id)arg1;
- (void)layoutThirdLogin;
- (void)hideKeyboard:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)addTapGuesture;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)textFieldChanged:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)willEnterFroeground:(id)arg1;
- (void)removeThird:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

