//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JDMainPageFloorAnimationMTAHelper : NSObject
{
}

+ (void)clickIconViewMTAWithResultState:(long long)arg1 currentGameLevel:(long long)arg2;
+ (void)clickShareGameRecordButtonMTAWithCurrentLevel:(long long)arg1;
+ (void)showGameMTA;
+ (void)clickExitGameButtoMTA:(long long)arg1;
+ (void)clickStartGameButtonNotLogin;
+ (void)clickStartGameButtonMTA:(long long)arg1 startButtonState:(long long)arg2;
+ (void)fetchGameModel:(id)arg1;

@end

