//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDMainPageRecommendItemModel.h"

@class NSArray, NSString;

@interface JDMainPageRecommendShopModel : JDMainPageRecommendItemModel
{
    _Bool _jdShop;
    NSString *_wareId;
    NSString *_wname;
    NSString *_imageurl;
    long long _followCount;
    NSString *_clickUrl;
    NSString *_clk;
    NSArray *_subWareList;
    long long _venderType;
}

@property(nonatomic) _Bool jdShop; // @synthesize jdShop=_jdShop;
@property(nonatomic) long long venderType; // @synthesize venderType=_venderType;
@property(retain, nonatomic) NSArray *subWareList; // @synthesize subWareList=_subWareList;
@property(copy, nonatomic) NSString *clk; // @synthesize clk=_clk;
@property(copy, nonatomic) NSString *clickUrl; // @synthesize clickUrl=_clickUrl;
@property(nonatomic) long long followCount; // @synthesize followCount=_followCount;
@property(copy, nonatomic) NSString *imageurl; // @synthesize imageurl=_imageurl;
@property(copy, nonatomic) NSString *wname; // @synthesize wname=_wname;
@property(copy, nonatomic) NSString *wareId; // @synthesize wareId=_wareId;
- (void).cxx_destruct;
- (id)params;
- (id)des;
- (id)mta_eventId;

@end

