//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@class UIImageView;

@interface JDMainPageDecorateLabelStyle02 : UILabel
{
    UIImageView *_leftTag;
    UIImageView *_rightTag;
}

- (void).cxx_destruct;
- (id)getTag:(long long)arg1;
- (void)setText:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

