//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class JDImageView, NSDictionary, UIButton, UIImageView, UILabel, UIView;

@interface JDMCouponCell : UITableViewCell
{
    JDImageView *haibaoPhoto;
    UILabel *cinemaName;
    UILabel *validateTime;
    UILabel *typeLabel;
    UILabel *ticketPrice;
    UIView *headView;
    UIView *middleView;
    UIView *bottomView;
    UIButton *stateButton_;
    UIImageView *finishLogo;
    UILabel *m_orderIdLab;
    UILabel *m_orderDetailLab;
    UILabel *m_orderPayLab;
    UILabel *m_orderTimeLab;
    long long m_orderState;
    UILabel *m_orderStateLab;
    NSDictionary *m_dataDic;
}

@property(retain, nonatomic) NSDictionary *m_dataDic; // @synthesize m_dataDic;
@property(retain, nonatomic) UILabel *m_orderStateLab; // @synthesize m_orderStateLab;
@property(nonatomic) long long m_orderState; // @synthesize m_orderState;
@property(retain, nonatomic) UILabel *m_orderTimeLab; // @synthesize m_orderTimeLab;
@property(retain, nonatomic) UILabel *m_orderPayLab; // @synthesize m_orderPayLab;
@property(retain, nonatomic) UILabel *m_orderDetailLab; // @synthesize m_orderDetailLab;
@property(retain, nonatomic) UILabel *m_orderIdLab; // @synthesize m_orderIdLab;
- (void)dealloc;
- (void)gotoPayViewcontorller:(id)arg1;
- (void)gotoPay:(id)arg1;
- (id)getAttributString:(id)arg1;
- (void)setData:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (void)prepareForReuse;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

