//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextFieldDelegate.h"

@class NSString, UITextField;

@interface JDMTicketSelectQuantityView : UIView <UITextFieldDelegate>
{
    id <JDMTicketSelectQuantityViewDelegate> _delegate;
    long long _maxNum;
    UITextField *_quantityTextField;
}

@property(retain, nonatomic) UITextField *quantityTextField; // @synthesize quantityTextField=_quantityTextField;
@property(nonatomic) long long maxNum; // @synthesize maxNum=_maxNum;
@property(nonatomic) __weak id <JDMTicketSelectQuantityViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)keybordConfim;
- (void)keybordCancel;
- (void)notKeyboardCancel:(id)arg1;
- (void)notKeyboardConfim:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)plusButtonClicked:(id)arg1;
- (void)minusButtonClicked:(id)arg1;
- (void)hideKeyboard;
- (void)configUI;
- (void)setQuantity:(int)arg1;
- (id)getQuantity;
- (void)showToastWithMsg:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

