//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBModel.h"

@interface JDPAccountInfoModel : CBModel
{
    _Bool _hasMobilePwd;
    _Bool _hasPcPwd;
    _Bool _hasFingerprint;
}

@property(nonatomic) _Bool hasFingerprint; // @synthesize hasFingerprint=_hasFingerprint;
@property(nonatomic) _Bool hasPcPwd; // @synthesize hasPcPwd=_hasPcPwd;
@property(nonatomic) _Bool hasMobilePwd; // @synthesize hasMobilePwd=_hasMobilePwd;

@end

