//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBPaymentBaseDataHandler.h"

#import "JDPBindCardProtocal.h"

@class NSString;

@interface JDPBindCardDataHandler : CBPaymentBaseDataHandler <JDPBindCardProtocal>
{
}

- (id)bindCardInfoModelFromDict:(id)arg1;
- (id)private_dictWithBankCardInfoModel:(id)arg1;
- (id)bindCardWithParamModel:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

