//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CBPaymentPayBaseViewController.h"

@class UIButton, UIImageView, UILabel, UIScrollView;

@interface JDPPaymentRealNameViewController : CBPaymentPayBaseViewController
{
    UIScrollView *_fillScrollView;
    UIImageView *_successImageView;
    UILabel *_successLabel;
    UILabel *_realNameLabel;
    UIButton *_successButton;
    UIImageView *_realNameBottomImageView;
}

@property(retain, nonatomic) UIImageView *realNameBottomImageView; // @synthesize realNameBottomImageView=_realNameBottomImageView;
@property(retain, nonatomic) UIButton *successButton; // @synthesize successButton=_successButton;
@property(retain, nonatomic) UILabel *realNameLabel; // @synthesize realNameLabel=_realNameLabel;
@property(retain, nonatomic) UILabel *successLabel; // @synthesize successLabel=_successLabel;
@property(retain, nonatomic) UIImageView *successImageView; // @synthesize successImageView=_successImageView;
@property(retain, nonatomic) UIScrollView *fillScrollView; // @synthesize fillScrollView=_fillScrollView;
- (void).cxx_destruct;
- (void)cb_successButtonAction:(id)arg1;
- (void)closeButtonAction:(id)arg1;
- (void)cb_createSuccessButton;
- (void)cb_createRealImageView;
- (void)cb_realNameBottomLabel;
- (void)cb_createRealNameLabel;
- (void)cb_createSuccessLabel;
- (void)cb_createSuccessImageView;
- (void)cb_createScrollView;
- (void)cb_createCloseButton;
- (void)cb_clearNavLeftButton;
- (void)cb_setupSelf;
- (void)viewDidLoad;
- (void)navBarLeftButtonAction:(id)arg1;

@end

