//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface JDSHHdxCellFiveViewModel : NSObject
{
    _Bool _hasLiked;
    NSString *_contentImgUrl;
    NSString *_title;
    NSString *_authorPic;
    NSString *_authorName;
    NSString *_desc;
    NSString *_price;
    long long _count;
    NSString *_idStr;
    NSString *_sku;
    NSString *_authorId;
    NSString *_ztTitle;
    NSString *_pin;
    NSString *_unionId;
}

@property(copy, nonatomic) NSString *unionId; // @synthesize unionId=_unionId;
@property(copy, nonatomic) NSString *pin; // @synthesize pin=_pin;
@property(copy, nonatomic) NSString *ztTitle; // @synthesize ztTitle=_ztTitle;
@property(copy, nonatomic) NSString *authorId; // @synthesize authorId=_authorId;
@property(copy, nonatomic) NSString *sku; // @synthesize sku=_sku;
@property(copy, nonatomic) NSString *idStr; // @synthesize idStr=_idStr;
@property(nonatomic) long long count; // @synthesize count=_count;
@property(nonatomic) _Bool hasLiked; // @synthesize hasLiked=_hasLiked;
@property(copy, nonatomic) NSString *price; // @synthesize price=_price;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(copy, nonatomic) NSString *authorName; // @synthesize authorName=_authorName;
@property(copy, nonatomic) NSString *authorPic; // @synthesize authorPic=_authorPic;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *contentImgUrl; // @synthesize contentImgUrl=_contentImgUrl;
- (void).cxx_destruct;
- (id)initWithImgHost:(id)arg1 authorId:(id)arg2 authorName:(id)arg3 authorPic:(id)arg4 goodsPic:(id)arg5 hasLike:(_Bool)arg6 idStr:(id)arg7 likeNum:(long long)arg8 desc:(id)arg9 title:(id)arg10 sku:(id)arg11 goodRate:(id)arg12 skuPrice:(id)arg13 ztTitle:(id)arg14 pin:(id)arg15 unionId:(id)arg16;

@end

