//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class JDStowShopProductModel, UIImageView, UILabel, UIView;

@interface JDShopDynamicModeTwoCell : UICollectionViewCell
{
    UIImageView *imageView;
    UILabel *priceLabel;
    UILabel *introLabel;
    UIView *statusView;
    UILabel *statusLabel;
    JDStowShopProductModel *_productModel;
}

@property(retain, nonatomic) JDStowShopProductModel *productModel; // @synthesize productModel=_productModel;
- (void).cxx_destruct;
- (id)formatePriceString:(id)arg1;
- (void)setStatusView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

