//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class JDSHCalendarDayViewModel, UIImageView, UILabel;

@interface JDSHCalendarDayView : UIView
{
    JDSHCalendarDayViewModel *_dayViewModel;
    UILabel *_weekLable;
    UILabel *_dayLabel;
    UILabel *_lunarLabel;
    UILabel *_redDotLabel;
    UIImageView *_redDotView;
    UIImageView *_triangleImageView;
}

@property(retain, nonatomic) UIImageView *triangleImageView; // @synthesize triangleImageView=_triangleImageView;
@property(retain, nonatomic) UIImageView *redDotView; // @synthesize redDotView=_redDotView;
@property(retain, nonatomic) UILabel *redDotLabel; // @synthesize redDotLabel=_redDotLabel;
@property(retain, nonatomic) UILabel *lunarLabel; // @synthesize lunarLabel=_lunarLabel;
@property(retain, nonatomic) UILabel *dayLabel; // @synthesize dayLabel=_dayLabel;
@property(retain, nonatomic) UILabel *weekLable; // @synthesize weekLable=_weekLable;
@property(retain, nonatomic) JDSHCalendarDayViewModel *dayViewModel; // @synthesize dayViewModel=_dayViewModel;
- (void).cxx_destruct;
- (void)configView;
- (id)initWithCalendarDayViewModel:(id)arg1 Frame:(struct CGRect)arg2;

@end

