//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDModel.h"

@class NSNumber, NSString;

@interface JDShippingAddressModel : JDModel
{
    NSString *_name;
    NSString *_pin;
    NSString *_mobile;
    NSString *_phone;
    NSString *_identityCardNumber;
    _Bool _defaultAddressFlag;
    _Bool _needTownIDFlag;
    _Bool _townErrorFlag;
    double _latitude;
    double _longitude;
    unsigned long long _addressType;
    unsigned long long _coordinateType;
    NSNumber *_ID;
    NSNumber *_provinceID;
    NSNumber *_cityID;
    NSNumber *_countyID;
    NSNumber *_townID;
    NSString *_province;
    NSString *_city;
    NSString *_county;
    NSString *_town;
    NSString *_street;
    NSString *_fullAddress;
    NSString *_postalCode;
    NSString *_needTownMessage;
    NSString *_areaExplainMsg;
    NSString *_areaExplainUrl;
}

+ (id)replacedKeyFromPropertyName;
+ (id)shippingAddressModelWithData:(id)arg1;
@property(copy, nonatomic) NSString *areaExplainUrl; // @synthesize areaExplainUrl=_areaExplainUrl;
@property(copy, nonatomic) NSString *areaExplainMsg; // @synthesize areaExplainMsg=_areaExplainMsg;
@property(nonatomic) _Bool townErrorFlag; // @synthesize townErrorFlag=_townErrorFlag;
@property(copy, nonatomic) NSString *needTownMessage; // @synthesize needTownMessage=_needTownMessage;
@property(nonatomic) _Bool needTownIDFlag; // @synthesize needTownIDFlag=_needTownIDFlag;
@property(copy, nonatomic) NSString *postalCode; // @synthesize postalCode=_postalCode;
@property(copy, nonatomic) NSString *fullAddress; // @synthesize fullAddress=_fullAddress;
@property(copy, nonatomic) NSString *street; // @synthesize street=_street;
@property(copy, nonatomic) NSString *town; // @synthesize town=_town;
@property(copy, nonatomic) NSString *county; // @synthesize county=_county;
@property(copy, nonatomic) NSString *city; // @synthesize city=_city;
@property(copy, nonatomic) NSString *province; // @synthesize province=_province;
@property(retain, nonatomic) NSNumber *townID; // @synthesize townID=_townID;
@property(retain, nonatomic) NSNumber *countyID; // @synthesize countyID=_countyID;
@property(retain, nonatomic) NSNumber *cityID; // @synthesize cityID=_cityID;
@property(retain, nonatomic) NSNumber *provinceID; // @synthesize provinceID=_provinceID;
@property(retain, nonatomic) NSNumber *ID; // @synthesize ID=_ID;
@property(nonatomic) unsigned long long coordinateType; // @synthesize coordinateType=_coordinateType;
@property(nonatomic) unsigned long long addressType; // @synthesize addressType=_addressType;
@property(nonatomic) double longitude; // @synthesize longitude=_longitude;
@property(nonatomic) double latitude; // @synthesize latitude=_latitude;
@property(nonatomic) _Bool defaultAddressFlag; // @synthesize defaultAddressFlag=_defaultAddressFlag;
- (void).cxx_destruct;
- (_Bool)isLiteralEqual:(id)arg1;
- (_Bool)isIDEqual:(id)arg1;
- (_Bool)isEqual:(id)arg1;
@property(copy, nonatomic) NSString *identityCardNumber; // @dynamic identityCardNumber;
@property(copy, nonatomic) NSString *phone; // @dynamic phone;
@property(copy, nonatomic) NSString *mobile; // @dynamic mobile;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(readonly, copy, nonatomic) NSString *pin; // @dynamic pin;
- (id)generateRequestParams;

@end

