//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JDVDanmuNetwork, NSError, NSString;

@protocol JDVDanmuNetworkDelegate <NSObject>
- (void)network:(JDVDanmuNetwork *)arg1 didReceiveMsgString:(NSString *)arg2 Content:(id)arg3;
- (void)network:(JDVDanmuNetwork *)arg1 closedWithAddress:(NSString *)arg2 Error:(NSError *)arg3 Retrying:(_Bool)arg4;
- (void)network:(JDVDanmuNetwork *)arg1 openedWithAddress:(NSString *)arg2;
@end

