//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JIMIBaseCell.h"

@class JIMIProductPromotModel, UIButton, UILabel, UINetImageView, UIView;

@interface JIMIProductsCell : JIMIBaseCell
{
    JIMIProductPromotModel *_productsModel;
    UIView *_bg;
    UINetImageView *_productImageView;
    UILabel *_productInfoLable;
    UILabel *_priceDetailLable;
    UIButton *_sendButton;
    UIView *_toolView;
}

+ (float)getCellHeight:(id)arg1;
@property(retain, nonatomic) UIView *toolView; // @synthesize toolView=_toolView;
@property(retain, nonatomic) UIButton *sendButton; // @synthesize sendButton=_sendButton;
@property(retain, nonatomic) UILabel *priceDetailLable; // @synthesize priceDetailLable=_priceDetailLable;
@property(retain, nonatomic) UILabel *productInfoLable; // @synthesize productInfoLable=_productInfoLable;
@property(retain, nonatomic) UINetImageView *productImageView; // @synthesize productImageView=_productImageView;
@property(retain, nonatomic) UIView *bg; // @synthesize bg=_bg;
@property(retain, nonatomic) JIMIProductPromotModel *productsModel; // @synthesize productsModel=_productsModel;
- (void).cxx_destruct;
- (void)switchProductInfo:(id)arg1;
- (void)jump2ProductInfo:(id)arg1;
- (void)initUI;
- (void)prepareForReuse;
- (void)setModelInfo:(id)arg1 parentVC:(id)arg2;

@end

