//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDModel.h"

@class NSString;

@interface KeyValueModel : JDModel
{
    NSString *Label;
    NSString *Value;
    NSString *Operator;
}

@property(retain, nonatomic) NSString *Operator; // @synthesize Operator;
@property(retain, nonatomic) NSString *Value; // @synthesize Value;
@property(retain, nonatomic) NSString *Label; // @synthesize Label;
- (void)dealloc;
- (void)setDataWithDic:(id)arg1;

@end

