//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LCRequestItem, NSDictionary, NSMutableArray, NSString;

@interface LCResponseItem : NSObject
{
    int _code;
    LCRequestItem *_requestItem;
    NSString *_jsonString;
    NSDictionary *_responseDict;
    NSString *_errorInfo;
    NSString *_messageTips;
    NSString *_errorCode;
    long long _returnState;
    NSMutableArray *_responseDataArray;
}

@property(retain, nonatomic) NSMutableArray *responseDataArray; // @synthesize responseDataArray=_responseDataArray;
@property(nonatomic) long long returnState; // @synthesize returnState=_returnState;
@property(nonatomic) int code; // @synthesize code=_code;
@property(retain, nonatomic) NSString *errorCode; // @synthesize errorCode=_errorCode;
@property(retain, nonatomic) NSString *messageTips; // @synthesize messageTips=_messageTips;
@property(retain, nonatomic) NSString *errorInfo; // @synthesize errorInfo=_errorInfo;
@property(retain, nonatomic) NSDictionary *responseDict; // @synthesize responseDict=_responseDict;
@property(retain, nonatomic) NSString *jsonString; // @synthesize jsonString=_jsonString;
@property(retain, nonatomic) LCRequestItem *requestItem; // @synthesize requestItem=_requestItem;
- (void).cxx_destruct;
- (id)init;

@end

