//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSTimer, OrderDetailBottomButton, UILabel;

@interface OrderDetailBottomView : UIView
{
    _Bool noButton;
    _Bool onlyCancelButton;
    _Bool hasRemainTimer;
    long long _buttonsNum;
    OrderDetailBottomButton *_button1;
    OrderDetailBottomButton *_button2;
    OrderDetailBottomButton *_button3;
    OrderDetailBottomButton *_button4;
    UILabel *_remainTextLabel;
    int m;
    int _seconds;
    id <OrderDetailBottomButtonDelegate><OrderDetailBottomViewDelegate> delegate;
    UILabel *_remainTimeLabel;
    NSTimer *_orderTimer;
}

@property(retain, nonatomic) NSTimer *orderTimer; // @synthesize orderTimer=_orderTimer;
@property(nonatomic) int seconds; // @synthesize seconds=_seconds;
@property(retain, nonatomic) UILabel *remainTimeLabel; // @synthesize remainTimeLabel=_remainTimeLabel;
@property(nonatomic) _Bool onlyCancelButton; // @synthesize onlyCancelButton;
@property(nonatomic) _Bool noButton; // @synthesize noButton;
@property(nonatomic) id <OrderDetailBottomButtonDelegate><OrderDetailBottomViewDelegate> delegate; // @synthesize delegate;
- (void)timeInvalide;
- (id)setAttributedString:(id)arg1;
- (void)setTimeLabel:(int)arg1 timer:(id)arg2;
- (void)timeFire:(id)arg1;
- (void)startCountTime;
- (void)hideAllButtons;
- (id)getNoUsedButton;
- (void)setupBottomView:(id)arg1;
- (void)creatButtons;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

