//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIBarButtonItem.h"

@class OrderOftenBuyCartView;

@interface OrderOftenBuyCartBarButtonItem : UIBarButtonItem
{
    OrderOftenBuyCartView *_cartView;
    id <OOBItemDelegate> _delegate;
}

+ (id)cartView;
+ (id)orderOftenBuyCartBarButtonItem;
@property(nonatomic) __weak id <OOBItemDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) OrderOftenBuyCartView *cartView; // @synthesize cartView=_cartView;
- (void).cxx_destruct;
- (void)goCart;
- (void)updateCartViewNmuber:(id)arg1;

@end

