//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "DetailBgContentItem.h"

@interface PDDeliveryInstallView : DetailBgContentItem
{
}

- (id)deliveryInstallIconWithFrame:(struct CGRect)arg1 Title:(id)arg2;
- (void)loadDeliveryInstall:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

