//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RCTViewManager.h"

@interface RCTNavItemManager : RCTViewManager
{
}

+ (id)propConfig_onRightButtonPress;
+ (id)propConfig_onLeftButtonPress;
+ (id)propConfig_rightButtonTitle;
+ (id)propConfig_rightButtonIcon;
+ (id)propConfig_leftButtonIcon;
+ (id)propConfig_leftButtonTitle;
+ (id)propConfig_backButtonTitle;
+ (id)propConfig_backButtonIcon;
+ (id)propConfig_titleTextColor;
+ (id)propConfig_title;
+ (id)propConfig_translucent;
+ (id)propConfig_barTintColor;
+ (id)propConfig_tintColor;
+ (id)propConfig_shadowHidden;
+ (id)propConfig_navigationBarHidden;
+ (void)load;
+ (id)moduleName;
- (id)view;

@end

