//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel;

@interface RefundProgressHeaderView : UIView
{
    UILabel *_orderId;
    UILabel *_orderReason;
    UILabel *_orderProgress;
    UILabel *_totalMoney;
    UILabel *_tipLabel;
    UIImageView *_warningView;
    UIView *_bottomView;
}

@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIImageView *warningView; // @synthesize warningView=_warningView;
@property(retain, nonatomic) UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
@property(retain, nonatomic) UILabel *totalMoney; // @synthesize totalMoney=_totalMoney;
@property(retain, nonatomic) UILabel *orderProgress; // @synthesize orderProgress=_orderProgress;
@property(retain, nonatomic) UILabel *orderReason; // @synthesize orderReason=_orderReason;
@property(retain, nonatomic) UILabel *orderId; // @synthesize orderId=_orderId;
- (void).cxx_destruct;
- (void)configSpliter;
- (id)createAndAddSpliter;
- (void)updateHeight:(double)arg1 orderReasonH:(double)arg2 orderProgressH:(double)arg3 totalMoneyH:(double)arg4 tipHeight:(double)arg5;
- (void)addInitConstraints;
- (void)orderIdLongGesture:(id)arg1;
- (id)stringFromArray:(id)arg1;
- (id)style;
- (id)toAttributeString:(id)arg1 specialHex:(id)arg2 normalHex:(id)arg3;
- (double)getHeightWithLabel:(id)arg1 width:(double)arg2;
- (double)configTextForLabelsWith:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

