//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIColor, UIImage;

@interface SearchTagView : UIView
{
    UIColor *_tLabelColor;
    UIColor *_tBackgroundColor;
    UIColor *_tCloseButtonColor;
    UIImage *_tImage;
    NSString *_tTitle;
    CDUnknownBlockType _searchTagViewDidRemove;
}

@property(copy, nonatomic) CDUnknownBlockType searchTagViewDidRemove; // @synthesize searchTagViewDidRemove=_searchTagViewDidRemove;
@property(copy, nonatomic) NSString *tTitle; // @synthesize tTitle=_tTitle;
@property(retain, nonatomic) UIImage *tImage; // @synthesize tImage=_tImage;
@property(retain, nonatomic) UIColor *tCloseButtonColor; // @synthesize tCloseButtonColor=_tCloseButtonColor;
@property(retain, nonatomic) UIColor *tBackgroundColor; // @synthesize tBackgroundColor=_tBackgroundColor;
@property(retain, nonatomic) UIColor *tLabelColor; // @synthesize tLabelColor=_tLabelColor;
- (void).cxx_destruct;
- (void)tagClose:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (struct CGSize)getTagSize;
- (id)initWithFrame:(struct CGRect)arg1;

@end

