//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDModel.h"

@class NSString;

@interface SetupUrlModel : JDModel
{
    NSString *_setupServerUrl;
    NSString *_setupMessageUrl;
    NSString *_setupPhotoBuyUrl;
    NSString *_setupColorBuyUrl;
    NSString *_setupMServerUrl;
    NSString *_setupCCServerUrl;
    NSString *_setupOrderUrl;
    NSString *_setupCartUrl;
    NSString *_setupWareUrl;
    NSString *_setupSearchUrl;
    NSString *_setupPayUrl;
    NSString *_setupPrePayUrl;
    NSString *_setupVirtualUrl;
    NSString *_setupVirtualJPUrl;
    NSString *_setupMy360BuyUrl;
    NSString *_setupStoryUrl;
    NSString *_setupCommuneUrl;
    NSString *_setupName;
    NSString *_promotionServerUrl;
    NSString *_activityServerUrl;
    NSString *_categoryServerUrl;
    NSString *_hotkeySearchBoxServerUrl;
    NSString *_setupNewServerURL;
}

@property(retain, nonatomic) NSString *setupNewServerURL; // @synthesize setupNewServerURL=_setupNewServerURL;
@property(retain, nonatomic) NSString *hotkeySearchBoxServerUrl; // @synthesize hotkeySearchBoxServerUrl=_hotkeySearchBoxServerUrl;
@property(retain, nonatomic) NSString *categoryServerUrl; // @synthesize categoryServerUrl=_categoryServerUrl;
@property(retain, nonatomic) NSString *activityServerUrl; // @synthesize activityServerUrl=_activityServerUrl;
@property(retain, nonatomic) NSString *promotionServerUrl; // @synthesize promotionServerUrl=_promotionServerUrl;
@property(retain, nonatomic) NSString *setupName; // @synthesize setupName=_setupName;
@property(retain, nonatomic) NSString *setupCommuneUrl; // @synthesize setupCommuneUrl=_setupCommuneUrl;
@property(retain, nonatomic) NSString *setupStoryUrl; // @synthesize setupStoryUrl=_setupStoryUrl;
@property(retain, nonatomic) NSString *setupMy360BuyUrl; // @synthesize setupMy360BuyUrl=_setupMy360BuyUrl;
@property(retain, nonatomic) NSString *setupVirtualJPUrl; // @synthesize setupVirtualJPUrl=_setupVirtualJPUrl;
@property(retain, nonatomic) NSString *setupVirtualUrl; // @synthesize setupVirtualUrl=_setupVirtualUrl;
@property(retain, nonatomic) NSString *setupPrePayUrl; // @synthesize setupPrePayUrl=_setupPrePayUrl;
@property(retain, nonatomic) NSString *setupPayUrl; // @synthesize setupPayUrl=_setupPayUrl;
@property(retain, nonatomic) NSString *setupSearchUrl; // @synthesize setupSearchUrl=_setupSearchUrl;
@property(retain, nonatomic) NSString *setupWareUrl; // @synthesize setupWareUrl=_setupWareUrl;
@property(retain, nonatomic) NSString *setupCartUrl; // @synthesize setupCartUrl=_setupCartUrl;
@property(retain, nonatomic) NSString *setupOrderUrl; // @synthesize setupOrderUrl=_setupOrderUrl;
@property(retain, nonatomic) NSString *setupCCServerUrl; // @synthesize setupCCServerUrl=_setupCCServerUrl;
@property(retain, nonatomic) NSString *setupMServerUrl; // @synthesize setupMServerUrl=_setupMServerUrl;
@property(retain, nonatomic) NSString *setupColorBuyUrl; // @synthesize setupColorBuyUrl=_setupColorBuyUrl;
@property(retain, nonatomic) NSString *setupPhotoBuyUrl; // @synthesize setupPhotoBuyUrl=_setupPhotoBuyUrl;
@property(retain, nonatomic) NSString *setupMessageUrl; // @synthesize setupMessageUrl=_setupMessageUrl;
@property(retain, nonatomic) NSString *setupServerUrl; // @synthesize setupServerUrl=_setupServerUrl;
- (void)dealloc;

@end

