//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

#import "UIGestureRecognizerDelegate.h"
#import "UITextViewDelegate.h"

@class CommentWareInfoModel, JDImageView, NSString, RateView, ShareOrderTextView, UIButton, UILabel, UIView;

@interface ShareOrderHeaderView : UICollectionReusableView <UIGestureRecognizerDelegate, UITextViewDelegate>
{
    double touchWindowHeight;
    double touchViewHeight;
    double scrollHeight;
    double changHeight;
    UIButton *giftButton;
    JDImageView *goImageView;
    int jingBeanWordCount;
    id <ShareOrderHeaderViewDelegate> _delegate;
    CommentWareInfoModel *_wareModel;
    long long _textEditType;
    RateView *_rateScoreView;
    ShareOrderTextView *_textView;
    UIView *_storyView;
    UIView *_wareDetailView;
    UIView *_commentView;
    UILabel *_leftLabel;
    UILabel *_label;
    struct _NSRange _lastRange;
}

+ (double)getHeaderHeight:(id)arg1;
@property(nonatomic) struct _NSRange lastRange; // @synthesize lastRange=_lastRange;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UILabel *leftLabel; // @synthesize leftLabel=_leftLabel;
@property(retain, nonatomic) UIView *commentView; // @synthesize commentView=_commentView;
@property(retain, nonatomic) UIView *wareDetailView; // @synthesize wareDetailView=_wareDetailView;
@property(retain, nonatomic) UIView *storyView; // @synthesize storyView=_storyView;
@property(retain, nonatomic) ShareOrderTextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) RateView *rateScoreView; // @synthesize rateScoreView=_rateScoreView;
@property(nonatomic) long long textEditType; // @synthesize textEditType=_textEditType;
@property(retain, nonatomic) CommentWareInfoModel *wareModel; // @synthesize wareModel=_wareModel;
@property(nonatomic) __weak id <ShareOrderHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)viewDidTaped:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)fitCommentView;
- (_Bool)resignFirstResponder;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)hideKeyboard;
- (void)convertShieldList:(id)arg1 imageShieldList:(id)arg2;
- (void)textChanged:(long long)arg1;
- (void)showGuideView;
- (void)setData:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

