//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDViewController.h"

#import "CategoryPromotionViewDelegate.h"
#import "JDStatusViewDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class CJDButton, CategoryFooterView, CategoryPromotionService, CategoryPromotionView, CategorySecondService, CategorySubListFlowLayout, NSMutableArray, NSString, UICollectionView;

@interface SHCategorySubListViewController : JDViewController <UICollectionViewDelegate, UICollectionViewDataSource, JDStatusViewDelegate, CategoryPromotionViewDelegate>
{
    CategorySecondService *_service;
    CategoryPromotionService *_promotionService;
    CJDButton *_returnTopButton;
    CategoryFooterView *_footerView;
    CategoryPromotionView *promotionHeader_;
    _Bool _isMerge;
    _Bool _lastMerge;
    _Bool _isLoadingState;
    _Bool _canPullRefresh;
    int _categoryId;
    int _indexMerge;
    id <SHCategorySubListViewControllerDelegate> _delegate;
    NSString *_nextTitle;
    UICollectionView *_collectionView;
    NSMutableArray *_categorySubListArray;
    CategorySubListFlowLayout *_flowLayout;
}

@property(nonatomic) _Bool canPullRefresh; // @synthesize canPullRefresh=_canPullRefresh;
@property(retain, nonatomic) CategorySubListFlowLayout *flowLayout; // @synthesize flowLayout=_flowLayout;
@property(retain, nonatomic) NSMutableArray *categorySubListArray; // @synthesize categorySubListArray=_categorySubListArray;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) _Bool isLoadingState; // @synthesize isLoadingState=_isLoadingState;
@property(copy, nonatomic) NSString *nextTitle; // @synthesize nextTitle=_nextTitle;
@property(nonatomic) int indexMerge; // @synthesize indexMerge=_indexMerge;
@property(nonatomic) _Bool lastMerge; // @synthesize lastMerge=_lastMerge;
@property(nonatomic) _Bool isMerge; // @synthesize isMerge=_isMerge;
@property(nonatomic) int categoryId; // @synthesize categoryId=_categoryId;
@property(nonatomic) __weak id <SHCategorySubListViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)reloadDataListWhenLoadFail;
- (void)removeNonetView;
- (void)JDStatusView:(id)arg1 didClickButton:(id)arg2;
- (void)categoryReloadView;
- (void)jumpNextTab;
- (void)setupBackTop;
- (void)categoryPromotionViewDidClickWithBannerSource:(id)arg1 categoryPromotionItem:(id)arg2 index:(long long)arg3;
- (void)showPromotionViewWithModel:(id)arg1;
- (void)cancelPromotionRequest;
- (void)showPromotionHeader;
- (void)hidePromotionHeader;
- (void)loadPromotion;
- (void)didFinishInToastView:(id)arg1;
- (void)didCancelInToastView:(id)arg1;
- (void)clearMostUseCategory;
- (void)clearMostUseCategoryData;
- (void)reloadCollectionView:(id)arg1 isLoadSuccess:(_Bool)arg2;
- (void)loadNewMostUseCategoryListData;
- (void)loadNewMostUseCategoryData;
- (void)loadCategoryData;
- (void)gotoCategoryRankingWithIndexPath:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)reconnect;
- (void)reloadData;
- (void)setupFootUI;
- (void)initDate;
- (void)createUI;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

