//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSError, NSMutableArray, NSString, SHVPDanmuSDK;

@protocol SHVPDanmuSDKDelegate <NSObject>
- (void)sdk:(SHVPDanmuSDK *)arg1 liveBroadCastEndAtTime:(double)arg2;
- (void)sdk:(SHVPDanmuSDK *)arg1 ProductList:(NSMutableArray *)arg2;
- (void)sdk:(SHVPDanmuSDK *)arg1 AnchorResumeLiveWithNickName:(NSString *)arg2;
- (void)sdk:(SHVPDanmuSDK *)arg1 AnchorSuspendLiveWithNickName:(NSString *)arg2;
- (void)sdk:(SHVPDanmuSDK *)arg1 ShopcartMessage:(NSString *)arg2 Nickname:(NSString *)arg3;
- (void)sdk:(SHVPDanmuSDK *)arg1 AnchorMessage:(NSString *)arg2 Nickname:(NSString *)arg3;
- (void)sdk:(SHVPDanmuSDK *)arg1 UserMessage:(NSString *)arg2 Nickname:(NSString *)arg3;
- (void)sdk:(SHVPDanmuSDK *)arg1 HeadPicArray:(NSArray *)arg2;
- (void)sdk:(SHVPDanmuSDK *)arg1 TotalCartNum:(int)arg2;
- (void)sdk:(SHVPDanmuSDK *)arg1 TotalThumbUpNum:(int)arg2;
- (void)sdk:(SHVPDanmuSDK *)arg1 TotalViewerNum:(int)arg2;
- (void)sdk:(SHVPDanmuSDK *)arg1 LeaveLiveBroadcastWithNickName:(NSString *)arg2;
- (void)sdk:(SHVPDanmuSDK *)arg1 JoinLiveBroadcastWithNickName:(NSString *)arg2;
- (void)sdk:(SHVPDanmuSDK *)arg1 ClosedWithAddress:(NSString *)arg2 Error:(NSError *)arg3 Retrying:(_Bool)arg4;
@end

