//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SHVPCalenderHelp : NSObject
{
}

+ (void)cancelRemindLiveId:(id)arg1 jumpUrl:(id)arg2 isMiaoSha:(_Bool)arg3 title:(id)arg4 publishTime:(id)arg5 finish:(CDUnknownBlockType)arg6;
+ (void)setRemindLiveId:(id)arg1 jumpUrl:(id)arg2 isMiaoSha:(_Bool)arg3 title:(id)arg4 publishTime:(id)arg5 finish:(CDUnknownBlockType)arg6;
+ (_Bool)hasSetRemind:(id)arg1 isMiaoSha:(_Bool)arg2;

@end

