//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPDYSettingsObj : NSObject
{
    CDStruct_2ea23212 _settings[9];
}

@property(readonly, nonatomic) CDStruct_2ea23212 *settings;
- (id)init;

@end

