//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface SPHGLProgram : NSObject
{
    NSMutableArray *attributes;
    NSMutableArray *uniforms;
    unsigned int vertShader;
    unsigned int fragShader;
    unsigned int _program;
}

@property(nonatomic) unsigned int program; // @synthesize program=_program;
- (void).cxx_destruct;
- (void)dealloc;
- (void)validate;
- (id)programLog;
- (id)fragmentShaderLog;
- (id)vertexShaderLog;
- (id)logForOpenGLObject:(unsigned int)arg1 infoCallback:(CDUnknownFunctionPointerType)arg2 logFunc:(CDUnknownFunctionPointerType)arg3;
- (void)use;
- (_Bool)link;
- (unsigned int)uniformIndex:(id)arg1;
- (unsigned int)attributeIndex:(id)arg1;
- (void)addAttribute:(id)arg1;
- (_Bool)compileShader:(unsigned int *)arg1 type:(unsigned int)arg2 string:(id)arg3;
- (id)initWithVertexShaderFilename:(id)arg1 fragmentShaderFilename:(id)arg2;

@end

