//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SSSNetwork : NSObject
{
}

+ (id)sssCategoryId:(id)arg1;
+ (id)sssCategoryRequestSetupModel;
+ (id)sssReceiveAwardActivityId:(id)arg1 moduleId:(id)arg2;
+ (id)sssAwardActivityId:(id)arg1 moduleId:(id)arg2;
+ (id)ssGroupBuyLandingNetwortModelBrandId:(id)arg1;
+ (id)ssGroupBuyNetwortModel;
+ (void)p_SendRequest:(id)arg1 finish:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (void)sssCategoryLandingNetworkWithCategoryId:(id)arg1 Finish:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (void)sssCategoryItemsNetwork:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
+ (void)sssGroupBuyingLangingReceiveAwardActivityId:(id)arg1 moduleId:(id)arg2 Finish:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
+ (void)sssGroupBuyingLangingAwardNetworkActivityId:(id)arg1 moduleId:(id)arg2 Finish:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
+ (void)sssGroupBuyingLangingNetworkWithBrandId:(id)arg1 Finish:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (void)sssGroupBuyingNetworkFinish:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
+ (void)sssRequest:(id)arg1 didFinish:(CDUnknownBlockType)arg2 didCancel:(CDUnknownBlockType)arg3;
+ (void)cancleSSSNetwork;
+ (id)sssGroupBuyRequest;

@end

