//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TTTBaseView.h"

@class NSArray, TTTTotalModel, UIScrollView, UIView;

@interface TTTHeadTabPicTextView : TTTBaseView
{
    double _itemWidth;
    _Bool _isAnimating;
    TTTTotalModel *_totalModel;
    UIView *_backImView;
    UIScrollView *_scrollView;
    NSArray *_buttons;
    unsigned long long _currentIndex;
}

@property(nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
@property(nonatomic) unsigned long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(retain, nonatomic) NSArray *buttons; // @synthesize buttons=_buttons;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UIView *backImView; // @synthesize backImView=_backImView;
@property(retain, nonatomic) TTTTotalModel *totalModel; // @synthesize totalModel=_totalModel;
- (void).cxx_destruct;
- (void)toCenterButton:(double)arg1;
- (void)selectButton:(unsigned long long)arg1;
- (void)initData:(id)arg1;
- (void)buttonsPressed:(id)arg1;
- (void)updateOffset:(struct CGPoint)arg1 isEndScolled:(_Bool)arg2;
- (void)createScrollView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 data:(id)arg2;

@end

