//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TTTBaseModel.h"

@class NSArray, NSString;

@interface TTTPersonalFloorModel : TTTBaseModel
{
    NSString *_templateId;
    NSArray *_coupon_newList;
}

+ (id)objectClassInArray;
@property(retain, nonatomic) NSArray *coupon_newList; // @synthesize coupon_newList=_coupon_newList;
@property(copy, nonatomic) NSString *templateId; // @synthesize templateId=_templateId;
- (void).cxx_destruct;

@end

