//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TTTBaseView.h"

#import "TTTBaseViewProtocol.h"

@class JDImageView, NSString, TTTShopItemNameInfoView, TTTShopModel;

@interface TTTShopItemView : TTTBaseView <TTTBaseViewProtocol>
{
    id <TTTShopItemDelegate> _delegate;
    JDImageView *_hotShopImage1;
    JDImageView *_hotShopImage2;
    JDImageView *_hotShopImage3;
    JDImageView *_logoImageView;
    TTTShopItemNameInfoView *_nameInfoView;
    TTTShopModel *_model;
}

@property(nonatomic) __weak TTTShopModel *model; // @synthesize model=_model;
@property(retain, nonatomic) TTTShopItemNameInfoView *nameInfoView; // @synthesize nameInfoView=_nameInfoView;
@property(retain, nonatomic) JDImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
@property(retain, nonatomic) JDImageView *hotShopImage3; // @synthesize hotShopImage3=_hotShopImage3;
@property(retain, nonatomic) JDImageView *hotShopImage2; // @synthesize hotShopImage2=_hotShopImage2;
@property(retain, nonatomic) JDImageView *hotShopImage1; // @synthesize hotShopImage1=_hotShopImage1;
@property(nonatomic) __weak id <TTTShopItemDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (struct CGRect)shopNameInfoFrame;
- (struct CGRect)logoFrame;
- (struct CGRect)hotShopSmall2Frame;
- (struct CGRect)hotShopSmall1Frame;
- (struct CGRect)hotShopBigImageFrame;
- (void)shopViewClick;
- (void)bindDataWithViewModel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

