//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JDStoreNetwork, NSMutableArray, NSMutableDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface WanderShopManager : NSObject
{
    JDStoreNetwork *entryClickDao;
    NSObject<OS_dispatch_queue> *_cacheIOQueue;
    NSString *_storyCacheFolder;
    NSMutableArray *_circleDetailBannerArray;
    _Bool _isRecommendCircleLoadFinished;
    _Bool _haveNewActivity;
    int _getDataDircetion;
    NSMutableArray *_MyPostedstoryListArray;
    NSMutableArray *_MyPraisedstoryListArray;
    NSString *_storyListLastPubDate;
    NSString *_storyListLastPubId;
    NSMutableArray *_storyListArray;
    NSMutableDictionary *_userHomePageListDic;
    NSMutableDictionary *_userHomePagePraisedListDic;
    NSMutableArray *_activityStoryListArray;
    NSMutableArray *_topBannerListArray;
    NSMutableArray *_myCircleArray;
    NSMutableArray *_specialCircleArray;
    NSMutableArray *_specialCircleIDs;
    NSMutableArray *_recommendCircleArray;
    NSMutableArray *_circleSelectedStoryArray;
    NSMutableArray *_circleNewStoryArray;
    NSString *_recommendFlag;
    NSString *_lastReadTime;
    long long _unreadMessageNum;
    long long _unreadNotificationNum;
    NSString *_shareUrl;
    NSString *_shareTitle;
    NSString *_sharedTopicUrl;
    NSMutableArray *_activeCenterListArray;
    NSMutableArray *_homeCircleListArray;
}

+ (id)autorelease;
+ (oneway void)release;
+ (id)retain;
+ (id)copyWithZone:(struct _NSZone *)arg1;
+ (id)sharedWanderShopManager;
@property(retain, nonatomic) NSMutableArray *homeCircleListArray; // @synthesize homeCircleListArray=_homeCircleListArray;
@property(retain, nonatomic) NSMutableArray *activeCenterListArray; // @synthesize activeCenterListArray=_activeCenterListArray;
@property(copy, nonatomic) NSString *sharedTopicUrl; // @synthesize sharedTopicUrl=_sharedTopicUrl;
@property(copy, nonatomic) NSString *shareTitle; // @synthesize shareTitle=_shareTitle;
@property(copy, nonatomic) NSString *shareUrl; // @synthesize shareUrl=_shareUrl;
@property(nonatomic) long long unreadNotificationNum; // @synthesize unreadNotificationNum=_unreadNotificationNum;
@property(nonatomic) _Bool haveNewActivity; // @synthesize haveNewActivity=_haveNewActivity;
@property(nonatomic) long long unreadMessageNum; // @synthesize unreadMessageNum=_unreadMessageNum;
@property(copy, nonatomic) NSString *lastReadTime; // @synthesize lastReadTime=_lastReadTime;
@property(copy, nonatomic) NSString *recommendFlag; // @synthesize recommendFlag=_recommendFlag;
@property(nonatomic) _Bool isRecommendCircleLoadFinished; // @synthesize isRecommendCircleLoadFinished=_isRecommendCircleLoadFinished;
@property(retain, nonatomic) NSMutableArray *circleNewStoryArray; // @synthesize circleNewStoryArray=_circleNewStoryArray;
@property(retain, nonatomic) NSMutableArray *circleSelectedStoryArray; // @synthesize circleSelectedStoryArray=_circleSelectedStoryArray;
@property(retain, nonatomic) NSMutableArray *recommendCircleArray; // @synthesize recommendCircleArray=_recommendCircleArray;
@property(retain, nonatomic) NSMutableArray *specialCircleIDs; // @synthesize specialCircleIDs=_specialCircleIDs;
@property(retain, nonatomic) NSMutableArray *specialCircleArray; // @synthesize specialCircleArray=_specialCircleArray;
@property(retain, nonatomic) NSMutableArray *myCircleArray; // @synthesize myCircleArray=_myCircleArray;
@property(retain, nonatomic) NSMutableArray *topBannerListArray; // @synthesize topBannerListArray=_topBannerListArray;
@property(retain, nonatomic) NSMutableArray *activityStoryListArray; // @synthesize activityStoryListArray=_activityStoryListArray;
@property(retain, nonatomic) NSMutableDictionary *userHomePagePraisedListDic; // @synthesize userHomePagePraisedListDic=_userHomePagePraisedListDic;
@property(retain, nonatomic) NSMutableDictionary *userHomePageListDic; // @synthesize userHomePageListDic=_userHomePageListDic;
@property(retain, nonatomic) NSMutableArray *storyListArray; // @synthesize storyListArray=_storyListArray;
@property(retain, nonatomic) NSString *storyListLastPubId; // @synthesize storyListLastPubId=_storyListLastPubId;
@property(retain, nonatomic) NSString *storyListLastPubDate; // @synthesize storyListLastPubDate=_storyListLastPubDate;
@property(retain, nonatomic) NSMutableArray *MyPraisedstoryListArray; // @synthesize MyPraisedstoryListArray=_MyPraisedstoryListArray;
@property(retain, nonatomic) NSMutableArray *MyPostedstoryListArray; // @synthesize MyPostedstoryListArray=_MyPostedstoryListArray;
@property(nonatomic) int getDataDircetion; // @synthesize getDataDircetion=_getDataDircetion;
- (void).cxx_destruct;
- (void)didFinishLogin:(id)arg1;
- (void)userDidLogout:(id)arg1;
- (void)drawAttributeString:(id)arg1 inRect:(struct CGRect)arg2 inContext:(struct CGContext *)arg3;
- (struct CGSize)sizeForAttributedString:(id)arg1 forWidth:(double)arg2;
- (void)getImageRange:(id)arg1:(id)arg2;
- (id)transferToAttributeString:(id)arg1 type:(int)arg2;
- (void)getUserHomePage:(long long)arg1 Direction:(int)arg2 pubUseId:(id)arg3 isfirstEntry:(_Bool)arg4 eventSrc:(id)arg5 responseUsingBlock:(CDUnknownBlockType)arg6 network:(id)arg7;
- (void)getUserPraiseStoryList:(long long)arg1 Direction:(int)arg2 pubUseId:(id)arg3 responseUsingBlock:(CDUnknownBlockType)arg4 network:(id)arg5;
- (void)removeModelInMyCircleArray:(id)arg1;
- (void)addModelInMyCircleArray:(id)arg1;
- (_Bool)removeRecommendCircleArray:(id)arg1;
- (void)getCircleStoryList:(CDUnknownBlockType)arg1 CircleId:(id)arg2 requestType:(id)arg3 IsRefresh:(_Bool)arg4 network:(id)arg5;
- (void)joinCircle:(CDUnknownBlockType)arg1 circleModel:(id)arg2 requestType:(id)arg3 network:(id)arg4;
- (void)getRecommendCircleData:(CDUnknownBlockType)arg1 Num:(id)arg2 IsRefresh:(_Bool)arg3 network:(id)arg4;
- (void)getMyCircleData:(CDUnknownBlockType)arg1 network:(id)arg2;
- (void)getCircleInfo:(CDUnknownBlockType)arg1 CircleId:(id)arg2 network:(id)arg3;
- (void)getVideoUrl:(id)arg1 responseUsingBlock:(CDUnknownBlockType)arg2 network:(id)arg3;
- (void)getStoryDetail:(id)arg1 responseUsingBlock:(CDUnknownBlockType)arg2 network:(id)arg3;
- (void)registerTopic:(id)arg1 responseUsingBlock:(CDUnknownBlockType)arg2 network:(id)arg3;
- (void)getActivityStateWithActivity:(id)arg1 activityBeginTime:(id)arg2 activityEndTime:(id)arg3 responseUsingBlock:(CDUnknownBlockType)arg4 network:(id)arg5;
- (void)getActivityStoryList:(long long)arg1 Direction:(int)arg2 topicId:(id)arg3 themeId:(id)arg4 oType:(id)arg5 responseUsingBlock:(CDUnknownBlockType)arg6 network:(id)arg7;
- (void)getDetailInfoWithActivity:(id)arg1 type:(id)arg2 responseUsingBlock:(CDUnknownBlockType)arg3 network:(id)arg4;
- (void)getActiveCenterList:(CDUnknownBlockType)arg1 Direction:(int)arg2 network:(id)arg3;
- (void)getStoryList:(long long)arg1 Direction:(int)arg2 responseUsingBlock:(CDUnknownBlockType)arg3 cancelBlock:(CDUnknownBlockType)arg4 network:(id)arg5;
- (void)requestDataWithBlock:(CDUnknownBlockType)arg1 network:(id)arg2;
- (void)getNewActivityRedDotWithTime:(id)arg1 responseUsingBlock:(CDUnknownBlockType)arg2 network:(id)arg3;
- (void)isUserInWhiteList:(CDUnknownBlockType)arg1 network:(id)arg2;
- (void)reportStory:(id)arg1 reportType:(id)arg2 responseUsingBlock:(CDUnknownBlockType)arg3 network:(id)arg4;
- (void)getEncourageStory:(id)arg1 number:(id)arg2 responseUsingBlock:(CDUnknownBlockType)arg3 net:(id)arg4;
- (void)getStoryShareData:(CDUnknownBlockType)arg1 net:(id)arg2;
- (void)deleteStoryComment:(id)arg1 commentId:(id)arg2 commentList:(id)arg3 responseUsingBlock:(CDUnknownBlockType)arg4 network:(id)arg5;
- (void)getStoryCommentList:(id)arg1 isGetMore:(_Bool)arg2 commentList:(id)arg3 responseUsingBlock:(CDUnknownBlockType)arg4 network:(id)arg5;
- (void)sendStoryComment:(id)arg1 replyId:(id)arg2 content:(id)arg3 commentList:(id)arg4 responseUsingBlock:(CDUnknownBlockType)arg5 network:(id)arg6;
- (void)uploadHeaderBackgroundImage:(id)arg1 isHeaderView:(_Bool)arg2 responseUsingBlock:(CDUnknownBlockType)arg3 network:(id)arg4;
- (void)changeUserIntroduction:(id)arg1 nickName:(id)arg2 responseUsingBlock:(CDUnknownBlockType)arg3 network:(id)arg4;
- (void)doStoryActionInDateBase:(id)arg1 storyId:(id)arg2;
- (void)doStoryAction:(int)arg1 storyId:(id)arg2 responseUsingBlock:(CDUnknownBlockType)arg3 network:(id)arg4;
- (void)getpraiseInfo:(id)arg1 responseUsingBlock:(CDUnknownBlockType)arg2 network:(id)arg3;
- (id)getMainStoryListLastStory;
- (id)getMainStoryListFirstStory;
- (id)parserJsonWithData:(id)arg1 errorMsg:(id *)arg2;
- (void)insertactiveToMainStoryList:(id)arg1;
- (id)networkStatus;
- (void)entryClick;
- (void)saveUserCenterPraiseList:(id)arg1;
- (id)loadUserCenterPraiseList;
- (void)saveUserCenterCreateStoryList:(id)arg1;
- (id)loadUserCenterCreateStoryList;
- (void)saveStoryDetailComment:(id)arg1 withStroryID:(id)arg2;
- (id)loadStoryDetailCommentWithStroryID:(id)arg1;
- (void)saveStoryDetailInfo:(id)arg1 withStoryID:(id)arg2;
- (id)loadStoryDetailInfoWithStroryID:(id)arg1;
- (void)saveActiveStoryList:(id)arg1 withActiveID:(id)arg2;
- (id)loadActiveStoryListWithID:(id)arg1;
- (void)saveActiveDetailInfo:(id)arg1 withActiveID:(id)arg2;
- (id)loadActiveDetailInfoWithID:(id)arg1;
- (void)saveCircleInfo:(id)arg1 CircleId:(id)arg2;
- (id)loadCircleInfo:(id)arg1;
- (void)saveRecommendCircle:(id)arg1;
- (id)loadRecommendCircle;
- (void)saveCircleStoryList:(id)arg1 CircleId:(id)arg2;
- (id)loadCircleStoryList:(id)arg1;
- (void)saveActiveList:(id)arg1;
- (id)loadActiveList;
- (void)saveHomeStoryList:(id)arg1;
- (id)loadHomeStoryList;
- (void)saveHomeMyCircleList:(id)arg1;
- (id)loadHomeMyCircleList;
- (void)saveHomeBannerInfo:(id)arg1;
- (id)loadHomeBannerInfo;
- (id)fileNameAppendUserPin:(id)arg1;
- (id)loadData:(id)arg1;
- (void)deleteCacheData:(id)arg1;
- (void)saveData:(id)arg1 toFile:(id)arg2;
- (id)filePathOfName:(id)arg1;
@property(readonly, copy, nonatomic) NSString *storyCacheFolder;
- (id)cacheIOQueue;
- (id)init;
- (void)dealloc;

@end

