//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDViewController.h"

#import "BusinessSupportPlatformViewDelegate.h"
#import "FunctionButtonsViewDelegate.h"
#import "GiftRequestManagerDelegate.h"
#import "JDBaseToastRealnameVerifyViewDelegate.h"
#import "JDContentItemDelegate.h"
#import "JDContentViewDataSource.h"
#import "PDCouponPopupViewDelegate.h"
#import "PDDrugAnswerFloorProtocol.h"
#import "TTTAttributedLabelDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UIViewControllerPreviewingDelegate.h"
#import "WareBRateViewDelegate.h"
#import "WareBSKUDetailViewDelegate.h"
#import "WareBStoreServiceViewDelegate.h"
#import "WareInfoNetworkResponseDelegate.h"
#import "WareMenuViewDelegate.h"
#import "WarePageViewDelegate.h"

@class JDBaseToastView, JDContentView, JDImageView, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, NewProductModel, PDCouponPopupView, PDWeakTimer, UILabel, WareBBottomButtonsView, WareBImageView, WareBSKUDetailView, WareCommentDetailListViewController, WareInfoDataAccessObject, WareInfoParamModel, WareInfoWhitePlanInfo, WareIntroDetailView, WareIntroViewController, WareMenuView, WarePageView;

@interface WareInfoBViewController : JDViewController <WareMenuViewDelegate, BusinessSupportPlatformViewDelegate, FunctionButtonsViewDelegate, UIViewControllerPreviewingDelegate, UIActionSheetDelegate, PDDrugAnswerFloorProtocol, JDContentViewDataSource, WareBStoreServiceViewDelegate, TTTAttributedLabelDelegate, JDContentItemDelegate, WareBSKUDetailViewDelegate, UIScrollViewDelegate, WareBRateViewDelegate, GiftRequestManagerDelegate, WareInfoNetworkResponseDelegate, WarePageViewDelegate, JDBaseToastRealnameVerifyViewDelegate, PDCouponPopupViewDelegate>
{
    WareIntroDetailView *_detailView;
    _Bool isDetailViewInit_;
    _Bool isDetailViewAddedToSuperView;
    long long _originSeconds;
    NSMutableDictionary *_yuYueAllDic;
    NSString *_wareId;
    NewProductModel *_wareModel;
    WareInfoDataAccessObject *_wareInfoDataAccessObject;
    JDBaseToastView *_toast;
    WareInfoParamModel *_wareInfoParamModel;
    JDBaseToastView *_captchaView;
    WareBSKUDetailView *_skuDetailView;
    NSMutableArray *_subviews;
    WareBBottomButtonsView *_wareButtons;
    NSString *_locParamString;
    NSDictionary *_locParams;
    NSMutableArray *_moreArray;
    JDContentView *_contentView;
    WarePageView *_pageView;
    WareIntroViewController *_wareIntroController;
    WareCommentDetailListViewController *_wareCommentDetailListController;
    NSMutableArray *_pageViewArray;
    PDWeakTimer *_weakTimer;
    WareBImageView *_mainSkuImageView;
    double _mainSkuImageViewTopMargin;
    PDCouponPopupView *_couponView;
}

@property(retain, nonatomic) PDCouponPopupView *couponView; // @synthesize couponView=_couponView;
@property(nonatomic) double mainSkuImageViewTopMargin; // @synthesize mainSkuImageViewTopMargin=_mainSkuImageViewTopMargin;
@property(retain, nonatomic) WareBImageView *mainSkuImageView; // @synthesize mainSkuImageView=_mainSkuImageView;
@property(retain, nonatomic) PDWeakTimer *weakTimer; // @synthesize weakTimer=_weakTimer;
@property(retain, nonatomic) NSMutableArray *pageViewArray; // @synthesize pageViewArray=_pageViewArray;
@property(retain, nonatomic) WareCommentDetailListViewController *wareCommentDetailListController; // @synthesize wareCommentDetailListController=_wareCommentDetailListController;
@property(retain, nonatomic) WareIntroViewController *wareIntroController; // @synthesize wareIntroController=_wareIntroController;
@property(retain, nonatomic) WarePageView *pageView; // @synthesize pageView=_pageView;
@property(retain, nonatomic) JDContentView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) NSMutableArray *moreArray; // @synthesize moreArray=_moreArray;
@property(copy, nonatomic) NSDictionary *locParams; // @synthesize locParams=_locParams;
@property(copy, nonatomic) NSString *locParamString; // @synthesize locParamString=_locParamString;
@property(retain, nonatomic) WareBBottomButtonsView *wareButtons; // @synthesize wareButtons=_wareButtons;
@property(retain, nonatomic) NSMutableArray *subviews; // @synthesize subviews=_subviews;
@property(retain, nonatomic) WareBSKUDetailView *skuDetailView; // @synthesize skuDetailView=_skuDetailView;
@property(retain, nonatomic) JDBaseToastView *captchaView; // @synthesize captchaView=_captchaView;
@property(retain, nonatomic) WareInfoParamModel *wareInfoParamModel; // @synthesize wareInfoParamModel=_wareInfoParamModel;
@property(retain, nonatomic) JDBaseToastView *toast; // @synthesize toast=_toast;
@property(retain, nonatomic) WareInfoDataAccessObject *wareInfoDataAccessObject; // @synthesize wareInfoDataAccessObject=_wareInfoDataAccessObject;
@property(retain, nonatomic) NewProductModel *wareModel; // @synthesize wareModel=_wareModel;
@property(copy, nonatomic) NSString *wareId; // @synthesize wareId=_wareId;
- (void).cxx_destruct;
- (void)applicationBackgroud:(id)arg1;
- (id)sectionForIdentifier:(id)arg1;
- (void)scrollToProductInfo_M;
- (void)scrollToProductInfo_Local;
- (void)returnTop:(id)arg1;
- (void)setCurrentPageTo:(long long)arg1 animate:(_Bool)arg2;
- (void)reloadContentView;
- (void)setupDetailUI;
- (void)setupBasicUI;
- (void)scrollToWareCommentDetailListViewController:(id)arg1;
- (void)updateBadge:(id)arg1;
- (void)reportDataWithCode:(id)arg1 imageUrl:(id)arg2;
- (void)fetchGetWareDetailCommentData;
- (void)fetchSkuDyInfoData:(id)arg1;
- (void)fetchSkuDetailData;
- (void)reloadSizeHelperView:(id)arg1;
- (void)priceDownNotification:(id)arg1;
- (void)cancelFavorite;
- (void)addFavorite:(_Bool)arg1;
- (void)skuNotice;
- (void)jumpOrderVC;
- (void)buyGiftCard;
- (void)gameQqBuy;
- (void)addGiftToCartSuccess:(_Bool)arg1;
- (void)beginBuyForPresentBuy;
- (void)getProductsMatchSelectedCar:(id)arg1;
- (_Bool)handleJumpService;
- (void)checkUserMessageWithName:(id)arg1 idNumber:(id)arg2;
- (void)toastView:(id)arg1 didFinishWithName:(id)arg2 idNumber:(id)arg3;
- (void)captchaVerifyCancel;
- (void)closePopupView:(id)arg1;
- (void)responseWithFunctionId:(long long)arg1 withModel:(id)arg2;
- (void)jumpToMOrderInfo;
- (void)jumpToDingZhiView;
- (void)jumpToHybrid;
- (void)inviteFriend;
- (void)InternationalAuthFinish:(_Bool)arg1;
- (void)cartShield;
- (void)miaoshaGotoOrder;
- (void)tappedButtonInView:(id)arg1 withViewTag:(long long)arg2 withButtonTag:(long long)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)headerImageViewTapped:(id)arg1;
- (void)largeImageDownloadFaild:(id)arg1;
- (void)imageDownloadFaild:(id)arg1;
- (void)imageView:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (void)bargainByChat:(id)arg1;
- (void)invokeJIMI;
- (void)invokeIM;
- (void)updateStoreServiceView;
- (void)storeServiceView:(id)arg1 tappedButtonAtIndex:(long long)arg2;
- (void)showWareCommentAblum;
- (void)wareBRateViewButtonTapped:(id)arg1;
- (void)changeAddToCartButtonState:(id)arg1;
- (void)changeWare:(id)arg1;
- (void)adwordLinkInvoke:(id)arg1;
- (void)tuwenInvoke:(id)arg1;
- (void)pageViewDidChanged:(long long)arg1;
- (id)separatorViewWithTopSection:(long long)arg1;
- (id)contentView:(id)arg1 sectionAtIndex:(long long)arg2;
- (long long)numberOfSectionsInConentView:(id)arg1;
- (void)fetchCouponViewDataAndIsCouponViewShowWhenComplete:(_Bool)arg1;
- (void)fetchReceiveDataFromNetworkWithParam:(id)arg1;
- (void)tableViewCellDidSelected;
- (void)reloadFetchCouponViewData;
- (void)openPlusMemberView;
- (void)jumpToWenDa;
- (void)didTapAtItemView:(id)arg1;
- (void)backButtonClicked;
- (void)statusBarFrameChanged:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)initViewsWithIntialParam;
- (id)initWithModel:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) UILabel *messageNumberLabel;
@property(retain, nonatomic) JDImageView *messageNumberIcon;
@property(retain, nonatomic) JDImageView *redDotImageView; // @dynamic redDotImageView;
@property(retain, nonatomic) WareMenuView *menuView; // @dynamic menuView;
@property(retain, nonatomic) UILabel *titleLabel; // @dynamic titleLabel;
@property(retain, nonatomic) UILabel *tuwenLabel; // @dynamic tuwenLabel;
- (void)getRedDotCompleted:(id)arg1;
- (void)setRedDotHidden:(_Bool)arg1;
- (void)menuViewDidChanged:(long long)arg1;
- (void)goToMyFavorite;
- (void)goToMessageCenter;
- (void)shareAction:(id)arg1;
- (void)shareWithUrl:(id)arg1 weiBoContent:(id)arg2 weiXinContent:(id)arg3 hasWeiBo:(_Bool)arg4;
- (void)moreAction:(id)arg1;
- (void)toastView:(id)arg1 didSelectMenuRow:(long long)arg2;
- (_Bool)toastView:(id)arg1 hasRedDotAtRow:(long long)arg2;
- (id)toastView:(id)arg1 titleForMenuRow:(long long)arg2;
- (id)toastView:(id)arg1 imageForMenuRow:(long long)arg2;
- (long long)numberOfRowsInMenuToastView:(id)arg1;
- (void)configNavigationBarView;
- (void)jumpToSkuDetaiView;
- (void)businessSupportPlatformView:(id)arg1 fetchLvDataWithParams:(id)arg2;
- (void)updateBusinessSupportPlatformView;
- (void)captchaException:(id)arg1;
- (void)changeVerifyCodeImageInToastView;
- (void)verifyWithInputCode:(id)arg1;
- (void)inputViewHasCharacter:(_Bool)arg1;
- (void)popupVerificationCodeViewImage:(id)arg1;
- (void)didFinishInToastView:(id)arg1;
- (void)didCancelInToastView:(id)arg1;
- (void)startYuYue;
- (void)requestCaptchaWithParams:(id)arg1;
- (void)requestYuye;
- (void)beginBuyForYuYue;
- (void)requestConfirmIsAppointFromYuyu:(_Bool)arg1;
- (void)countDownConfig;
- (void)refreshYuYueBtWithModel:(id)arg1;
- (void)clockTick;
- (void)yuYueTimeEnd:(_Bool)arg1;
- (void)beginBuySpecialWareWithType;
- (void)requestSpecialWithType;
- (void)locShopSelected:(id)arg1;
- (void)locPurchase;
- (id)previewActionItems;
- (id)previewingContext:(id)arg1 viewControllerForLocation:(struct CGPoint)arg2;
- (void)traitCollectionDidChange:(id)arg1;
@property(retain, nonatomic) WareInfoWhitePlanInfo *planInfoSelected;
- (void)whiteBarOpenUrl;
- (void)whiteBarIntoOrder;
- (void)whiteBarpay:(id)arg1;
- (void)whiteBarFinishLogin;
- (void)whiteBarpopupSelector;
- (void)changeSkin;
- (id)analysisSkuDyInfoDataWithString:(id)arg1;
- (id)analysisSkuDetailDataWithString:(id)arg1;
- (void)updateStock:(id)arg1;
- (void)updateStockStatusWithParams:(id)arg1;
- (void)goToOrder;
- (void)startYuShou;
- (id)buildUpStatisticsParams;
- (id)getRecommendGoodsWareIds;
- (id)checkoutParams;
- (void)cancelRequestByQueue:(id)arg1;
- (void)reRequestByQueue:(id)arg1;
@property(nonatomic) _Bool shouldShowToastWhenAddToCartInfoReturn; // @dynamic shouldShowToastWhenAddToCartInfoReturn;
- (void)addToCartNotification:(id)arg1;
- (void)showAddCartToast:(long long)arg1 msg:(id)arg2;
- (void)addWareToShopCart:(_Bool)arg1;
- (void)removeNotificationsInDeallocFunction;
- (void)addNotificationsInViewDidLoadFunction;
- (void)removeNotificationsInViewWillDisappearFunction;
- (void)addNotificationsInViewWillAppearFunction;
- (_Bool)dealWithTreaty;
- (void)restoreJDPrice:(id)arg1;
- (void)getTreatyPrice:(id)arg1;
- (void)jumpToAnswerPage;
- (void)jumpToCertificatePage;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)loginAddDrugCartCallback:(id)arg1;
- (void)addDrugCart:(_Bool)arg1;
- (void)refreshDrugCartNum;
- (void)drugPhoneClick;
- (void)jumpToDrugListPage;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

