//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JDView.h"

@class BrowseHistoryDao, JDFooterLoadingView, JDStoreNetwork, NSMutableArray, NewProductModel, UIButton, UITableView, UIView;

@interface WareHistroyView : JDView
{
    UIButton *maskView_;
    UIView *titleView_;
    UITableView *myTable_;
    int currentPage;
    BrowseHistoryDao *browseDao_;
    JDStoreNetwork *networkDao_;
    _Bool isLoading;
    _Bool isGetMore;
    NSMutableArray *items_;
    JDFooterLoadingView *footerView_;
    UIView *headView_;
    UIView *backgroundView_;
    NewProductModel *_model;
}

@property(retain, nonatomic) NewProductModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)didFinishResponse:(id)arg1 requestSetup:(id)arg2 components:(id)arg3 msg:(id)arg4;
- (void)scrollViewDidScroll:(id)arg1;
- (void)refreshView;
- (id)genParamsWithPage:(int)arg1;
- (void)requestDataWithPage:(int)arg1;
- (void)dismiss;
- (void)show;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

