//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSMutableArray, UILabel, WBSDKCountryCode;

@interface WBSDKPhoneCountryView : UIButton
{
    long long _countryCodeStr;
    NSMutableArray *_countryArray;
    WBSDKCountryCode *_currentCoutryCode;
    UILabel *_codeLabel;
    UILabel *_countryLabel;
}

@property(retain, nonatomic) UILabel *countryLabel; // @synthesize countryLabel=_countryLabel;
@property(retain, nonatomic) UILabel *codeLabel; // @synthesize codeLabel=_codeLabel;
@property(retain, nonatomic) WBSDKCountryCode *currentCoutryCode; // @synthesize currentCoutryCode=_currentCoutryCode;
@property(retain, nonatomic) NSMutableArray *countryArray; // @synthesize countryArray=_countryArray;
- (void).cxx_destruct;
- (_Bool)isStringNull:(id)arg1;
- (id)getSimCardInformation;
- (void)matchingMCC:(id)arg1;
- (void)insertCommonUseData;
- (void)indexedContactsArrayWithSortedContacts:(id)arg1;
- (void)getCountryList;
- (_Bool)isPhoneMacthCountry;
- (id)initWithFrame:(struct CGRect)arg1;

@end

