//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDictionary, NSObject, NSString, UIImage;
@protocol ABDetectListener, ABLivenessDetector, OS_dispatch_queue;

@protocol ABLivenessDetector <NSObject>
- (NSString *)getLog;
- (void)reset;
- (NSArray *)getValidFrame;
- (int)getCurrentDetectType;
- (void)changeDetectType:(int)arg1;
- (_Bool)doDetect:(UIImage *)arg1 datas:(NSDictionary *)arg2;
- (_Bool)doDetect:(UIImage *)arg1;
- (_Bool)doDetect:(struct opaqueCMSampleBuffer *)arg1 orientation:(long long)arg2 datas:(NSDictionary *)arg3;
- (_Bool)doDetect:(struct opaqueCMSampleBuffer *)arg1 orientation:(long long)arg2;
- (NSString *)getVersion;
- (void)setDetectListener:(id <ABDetectListener>)arg1;
- (id <ABLivenessDetector>)init:(NSDictionary *)arg1;
- (id <ABLivenessDetector>)init:(NSDictionary *)arg1 andDispatchQueue:(NSObject<OS_dispatch_queue> *)arg2;
@end

