//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface ACDSMonitor : NSObject
{
}

+ (void)monitorDataFailure:(int)arg1 withDS:(id)arg2 withErrorCode:(int)arg3 withExtParam:(id)arg4;
+ (void)monitorDataSuccess:(int)arg1 withDS:(id)arg2 withExtParam:(id)arg3;
+ (id)convertMonitorKey:(int)arg1;
+ (id)sharedInstance;

@end

