//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AliDetailBaseContainerView.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class AliDetailContractPhoneCityView, AliDetailContractPhoneDataEngine, AliDetailContractPhoneNavigationBar, AliDetailContractPhonePackageView, AliDetailContractPhoneSelectNumberView, AliDetailDataEngine, AliDetailSkuContractInfo, NSArray, NSString, UIButton, UIImageView, UITableView, UIView;
@protocol AliDetailContractPhoneViewProtocal;

@interface AliDetailContractPhoneMainView : AliDetailBaseContainerView <UITableViewDataSource, UITableViewDelegate>
{
    _Bool _isAddObserver;	// 8 = 0x8
    AliDetailDataEngine *_dataEngine;	// 16 = 0x10
    AliDetailContractPhoneCityView *_cityView;	// 24 = 0x18
    AliDetailContractPhonePackageView *_packageView;	// 32 = 0x20
    AliDetailContractPhoneSelectNumberView *_selectNumberView;	// 40 = 0x28
    UIImageView *_animationImageView;	// 48 = 0x30
    UIView<AliDetailContractPhoneViewProtocal> *_currentView;	// 56 = 0x38
    AliDetailContractPhoneNavigationBar *_navigationBar;	// 64 = 0x40
    UITableView *_tableView;	// 72 = 0x48
    UIView *_footerView;	// 80 = 0x50
    UIButton *_finishBtn;	// 88 = 0x58
    UIView *_loadingView;	// 96 = 0x60
    long long _currentItemType;	// 104 = 0x68
    NSArray *_itemsArray;	// 112 = 0x70
    AliDetailSkuContractInfo *_contractInfo;	// 120 = 0x78
    AliDetailContractPhoneDataEngine *_contractDataEngine;	// 128 = 0x80
}

@property(nonatomic) _Bool isAddObserver; // @synthesize isAddObserver=_isAddObserver;
@property(retain, nonatomic) AliDetailContractPhoneDataEngine *contractDataEngine; // @synthesize contractDataEngine=_contractDataEngine;
@property(nonatomic) __weak AliDetailSkuContractInfo *contractInfo; // @synthesize contractInfo=_contractInfo;
@property(retain, nonatomic) NSArray *itemsArray; // @synthesize itemsArray=_itemsArray;
@property(nonatomic) long long currentItemType; // @synthesize currentItemType=_currentItemType;
@property(retain, nonatomic) UIView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) UIButton *finishBtn; // @synthesize finishBtn=_finishBtn;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) AliDetailContractPhoneNavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
@property(retain, nonatomic) UIView<AliDetailContractPhoneViewProtocal> *currentView; // @synthesize currentView=_currentView;
@property(retain, nonatomic) UIImageView *animationImageView; // @synthesize animationImageView=_animationImageView;
@property(retain, nonatomic) AliDetailContractPhoneSelectNumberView *selectNumberView; // @synthesize selectNumberView=_selectNumberView;
@property(retain, nonatomic) AliDetailContractPhonePackageView *packageView; // @synthesize packageView=_packageView;
@property(retain, nonatomic) AliDetailContractPhoneCityView *cityView; // @synthesize cityView=_cityView;
@property(retain, nonatomic) AliDetailDataEngine *dataEngine; // @synthesize dataEngine=_dataEngine;
- (void).cxx_destruct;
- (void)handlePhoneNumEvent:(id)arg1;
- (void)handlePackageEvent:(id)arg1;
- (void)handleCityEvent:(id)arg1;
- (void)onFinishBtnClick;
- (CDUnknownBlockType)viewWillAppearBlock;
- (CDUnknownBlockType)viewDidDisappearBlock;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)cellOfType:(long long)arg1;
- (void)showLoading:(_Bool)arg1;
- (struct CGRect)viewFrameOfType:(long long)arg1;
- (double)offsetYOfType:(long long)arg1;
- (id)viewOfType:(long long)arg1;
- (void)closeView;
- (void)openView:(long long)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)clearData;
- (void)removeObserver;
- (void)initContractEngine:(id)arg1;
- (void)prepareData;
- (void)createSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

