//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class AliDetailSizeChartComponentViewModel, AliDetailSizeChartTitleView, AliProductSingleSizeChartComponent;

@interface AliDetailSizeChartView : UIView
{
    AliDetailSizeChartComponentViewModel *_sizeChartModel;	// 8 = 0x8
    AliProductSingleSizeChartComponent *_sizeChartComponent;	// 16 = 0x10
    AliDetailSizeChartTitleView *_titleView;	// 24 = 0x18
}

@property(retain, nonatomic) AliDetailSizeChartTitleView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) AliProductSingleSizeChartComponent *sizeChartComponent; // @synthesize sizeChartComponent=_sizeChartComponent;
@property(retain, nonatomic) AliDetailSizeChartComponentViewModel *sizeChartModel; // @synthesize sizeChartModel=_sizeChartModel;
- (void).cxx_destruct;
- (id)sizeChartComponentModel;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;

@end

