//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface aluDeviceTokenDTO : NSObject
{
    NSString *_key;	// 8 = 0x8
    NSString *_salt;	// 16 = 0x10
}

@property(copy, nonatomic) NSString *salt; // @synthesize salt=_salt;
@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
- (void).cxx_destruct;

@end

