//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "aluInputBoxDelegate-Protocol.h"

@class NSArray, NSString, UILabel, UITableView, aluInputBox;
@protocol aluLoginBoxDelegate;

@interface aluLoginBox : UIView <aluInputBoxDelegate, UITableViewDataSource, UITableViewDelegate>
{
    long long _selectedHistoryIndex;	// 8 = 0x8
    struct CGRect _originalFrame;	// 16 = 0x10
    _Bool _historyTableVisible;	// 48 = 0x30
    _Bool _showHiddenPwd;	// 49 = 0x31
    aluInputBox *_loginIdInputBox;	// 56 = 0x38
    aluInputBox *_passwordInputBox;	// 64 = 0x40
    UIView *_upLine;	// 72 = 0x48
    UIView *_midLine;	// 80 = 0x50
    UITableView *_historyTableView;	// 88 = 0x58
    NSArray *_historyItems;	// 96 = 0x60
    id <aluLoginBoxDelegate> _delegate;	// 104 = 0x68
    double _inputBoxHeight;	// 112 = 0x70
    UILabel *_pwdRightAccessoryLabel;	// 120 = 0x78
}

+ (id)aluLoginBoxWith:(id)arg1 delegate:(id)arg2 frame:(struct CGRect)arg3;
@property(nonatomic) _Bool showHiddenPwd; // @synthesize showHiddenPwd=_showHiddenPwd;
@property(nonatomic) __weak UILabel *pwdRightAccessoryLabel; // @synthesize pwdRightAccessoryLabel=_pwdRightAccessoryLabel;
@property(nonatomic) _Bool historyTableVisible; // @synthesize historyTableVisible=_historyTableVisible;
@property(nonatomic) double inputBoxHeight; // @synthesize inputBoxHeight=_inputBoxHeight;
@property(nonatomic) __weak id <aluLoginBoxDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *historyItems; // @synthesize historyItems=_historyItems;
@property(nonatomic) __weak UITableView *historyTableView; // @synthesize historyTableView=_historyTableView;
@property(nonatomic) __weak UIView *midLine; // @synthesize midLine=_midLine;
@property(nonatomic) __weak UIView *upLine; // @synthesize upLine=_upLine;
@property(nonatomic) __weak aluInputBox *passwordInputBox; // @synthesize passwordInputBox=_passwordInputBox;
@property(nonatomic) __weak aluInputBox *loginIdInputBox; // @synthesize loginIdInputBox=_loginIdInputBox;
- (void).cxx_destruct;
- (id)loginIdOfItemWithIndex:(long long)arg1;
- (struct CGSize)sizeThatFit;
- (struct CGSize)historyTableSizeThatFit;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)aluInputBoxTextDidBegin:(id)arg1;
- (void)cancleRequest;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldClear:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)aluIputBoxTextInputDidChange:(id)arg1;
- (void)aluIputBoxRightAccessoryClicked:(id)arg1;
- (void)clearLoginIdHistoryItem;
- (id)getSelectedHistoryUser;
- (void)setSelectedIndex:(long long)arg1;
- (void)reload;
- (id)getPassword;
- (id)getLoginId;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

