//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@interface aluLinkButton : UIButton
{
}

+ (id)buttonWithTitle:(id)arg1 normalColor:(id)arg2 highLightColor:(id)arg3;
+ (id)buttonWithTitle:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

