//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSThread.h>

@class NSMutableOrderedSet;
@protocol AppMonitorTask;

@interface AppMonitorTaskPool : NSThread
{
    NSMutableOrderedSet<AppMonitorTask> *taskList;	// 64 = 0x40
    float miniInterval;	// 72 = 0x48
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedAppMonitorTaskPool;
- (void).cxx_destruct;
- (void)main;
- (void)dealloc;
- (void)removeTaskForKey:(id)arg1;
- (void)startMainLoop;
- (void)addTask:(id)arg1 forKey:(id)arg2;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

