//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TBChannelTabBarViewDelegate-Protocol.h"

@class NSMutableArray, NSString;
@protocol TBChannelTabBarViewDelegate;

@interface BottomTabbar : UIView <TBChannelTabBarViewDelegate>
{
    id <TBChannelTabBarViewDelegate> delegate;	// 8 = 0x8
    long long _currentSelectTag;	// 16 = 0x10
    NSMutableArray *_menuData;	// 24 = 0x18
}

@property(retain, nonatomic) NSMutableArray *menuData; // @synthesize menuData=_menuData;
@property(nonatomic) long long currentSelectTag; // @synthesize currentSelectTag=_currentSelectTag;
@property(nonatomic) __weak id <TBChannelTabBarViewDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)tabBarButtonClicked:(id)arg1;
- (_Bool)willUseSpecialUIStyle;
- (void)setTabBarData:(id)arg1;
- (void)buttonSelectWithTag:(long long)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

