//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UILabel;

@interface Bubble : UIView
{
    UILabel *label;	// 8 = 0x8
    UIView *bg;	// 16 = 0x10
    NSString *_text;	// 24 = 0x18
}

@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (void)papapa;
- (id)init;

@end

