//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface EventInfo : NSObject
{
    SEL _sel;	// 8 = 0x8
    id _receiver;	// 16 = 0x10
    id _sender;	// 24 = 0x18
}

@property(nonatomic) __weak id sender; // @synthesize sender=_sender;
@property(nonatomic) __weak id receiver; // @synthesize receiver=_receiver;
@property(nonatomic) SEL sel; // @synthesize sel=_sel;
- (void).cxx_destruct;

@end

