//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface GDMBanner : NSObject
{
    float _bannerHeight;	// 8 = 0x8
    NSString *_bannerPic;	// 16 = 0x10
    NSString *_bannerUrl;	// 24 = 0x18
}

@property float bannerHeight; // @synthesize bannerHeight=_bannerHeight;
@property(copy, nonatomic) NSString *bannerUrl; // @synthesize bannerUrl=_bannerUrl;
@property(copy, nonatomic) NSString *bannerPic; // @synthesize bannerPic=_bannerPic;
- (void).cxx_destruct;
- (_Bool)parserResponse:(id)arg1;

@end

