//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDMMtopRequest.h"

@class NSArray;

@interface GDMDarenFeedSearchRequest : GDMMtopRequest
{
    _Bool _isLoadFinish;	// 8 = 0x8
    NSArray *_feedItemArray;	// 16 = 0x10
}

@property _Bool isLoadFinish; // @synthesize isLoadFinish=_isLoadFinish;
@property(retain) NSArray *feedItemArray; // @synthesize feedItemArray=_feedItemArray;
- (void).cxx_destruct;
- (void)startLoadFeedListWithUserId:(id)arg1 timestamp:(id)arg2 tags:(id)arg3 finishBlock:(CDUnknownBlockType)arg4;
- (void)startLoadFeedListWithUserId:(id)arg1 timestamp:(id)arg2 tapType:(id)arg3 finishBlock:(CDUnknownBlockType)arg4;
- (_Bool)procResultDataFromJson:(id)arg1;
- (id)methodName;

@end

