//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDMMtopRequest.h"

@class NSArray;

@interface GDMPublishLocationPOIRequest : GDMMtopRequest
{
    NSArray *_poiItems;	// 8 = 0x8
}

@property(retain) NSArray *poiItems; // @synthesize poiItems=_poiItems;
- (void).cxx_destruct;
- (void)startLoadPIOInfoWithCoord:(CDStruct_2c43369c)arg1 keyword:(id)arg2 finishBlock:(CDUnknownBlockType)arg3;
- (_Bool)procResultDataFromJson:(id)arg1;
- (id)methodName;

@end

