//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPUImageFilter.h"

@class NSArray;

@interface GPUImageToneCurveFilter : GPUImageFilter
{
    int toneCurveTextureUniform;	// 216 = 0xd8
    unsigned int toneCurveTexture;	// 220 = 0xdc
    char *toneCurveByteArray;	// 224 = 0xe0
    NSArray *_redCurve;	// 232 = 0xe8
    NSArray *_greenCurve;	// 240 = 0xf0
    NSArray *_blueCurve;	// 248 = 0xf8
    NSArray *_rgbCompositeCurve;	// 256 = 0x100
    NSArray *_rgbCompositeControlPoints;	// 264 = 0x108
    NSArray *_redControlPoints;	// 272 = 0x110
    NSArray *_greenControlPoints;	// 280 = 0x118
    NSArray *_blueControlPoints;	// 288 = 0x120
}

@property(copy, nonatomic) NSArray *blueControlPoints; // @synthesize blueControlPoints=_blueControlPoints;
@property(copy, nonatomic) NSArray *greenControlPoints; // @synthesize greenControlPoints=_greenControlPoints;
@property(copy, nonatomic) NSArray *redControlPoints; // @synthesize redControlPoints=_redControlPoints;
@property(copy, nonatomic) NSArray *rgbCompositeControlPoints; // @synthesize rgbCompositeControlPoints=_rgbCompositeControlPoints;
- (void).cxx_destruct;
- (void)setRGBControlPoints:(id)arg1;
- (void)renderToTextureWithVertices:(const float *)arg1 textureCoordinates:(const float *)arg2 sourceTexture:(unsigned int)arg3;
- (void)updateToneCurveTexture;
- (id)secondDerivative:(id)arg1;
- (id)splineCurve:(id)arg1;
- (id)getPreparedSplineCurve:(id)arg1;
- (void)dealloc;
- (void)setPointsWithACVURL:(id)arg1;
- (void)setPointsWithACV:(id)arg1;
- (id)initWithACVURL:(id)arg1;
- (id)initWithACV:(id)arg1;
- (id)initWithACVData:(id)arg1;
- (id)init;

@end

