//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIView;

@protocol HTUIGalleryViewDelegate <NSObject>

@optional
- (void)didSelectViewAtIndex:(long long)arg1;
- (UIView *)viewAtIndex:(long long)arg1 frame:(struct CGRect)arg2;
@end

