//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@interface JHSFreeLayoutButton : UIButton
{
    _Bool _useCustomRect;	// 8 = 0x8
    struct CGRect _customImageRect;	// 16 = 0x10
    struct CGRect _customTitleRect;	// 48 = 0x30
}

@property(nonatomic) struct CGRect customTitleRect; // @synthesize customTitleRect=_customTitleRect;
@property(nonatomic) struct CGRect customImageRect; // @synthesize customImageRect=_customImageRect;
@property(nonatomic) _Bool useCustomRect; // @synthesize useCustomRect=_useCustomRect;
- (struct CGRect)imageRectForContentRect:(struct CGRect)arg1;
- (struct CGRect)titleRectForContentRect:(struct CGRect)arg1;

@end

