//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIPanGestureRecognizer.h>

@class NSString, UIView;
@protocol JUDragGestureRecognizerDelegate;

@interface JUDragGestureRecognizer : UIPanGestureRecognizer
{
    _Bool _shoudCheck;	// 8 = 0x8
    id <JUDragGestureRecognizerDelegate> _dragDelegate;	// 16 = 0x10
    UIView *_checkView1;	// 24 = 0x18
    UIView *_checkView2;	// 32 = 0x20
    struct CGPoint _point0;	// 40 = 0x28
}

@property(nonatomic) struct CGPoint point0; // @synthesize point0=_point0;
@property(nonatomic) _Bool shoudCheck; // @synthesize shoudCheck=_shoudCheck;
@property(nonatomic) __weak UIView *checkView2; // @synthesize checkView2=_checkView2;
@property(nonatomic) __weak UIView *checkView1; // @synthesize checkView1=_checkView1;
@property(nonatomic) __weak id <JUDragGestureRecognizerDelegate> dragDelegate; // @synthesize dragDelegate=_dragDelegate;
- (void).cxx_destruct;
- (void)handlePan:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

