//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface MMPTools : NSObject
{
}

+ (id)snapshot:(id)arg1;
+ (id)imageNamed:(id)arg1;
+ (id)imageViewWithImage:(id)arg1;
+ (id)imageWithColor:(id)arg1 size:(struct CGSize)arg2;
+ (double)floatWithHexStr:(id)arg1;
+ (id)colorWithHexStr:(id)arg1;
+ (double)sizeOfPixels:(long long)arg1;
+ (void)hideKeyboard;
+ (id)keyWindow;
+ (struct CGRect)screenRect;

@end

