//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDate.h>

@interface NSDate (TBSKDFormatString)
+ (id)dateFromString:(id)arg1 withFormat:(id)arg2 locale:(id)arg3;
+ (id)dateFromString:(id)arg1 withFormat:(id)arg2;
- (id)dateByAddingDays:(long long)arg1 months:(long long)arg2 years:(long long)arg3;
- (id)stringWithFormat:(id)arg1;
@end

