//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface NSObject (YMOptionsAndDefaults)
- (id)ym_optionOrDefaultForKey:(id)arg1;
- (void)ym_registerOptions:(id)arg1 defaults:(id)arg2;
@end

