//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NXASDisplayNodeViewProperties-Protocol.h"
#import "NXASDisplayProperties-Protocol.h"

@class CALayer, NSString, UIColor;

@interface NXASPendingState : NSObject <NXASDisplayNodeViewProperties, NXASDisplayProperties>
{
    unsigned long long autoresizingMask;	// 8 = 0x8
    unsigned int edgeAntialiasingMask;	// 16 = 0x10
    struct CGRect frame;	// 24 = 0x18
    struct CGRect bounds;	// 56 = 0x38
    struct CGColor *backgroundColor;	// 88 = 0x58
    struct CGColor *borderBottomColor;	// 96 = 0x60
    id contents;	// 104 = 0x68
    double alpha;	// 112 = 0x70
    double cornerRadius;	// 120 = 0x78
    long long contentMode;	// 128 = 0x80
    struct CGPoint anchorPoint;	// 136 = 0x88
    struct CGPoint position;	// 152 = 0x98
    double zPosition;	// 168 = 0xa8
    double contentsScale;	// 176 = 0xb0
    struct CATransform3D transform;	// 184 = 0xb8
    struct CATransform3D sublayerTransform;	// 312 = 0x138
    struct CGColor *shadowColor;	// 440 = 0x1b8
    double shadowOpacity;	// 448 = 0x1c0
    struct CGSize shadowOffset;	// 456 = 0x1c8
    double shadowRadius;	// 472 = 0x1d8
    double borderWidth;	// 480 = 0x1e0
    double borderBottomWidth;	// 488 = 0x1e8
    struct CGColor *borderColor;	// 496 = 0x1f0
    CALayer *borderBottomLayer;	// 504 = 0x1f8
    _Bool asyncTransactionContainer;	// 512 = 0x200
    _Bool isAccessibilityElement;	// 513 = 0x201
    NSString *accessibilityLabel;	// 520 = 0x208
    NSString *accessibilityHint;	// 528 = 0x210
    NSString *accessibilityValue;	// 536 = 0x218
    unsigned long long accessibilityTraits;	// 544 = 0x220
    struct CGRect accessibilityFrame;	// 552 = 0x228
    NSString *accessibilityLanguage;	// 584 = 0x248
    _Bool accessibilityElementsHidden;	// 592 = 0x250
    _Bool accessibilityViewIsModal;	// 593 = 0x251
    _Bool shouldGroupAccessibilityChildren;	// 594 = 0x252
    NSString *accessibilityIdentifier;	// 600 = 0x258
    struct {
        unsigned int needsDisplay:1;
        unsigned int needsLayout:1;
        unsigned int setClipsToBounds:1;
        unsigned int setOpaque:1;
        unsigned int setNeedsDisplayOnBoundsChange:1;
        unsigned int setAutoresizesSubviews:1;
        unsigned int setAutoresizingMask:1;
        unsigned int setFrame:1;
        unsigned int setBounds:1;
        unsigned int setBackgroundColor:1;
        unsigned int setBorderBottomColor:1;
        unsigned int setTintColor:1;
        unsigned int setContents:1;
        unsigned int setHidden:1;
        unsigned int setAlpha:1;
        unsigned int setCornerRadius:1;
        unsigned int setContentMode:1;
        unsigned int setNeedsDisplay:1;
        unsigned int setAnchorPoint:1;
        unsigned int setPosition:1;
        unsigned int setZPosition:1;
        unsigned int setContentsScale:1;
        unsigned int setTransform:1;
        unsigned int setSublayerTransform:1;
        unsigned int setUserInteractionEnabled:1;
        unsigned int setExclusiveTouch:1;
        unsigned int setShadowColor:1;
        unsigned int setShadowOpacity:1;
        unsigned int setShadowOffset:1;
        unsigned int setShadowRadius:1;
        unsigned int setBorderWidth:1;
        unsigned int setBorderColor:1;
        unsigned int setAsyncTransactionContainer:1;
        unsigned int setAllowsEdgeAntialiasing:1;
        unsigned int setEdgeAntialiasingMask:1;
        unsigned int setIsAccessibilityElement:1;
        unsigned int setAccessibilityLabel:1;
        unsigned int setAccessibilityHint:1;
        unsigned int setAccessibilityValue:1;
        unsigned int setAccessibilityTraits:1;
        unsigned int setAccessibilityFrame:1;
        unsigned int setAccessibilityLanguage:1;
        unsigned int setAccessibilityElementsHidden:1;
        unsigned int setAccessibilityViewIsModal:1;
        unsigned int setShouldGroupAccessibilityChildren:1;
        unsigned int setAccessibilityIdentifier:1;
    } _flags;	// 608 = 0x260
    _Bool clipsToBounds;	// 616 = 0x268
    _Bool opaque;	// 617 = 0x269
    _Bool isHidden;	// 618 = 0x26a
    _Bool needsDisplayOnBoundsChange;	// 619 = 0x26b
    _Bool allowsEdgeAntialiasing;	// 620 = 0x26c
    _Bool autoresizesSubviews;	// 621 = 0x26d
    _Bool userInteractionEnabled;	// 622 = 0x26e
    _Bool exclusiveTouch;	// 623 = 0x26f
    UIColor *tintColor;	// 624 = 0x270
}

+ (id)pendingViewStateFromView:(id)arg1;
+ (id)pendingViewStateFromLayer:(id)arg1;
@property(nonatomic, getter=nx_asyncdisplay_isAsyncTransactionContainer, setter=nx_asyncdisplay_setAsyncTransactionContainer:) _Bool nx_asyncdisplay_asyncTransactionContainer; // @synthesize nx_asyncdisplay_asyncTransactionContainer=asyncTransactionContainer;
@property(retain, nonatomic) struct CGColor *borderColor; // @synthesize borderColor;
@property(nonatomic) double borderWidth; // @synthesize borderWidth;
@property(nonatomic) double shadowRadius; // @synthesize shadowRadius;
@property(nonatomic) struct CGSize shadowOffset; // @synthesize shadowOffset;
@property(nonatomic) double shadowOpacity; // @synthesize shadowOpacity;
@property(retain, nonatomic) struct CGColor *shadowColor; // @synthesize shadowColor;
@property(nonatomic, getter=isExclusiveTouch) _Bool exclusiveTouch; // @synthesize exclusiveTouch;
@property(nonatomic, getter=isUserInteractionEnabled) _Bool userInteractionEnabled; // @synthesize userInteractionEnabled;
@property(nonatomic) struct CATransform3D sublayerTransform; // @synthesize sublayerTransform;
@property(nonatomic) struct CATransform3D transform; // @synthesize transform;
@property(nonatomic) double contentsScale; // @synthesize contentsScale;
@property(nonatomic) double zPosition; // @synthesize zPosition;
@property(nonatomic) struct CGPoint position; // @synthesize position;
@property(nonatomic) struct CGPoint anchorPoint; // @synthesize anchorPoint;
@property(nonatomic) long long contentMode; // @synthesize contentMode;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius;
@property(nonatomic) double alpha; // @synthesize alpha;
@property(retain, nonatomic) UIColor *tintColor; // @synthesize tintColor;
@property(nonatomic) unsigned long long autoresizingMask; // @synthesize autoresizingMask;
@property(nonatomic) _Bool autoresizesSubviews; // @synthesize autoresizesSubviews;
@property(nonatomic) unsigned int edgeAntialiasingMask; // @synthesize edgeAntialiasingMask;
@property(nonatomic) _Bool allowsEdgeAntialiasing; // @synthesize allowsEdgeAntialiasing;
@property(nonatomic) _Bool needsDisplayOnBoundsChange; // @synthesize needsDisplayOnBoundsChange;
@property(nonatomic, getter=isHidden) _Bool hidden; // @synthesize hidden=isHidden;
@property(retain, nonatomic) id contents; // @synthesize contents;
@property(nonatomic) struct CGRect bounds; // @synthesize bounds;
@property(nonatomic) struct CGRect frame; // @synthesize frame;
@property(nonatomic, getter=isOpaque) _Bool opaque; // @synthesize opaque;
@property(nonatomic) _Bool clipsToBounds; // @synthesize clipsToBounds;
- (void).cxx_destruct;
- (void)dealloc;
- (void)applyToView:(id)arg1;
- (void)applyToLayer:(id)arg1;
@property(copy, nonatomic) NSString *accessibilityIdentifier;
- (void)setShouldGroupAccessibilityChildren:(_Bool)arg1;
- (_Bool)shouldGroupAccessibilityChildren;
- (void)setAccessibilityViewIsModal:(_Bool)arg1;
- (_Bool)accessibilityViewIsModal;
- (void)setAccessibilityElementsHidden:(_Bool)arg1;
- (_Bool)accessibilityElementsHidden;
- (void)setAccessibilityLanguage:(id)arg1;
- (id)accessibilityLanguage;
- (void)setAccessibilityFrame:(struct CGRect)arg1;
- (struct CGRect)accessibilityFrame;
- (void)setAccessibilityTraits:(unsigned long long)arg1;
- (unsigned long long)accessibilityTraits;
- (void)setAccessibilityValue:(id)arg1;
- (id)accessibilityValue;
- (void)setAccessibilityHint:(id)arg1;
- (id)accessibilityHint;
- (void)setAccessibilityLabel:(id)arg1;
- (id)accessibilityLabel;
- (void)setIsAccessibilityElement:(_Bool)arg1;
- (_Bool)isAccessibilityElement;
@property(nonatomic) double borderBottomWidth;
@property(retain, nonatomic) struct CGColor *borderBottomColor;
@property(retain, nonatomic) struct CGColor *backgroundColor; // @synthesize backgroundColor;
- (void)setNeedsLayout;
- (void)setNeedsDisplay;
- (id)layer;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

