//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NXASLayoutablePrivate-Protocol.h"
#import "NXASStackLayoutable-Protocol.h"
#import "NXASStaticLayoutable-Protocol.h"

@class NXASLayout;

@protocol NXASLayoutable <NXASStackLayoutable, NXASStaticLayoutable, NXASLayoutablePrivate>
@property(nonatomic) struct CGPoint layoutPosition;
@property(nonatomic) CDStruct_32e40e3f sizeRange;
@property(nonatomic) double descender;
@property(nonatomic) double ascender;
@property(nonatomic) unsigned long long stackAlignSelf;
@property(nonatomic) CDStruct_5f1639cb flexBasis;
@property(nonatomic) _Bool flexShrink;
@property(nonatomic) _Bool flexGrow;
@property(nonatomic) double spacingAfter;
@property(nonatomic) double spacingBefore;
- (NXASLayout *)measureWithSizeRange:(CDStruct_42a63532)arg1;
@end

