//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NXControlNode.h"

@class NSArray, NSAttributedString, NSString, NXASHighlightOverlayLayer, NXASTextKitRenderer, UIColor, UILongPressGestureRecognizer;
@protocol NXASTextNodeDelegate;

@interface NXASTextNode : NXControlNode
{
    struct CGSize _shadowOffset;	// 328 = 0x148
    struct CGColor *_shadowColor;	// 344 = 0x158
    double _shadowOpacity;	// 352 = 0x160
    double _shadowRadius;	// 360 = 0x168
    NSArray *_exclusionPaths;	// 368 = 0x170
    NSAttributedString *_composedTruncationString;	// 376 = 0x178
    NSString *_highlightedLinkAttributeName;	// 384 = 0x180
    id _highlightedLinkAttributeValue;	// 392 = 0x188
    struct _NSRange _highlightRange;	// 400 = 0x190
    NXASHighlightOverlayLayer *_activeHighlightLayer;	// 416 = 0x1a0
    struct Mutex _rendererLock;	// 424 = 0x1a8
    struct CGSize _constrainedSize;	// 488 = 0x1e8
    NXASTextKitRenderer *_renderer;	// 504 = 0x1f8
    UILongPressGestureRecognizer *_longPressGestureRecognizer;	// 512 = 0x200
    _Bool _longPressCancelsTouches;	// 520 = 0x208
    _Bool _passthroughNonlinkTouches;	// 521 = 0x209
    NSAttributedString *_attributedString;	// 528 = 0x210
    NSAttributedString *_truncationAttributedString;	// 536 = 0x218
    NSAttributedString *_additionalTruncationMessage;	// 544 = 0x220
    long long _truncationMode;	// 552 = 0x228
    unsigned long long _maximumNumberOfLines;	// 560 = 0x230
    UIColor *_placeholderColor;	// 568 = 0x238
    NSArray *_linkAttributeNames;	// 576 = 0x240
    unsigned long long _highlightStyle;	// 584 = 0x248
    id <NXASTextNodeDelegate> _delegate;	// 592 = 0x250
    struct UIEdgeInsets _contentInsets;	// 600 = 0x258
    struct UIEdgeInsets _placeholderInsets;	// 632 = 0x278
}

+ (struct CGRect)_adjustRendererRect:(struct CGRect)arg1 forShadowPadding:(struct UIEdgeInsets)arg2;
+ (double)_highlightOpacityForStyle:(unsigned long long)arg1;
+ (struct CGColor *)_highlightColorForStyle:(unsigned long long)arg1;
+ (void)drawRect:(struct CGRect)arg1 withParameters:(id)arg2 isCancelled:(CDUnknownBlockType)arg3 isRasterizing:(_Bool)arg4;
@property(nonatomic) _Bool passthroughNonlinkTouches; // @synthesize passthroughNonlinkTouches=_passthroughNonlinkTouches;
@property(nonatomic) _Bool longPressCancelsTouches; // @synthesize longPressCancelsTouches=_longPressCancelsTouches;
@property(nonatomic) __weak id <NXASTextNodeDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned long long highlightStyle; // @synthesize highlightStyle=_highlightStyle;
@property(copy, nonatomic) NSArray *linkAttributeNames; // @synthesize linkAttributeNames=_linkAttributeNames;
@property(nonatomic) struct UIEdgeInsets placeholderInsets; // @synthesize placeholderInsets=_placeholderInsets;
@property(retain, nonatomic) UIColor *placeholderColor; // @synthesize placeholderColor=_placeholderColor;
@property(nonatomic) struct UIEdgeInsets contentInsets; // @synthesize contentInsets=_contentInsets;
@property(nonatomic) unsigned long long maximumNumberOfLines; // @synthesize maximumNumberOfLines=_maximumNumberOfLines;
@property(nonatomic) long long truncationMode; // @synthesize truncationMode=_truncationMode;
@property(copy, nonatomic) NSAttributedString *additionalTruncationMessage; // @synthesize additionalTruncationMessage=_additionalTruncationMessage;
@property(copy, nonatomic) NSAttributedString *truncationAttributedString; // @synthesize truncationAttributedString=_truncationAttributedString;
@property(copy, nonatomic) NSAttributedString *attributedString; // @synthesize attributedString=_attributedString;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)_prepareTruncationStringForDrawing:(id)arg1;
- (id)_composedTruncationString;
- (struct _NSRange)_additionalTruncationMessageRangeWithVisibleRange:(struct _NSRange)arg1;
- (void)_invalidateTruncationString;
@property(readonly, nonatomic) unsigned long long lineCount;
@property(readonly, nonatomic, getter=isTruncated) _Bool truncated;
@property(readonly, nonatomic) struct UIEdgeInsets shadowPadding;
- (void)setShadowRadius:(double)arg1;
- (double)shadowRadius;
- (void)setShadowOpacity:(double)arg1;
- (double)shadowOpacity;
- (void)setShadowOffset:(struct CGSize)arg1;
- (struct CGSize)shadowOffset;
- (void)setShadowColor:(struct CGColor *)arg1;
- (struct CGColor *)shadowColor;
- (_Bool)_pendingTruncationTap;
- (_Bool)_pendingLinkTap;
- (void)_handleLongPress:(id)arg1;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)placeholderImage;
- (struct CGRect)frameForTextRange:(struct _NSRange)arg1;
- (struct CGRect)trailingRect;
- (id)highlightRectsForTextRange:(struct _NSRange)arg1;
- (id)rectsForTextRange:(struct _NSRange)arg1;
- (id)_rectsForTextRange:(struct _NSRange)arg1 measureOption:(unsigned long long)arg2;
- (void)_clearHighlightIfNecessary;
- (void)_setHighlightRange:(struct _NSRange)arg1 forAttributeName:(id)arg2 value:(id)arg3 animated:(_Bool)arg4;
- (void)setHighlightRange:(struct _NSRange)arg1 animated:(_Bool)arg2;
@property(nonatomic) struct _NSRange highlightRange;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)_linkAttributeValueAtPoint:(struct CGPoint)arg1 attributeName:(out id *)arg2 range:(out struct _NSRange *)arg3 inAdditionalTruncationMessage:(out _Bool *)arg4 forHighlighting:(_Bool)arg5;
- (id)linkAttributeValueAtPoint:(struct CGPoint)arg1 attributeName:(out id *)arg2 range:(out struct _NSRange *)arg3;
- (id)drawParametersForAsyncLayer:(id)arg1;
@property(retain, nonatomic) NSArray *exclusionPaths;
- (void)_invalidateRenderer;
- (struct NXASTextKitAttributes)_rendererAttributes;
- (id)_renderer;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)didLoad;
- (void)clearContents;
- (void)displayDidFinish;
- (struct CGSize)calculateSizeThatFits:(struct CGSize)arg1;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (id)initWithViewBlock:(CDUnknownBlockType)arg1 didLoadBlock:(CDUnknownBlockType)arg2;
- (id)initWithLayerBlock:(CDUnknownBlockType)arg1 didLoadBlock:(CDUnknownBlockType)arg2;
- (void)fillInitialProperties;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool placeholderEnabled; // @dynamic placeholderEnabled;
@property(readonly) Class superclass;

@end

