//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PDCommandDelegate-Protocol.h"

@class NSNumber, NSString, PDIndexedDBDomain, PDIndexedDBKeyRange;

@protocol PDIndexedDBCommandDelegate <PDCommandDelegate>

@optional
- (void)domain:(PDIndexedDBDomain *)arg1 requestDataWithRequestId:(NSNumber *)arg2 frameId:(NSString *)arg3 databaseName:(NSString *)arg4 objectStoreName:(NSString *)arg5 indexName:(NSString *)arg6 skipCount:(NSNumber *)arg7 pageSize:(NSNumber *)arg8 keyRange:(PDIndexedDBKeyRange *)arg9 callback:(void (^)(id))arg10;
- (void)domain:(PDIndexedDBDomain *)arg1 requestDatabaseWithRequestId:(NSNumber *)arg2 frameId:(NSString *)arg3 databaseName:(NSString *)arg4 callback:(void (^)(id))arg5;
- (void)domain:(PDIndexedDBDomain *)arg1 requestDatabaseNamesForFrameWithRequestId:(NSNumber *)arg2 frameId:(NSString *)arg3 callback:(void (^)(id))arg4;
- (void)domain:(PDIndexedDBDomain *)arg1 disableWithCallback:(void (^)(id))arg2;
- (void)domain:(PDIndexedDBDomain *)arg1 enableWithCallback:(void (^)(id))arg2;
@end

