//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDate, NSString;

@interface PLCrashReportProcessInfo : NSObject
{
    NSString *_processName;	// 8 = 0x8
    unsigned long long _processID;	// 16 = 0x10
    NSString *_processPath;	// 24 = 0x18
    NSDate *_processStartTime;	// 32 = 0x20
    NSString *_parentProcessName;	// 40 = 0x28
    unsigned long long _parentProcessID;	// 48 = 0x30
    _Bool _native;	// 56 = 0x38
}

@property(readonly, nonatomic) _Bool native; // @synthesize native=_native;
@property(readonly, nonatomic) unsigned long long parentProcessID; // @synthesize parentProcessID=_parentProcessID;
@property(readonly, nonatomic) NSString *parentProcessName; // @synthesize parentProcessName=_parentProcessName;
@property(readonly, nonatomic) NSDate *processStartTime; // @synthesize processStartTime=_processStartTime;
@property(readonly, nonatomic) NSString *processPath; // @synthesize processPath=_processPath;
@property(readonly, nonatomic) unsigned long long processID; // @synthesize processID=_processID;
@property(readonly, nonatomic) NSString *processName; // @synthesize processName=_processName;
- (void)dealloc;
- (id)initWithProcessName:(id)arg1 processID:(unsigned long long)arg2 processPath:(id)arg3 processStartTime:(id)arg4 parentProcessName:(id)arg5 parentProcessID:(unsigned long long)arg6 native:(_Bool)arg7;

@end

