//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, UIImage;
@protocol RPPreviewPhotoControllerDelegate;

@interface RPPreviewPhotoController : UIViewController
{
    _Bool _isEnd;	// 8 = 0x8
    UIImage *_previewImage;	// 16 = 0x10
    id <RPPreviewPhotoControllerDelegate> _delegate;	// 24 = 0x18
}

@property(nonatomic) __weak id <RPPreviewPhotoControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isEnd; // @synthesize isEnd=_isEnd;
@property(retain, nonatomic) UIImage *previewImage; // @synthesize previewImage=_previewImage;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showAlertView;
- (void)exitController:(int)arg1;
- (void)onOkButtonPressed:(id)arg1;
- (void)onAgainButtonPressed:(id)arg1;
- (void)setupView;
- (_Bool)prefersStatusBarHidden;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

