//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray;
@protocol SearchReusableViewData;

@protocol SearchSectionViewData <NSObject>
@property(retain, nonatomic) NSArray *cellDatas;
@property(retain, nonatomic) id <SearchReusableViewData> footerData;
@property(retain, nonatomic) id <SearchReusableViewData> headerData;
@end

