//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface TaffyStringUtil : NSObject
{
}

+ (struct CGSize)getAttrTextSize:(id)arg1 withConstrainedSize:(struct CGSize)arg2 withOptions:(long long)arg3;
+ (struct CGSize)getAttrTextSize:(id)arg1 withConstrainedSize:(struct CGSize)arg2;
+ (struct CGSize)getTextSize:(id)arg1 withFont:(id)arg2 withConstrainedSize:(struct CGSize)arg3 withOptions:(long long)arg4;
+ (struct CGSize)getTextSize:(id)arg1 withFont:(id)arg2 withConstrainedSize:(struct CGSize)arg3;
+ (id)split:(id)arg1 withDelimit:(id)arg2;
+ (id)join:(id)arg1 withDelimit:(id)arg2;
+ (id)join:(id)arg1 withOther:(id)arg2;
+ (id)trim:(id)arg1;
+ (_Bool)isNotBlank:(id)arg1;
+ (_Bool)isBlank:(id)arg1;
+ (_Bool)isNotEmpty:(id)arg1;
+ (_Bool)isEmpty:(id)arg1;

@end

