//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface TBAccsManagerCenter : NSObject
{
    struct _opaque_pthread_rwlock_t lock;	// 8 = 0x8
    NSMutableDictionary *_accsManagerDict;	// 208 = 0xd0
}

+ (id)shareInstance;
@property(readonly) NSMutableDictionary *accsManagerDict; // @synthesize accsManagerDict=_accsManagerDict;
- (void).cxx_destruct;
- (id)getAccsManagerByHost:(id)arg1;
- (void)addAccsManager:(id)arg1;
- (id)init;

@end

