//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "AccsProtocol-Protocol.h"

@class NSString, TBAccsConfiguration, TBAccsReceiveAndCallBackCenter, TBAccsRequestQueue;

@interface TBAccsManager : NSObject <AccsProtocol>
{
    _Bool _userCustomHost;	// 8 = 0x8
    TBAccsReceiveAndCallBackCenter *_accsReceiveAndCallBackCenter;	// 16 = 0x10
    TBAccsRequestQueue *_accsRequestQueue;	// 24 = 0x18
    NSString *_host;	// 32 = 0x20
    TBAccsConfiguration *_configuration;	// 40 = 0x28
}

+ (id)responseDataabnormal:(id)arg1 serviceID:(id)arg2 parameters:(id)arg3;
+ (_Bool)isChannelError:(int)arg1 extP:(id)arg2;
+ (id)accsManagerByHost:(id)arg1;
+ (id)centerAccsManager;
+ (void)initialize;
@property(nonatomic) _Bool userCustomHost; // @synthesize userCustomHost=_userCustomHost;
@property(readonly, nonatomic) TBAccsConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) NSString *host; // @synthesize host=_host;
@property(readonly, nonatomic) TBAccsRequestQueue *accsRequestQueue; // @synthesize accsRequestQueue=_accsRequestQueue;
@property(readonly, nonatomic) TBAccsReceiveAndCallBackCenter *accsReceiveAndCallBackCenter; // @synthesize accsReceiveAndCallBackCenter=_accsReceiveAndCallBackCenter;
- (void).cxx_destruct;
- (void)serverRealUNBindServiceID:(id)arg1 callBack:(CDUnknownBlockType)arg2;
- (void)serverRealBindServiceID:(id)arg1 callBack:(CDUnknownBlockType)arg2;
- (void)cancelRequestByDataID:(id)arg1;
- (_Bool)checkServiceID:(id)arg1 callBack:(CDUnknownBlockType)arg2 error:(id *)arg3;
- (_Bool)checkNetwork:(CDUnknownBlockType)arg1 error:(id *)arg2;
- (id)sendRequestWithContext:(id)arg1 error:(id *)arg2;
- (id)sendRequestWithData:(id)arg1 serviceId:(id)arg2 userId:(id)arg3 routID:(id)arg4 otherParameters:(id)arg5 callBack:(CDUnknownBlockType)arg6 error:(id *)arg7;
- (id)sendRequestWithData:(id)arg1 serviceId:(id)arg2 userId:(id)arg3 routID:(id)arg4 otherParameters:(id)arg5 callBack:(CDUnknownBlockType)arg6;
- (void)unbindServiceWithServiceId:(id)arg1 callBack:(CDUnknownBlockType)arg2;
- (void)bindServiceWithServiceId:(id)arg1 callBack:(CDUnknownBlockType)arg2 receviceDataBlock:(CDUnknownBlockType)arg3;
- (void)unbindUserWithUserId:(id)arg1 callBack:(CDUnknownBlockType)arg2;
- (void)bindUserWithUserId:(id)arg1 callBack:(CDUnknownBlockType)arg2;
- (void)unbindAppWithResultsBlock:(CDUnknownBlockType)arg1;
- (void)bindAppWithAppleToken:(id)arg1 callBack:(CDUnknownBlockType)arg2;
@property(readonly, nonatomic) _Bool canRequest;
- (void)startAccs;
- (id)initWithHost:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

