//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface TBAddressBookMessageAvatarModel : NSObject
{
    NSString *_remarkName;	// 8 = 0x8
    NSString *_avatarUrlString;	// 16 = 0x10
    NSString *_name;	// 24 = 0x18
    NSString *_phone;	// 32 = 0x20
    NSString *_userId;	// 40 = 0x28
    long long _contactStatus;	// 48 = 0x30
}

@property(nonatomic) long long contactStatus; // @synthesize contactStatus=_contactStatus;
@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(retain, nonatomic) NSString *phone; // @synthesize phone=_phone;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *avatarUrlString; // @synthesize avatarUrlString=_avatarUrlString;
@property(retain, nonatomic) NSString *remarkName; // @synthesize remarkName=_remarkName;
- (void).cxx_destruct;

@end

