//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UISearchBar.h>

@interface TBAddressBookSearchBar : UISearchBar
{
    _Bool _needsConstraints;	// 8 = 0x8
}

@property(nonatomic) _Bool needsConstraints; // @synthesize needsConstraints=_needsConstraints;
- (void)modifyCancelButtonWithStatue:(_Bool)arg1;
- (void)layoutSubviews;

@end

