//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBAMPMessage.h"

@class NSDictionary, NSString;

@interface TBAMPShareMessage : TBAMPMessage
{
    NSString *_title;	// 8 = 0x8
    NSString *_picUrl;	// 16 = 0x10
    double _price;	// 24 = 0x18
    NSString *_actionUrl;	// 32 = 0x20
    NSString *_shareId;	// 40 = 0x28
    NSDictionary *_est;	// 48 = 0x30
    NSString *_shopLevelImageUrl;	// 56 = 0x38
}

@property(copy, nonatomic) NSString *shopLevelImageUrl; // @synthesize shopLevelImageUrl=_shopLevelImageUrl;
@property(copy, nonatomic) NSDictionary *est; // @synthesize est=_est;
@property(copy, nonatomic) NSString *shareId; // @synthesize shareId=_shareId;
@property(copy, nonatomic) NSString *actionUrl; // @synthesize actionUrl=_actionUrl;
@property(nonatomic) double price; // @synthesize price=_price;
@property(copy, nonatomic) NSString *picUrl; // @synthesize picUrl=_picUrl;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)parseFromDict:(id)arg1;
- (void)loadFromCoreDataMessage:(id)arg1;
- (void)copyToCoreDataMessage:(id)arg1;
- (void)loadDataWithMessage:(id)arg1;
- (id)ampDeepCopy;
- (id)initWithMessage:(id)arg1;
- (id)initWithJson:(id)arg1;
- (id)toDictionary;
- (id)init;

@end

