//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface TBAMPGroupQRCodeInfo : NSObject
{
    NSString *_code;	// 8 = 0x8
    NSString *_codeKey;	// 16 = 0x10
    NSString *_type;	// 24 = 0x18
    NSString *_expiredTime;	// 32 = 0x20
}

@property(retain, nonatomic) NSString *expiredTime; // @synthesize expiredTime=_expiredTime;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *codeKey; // @synthesize codeKey=_codeKey;
@property(retain, nonatomic) NSString *code; // @synthesize code=_code;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

