//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AMPDeepCopyObject-Protocol.h"
#import "NSObject-Protocol.h"

@class NSDate, NSDictionary, NSString;
@protocol TBAMPMobileContact;

@protocol TBAMPMobileContact <NSObject, AMPDeepCopyObject>
@property(copy, nonatomic) NSDate *lastModifiedDate;
@property(nonatomic) long long secNum;
@property(copy, nonatomic) NSString *pinyin;
@property(copy, nonatomic) NSString *phone;
@property(copy, nonatomic) NSString *name;
- (NSDictionary *)toJSONWithOperationType:(long long)arg1;
- (id)initWithMobileContact:(id <TBAMPMobileContact>)arg1;
@end

