//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBAppAction.h"

@class NSString;

@interface TBAppNavigationAction : TBAppAction
{
    NSString *_taokeFlag;	// 24 = 0x18
    NSString *_taokeType;	// 32 = 0x20
    NSString *_url;	// 40 = 0x28
}

@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *taokeType; // @synthesize taokeType=_taokeType;
@property(retain, nonatomic) NSString *taokeFlag; // @synthesize taokeFlag=_taokeFlag;
- (void).cxx_destruct;
- (void)runWithApp:(id)arg1;
- (id)runForURLRequest:(id)arg1 app:(id)arg2;
- (id)initWithResponseDict:(id)arg1 localDict:(id)arg2;

@end

