//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBPSAdapterViewController.h"

#import "TBPSAVCaptureViewControllerDelegate-Protocol.h"
#import "TBPSCaptureScanManagerDelegate-Protocol.h"
#import "TBPSImagePickerViewControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSMutableArray, NSString, NSURL, TBAVCaptureTipView, TBPSAVCaptureViewController, TBPSCaptureScanManager, UIButton, UIImageView, UILabel, UIPanGestureRecognizer, UIView, UIViewController;

@interface TBAVCaptureViewController : TBPSAdapterViewController <TBPSAVCaptureViewControllerDelegate, TBPSImagePickerViewControllerDelegate, UINavigationControllerDelegate, UIScrollViewDelegate, TBPSCaptureScanManagerDelegate>
{
    _Bool _isShowFrontCamera;	// 40 = 0x28
    UIView *_buttonView;	// 48 = 0x30
    UIImageView *_arrowView;	// 56 = 0x38
    UIImageView *_buttonBackView;	// 64 = 0x40
    UIButton *_btnPhotoLibrary;	// 72 = 0x48
    UIButton *_btnCamera;	// 80 = 0x50
    TBAVCaptureTipView *_captureTipView;	// 88 = 0x58
    UIButton *_btnCaptureTipView;	// 96 = 0x60
    UILabel *_refreshLabel;	// 104 = 0x68
    NSURL *_loadURL;	// 112 = 0x70
    NSMutableArray *_layerArray;	// 120 = 0x78
    _Bool _isOnlyShowCapture;	// 128 = 0x80
    UIViewController *_navController;	// 136 = 0x88
    _Bool _isScanning;	// 144 = 0x90
    _Bool _isShowHomePage;	// 145 = 0x91
    TBPSAVCaptureViewController *_captureViewController;	// 152 = 0x98
    UIPanGestureRecognizer *_panGesture;	// 160 = 0xa0
    double _offset;	// 168 = 0xa8
    TBPSCaptureScanManager *_captureScanManager;	// 176 = 0xb0
}

@property(retain, nonatomic) TBPSCaptureScanManager *captureScanManager; // @synthesize captureScanManager=_captureScanManager;
@property(nonatomic) double offset; // @synthesize offset=_offset;
@property(retain, nonatomic) UIPanGestureRecognizer *panGesture; // @synthesize panGesture=_panGesture;
@property(retain, nonatomic) TBPSAVCaptureViewController *captureViewController; // @synthesize captureViewController=_captureViewController;
@property(nonatomic) _Bool isOnlyShowCapture; // @synthesize isOnlyShowCapture=_isOnlyShowCapture;
@property(retain, nonatomic) UIButton *btnPhotoLibrary; // @synthesize btnPhotoLibrary=_btnPhotoLibrary;
@property(retain, nonatomic) UIButton *btnCamera; // @synthesize btnCamera=_btnCamera;
@property(retain, nonatomic) UIImageView *buttonBackView; // @synthesize buttonBackView=_buttonBackView;
@property(nonatomic) _Bool isShowHomePage; // @synthesize isShowHomePage=_isShowHomePage;
@property(retain, nonatomic) NSURL *loadURL; // @synthesize loadURL=_loadURL;
@property(nonatomic) _Bool isScanning; // @synthesize isScanning=_isScanning;
@property(nonatomic) _Bool isShowFrontCamera; // @synthesize isShowFrontCamera=_isShowFrontCamera;
- (void).cxx_destruct;
- (void)scanAfterBecomeActive:(id)arg1;
- (void)showUserGuide:(id)arg1;
- (void)starsFlicker;
- (void)TBOpenURL:(id)arg1;
- (void)clickedCapture:(id)arg1;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)capture:(id)arg1;
- (void)resizeAsyncImage:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)searchWithImage:(id)arg1 from:(id)arg2 metaInfo:(id)arg3;
- (void)layoutSubviews;
- (void)didReceiveMemoryWarning;
- (void)backViewController:(id)arg1;
- (void)backItemClicked:(id)arg1;
- (void)browsePhotoLibrary;
- (void)browsePhoto:(id)arg1;
- (_Bool)forbidbackPanGestureRecognized;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)dealloc;
- (void)viewDidUnload;
- (void)scanPhotoCapture;
- (void)showImageAsset:(id)arg1;
- (void)dissmissCapture;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)setParamURLArgs:(id)arg1;
- (id)initWithNavigatorURL:(id)arg1 query:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

