//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBBuyBaseEventHandler.h"

@interface TBBuyChangeAddressHandler : TBBuyBaseEventHandler
{
    id _addrOpaqueData;	// 8 = 0x8
}

+ (id)eventTag;
@property(retain, nonatomic) id addrOpaqueData; // @synthesize addrOpaqueData=_addrOpaqueData;
- (void).cxx_destruct;
- (void)handleEvent:(id)arg1;

@end

