//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString;

@protocol TBBuyQueryProtocol <NSObject>
- (void)cancel;
- (void)queryWithApiName:(NSString *)arg1 version:(NSString *)arg2 domain:(NSString *)arg3 params:(NSDictionary *)arg4 successBlock:(void (^)(NSString *, NSDictionary *))arg5 failureBlock:(void (^)(NSString *, NSString *, NSString *, NSDictionary *))arg6 extra:(NSDictionary *)arg7;
@end

