//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSIndexPath, NSMutableArray, UITableView, UITableViewCell;

@protocol TBCartUIInterceptorProtocol <NSObject>
- (void)tableView:(UITableView *)arg1 didSelectRowAtIndexPath:(NSIndexPath *)arg2;
- (UITableViewCell *)tableView:(UITableView *)arg1 cellForRowAtIndexPath:(NSIndexPath *)arg2;
- (double)tableView:(UITableView *)arg1 heightForRowAtIndexPath:(NSIndexPath *)arg2;
- (long long)tableView:(UITableView *)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(UITableView *)arg1;
- (unsigned long long)cartSectionStartIndexWithNeedLength:(unsigned long long)arg1;
- (_Bool)hasAdditionalData;
- (_Bool)isNeedShowAdditionalData;

@optional
- (void)interceptorDidNeedClean;
- (void)cartQueryEndPageDataSuccess;
- (void)cartQueryData;
- (NSMutableArray *)customizedBodyViewModelsWithOrigin:(NSMutableArray *)arg1;
- (NSDictionary *)customViewModelToViewRelationKeyMap;
- (void)setContext:(id)arg1;
@end

