//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class TBCalendarResponse;

@interface TBCalendarMTOPResult : NSObject
{
    _Bool _success;	// 8 = 0x8
    TBCalendarResponse *_response;	// 16 = 0x10
    id _responseJSON;	// 24 = 0x18
}

@property(retain) id responseJSON; // @synthesize responseJSON=_responseJSON;
@property(retain) TBCalendarResponse *response; // @synthesize response=_response;
@property(nonatomic) _Bool success; // @synthesize success=_success;
- (void).cxx_destruct;

@end

