//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSString;

@interface TBCartFooterCheckAllComponent : NSObject
{
    _Bool _checked;	// 8 = 0x8
    NSMutableDictionary *_data;	// 16 = 0x10
}

@property(retain, nonatomic) NSMutableDictionary *data; // @synthesize data=_data;
- (void).cxx_destruct;
@property(nonatomic, getter=isEditable) _Bool editable;
@property(retain, nonatomic) NSString *title;
@property(nonatomic, getter=isChecked) _Bool checked;
- (id)initWithData:(id)arg1;

@end

