//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "TBCartDataComponent-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString;
@protocol TBCartDataComponent;

@interface TBCartDataComponent : NSObject <TBCartDataComponent>
{
    NSMutableDictionary *_data;	// 8 = 0x8
    NSMutableDictionary *_origin;	// 16 = 0x10
    NSMutableArray *_children;	// 24 = 0x18
    id <TBCartDataComponent> _parent;	// 32 = 0x20
    NSString *_ckey;	// 40 = 0x28
}

@property(retain, nonatomic) NSString *ckey; // @synthesize ckey=_ckey;
@property(nonatomic) __weak id <TBCartDataComponent> parent; // @synthesize parent=_parent;
@property(retain, nonatomic) NSMutableArray *children; // @synthesize children=_children;
@property(retain, nonatomic) NSMutableDictionary *origin; // @synthesize origin=_origin;
@property(retain, nonatomic) NSMutableDictionary *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (void)recalculateCheck;
- (_Bool)isEditing;
- (void)setEditing:(_Bool)arg1;
- (_Bool)isCheckAll;
- (void)checkAll:(_Bool)arg1;
- (void)notifyCheck:(_Bool)arg1;
- (void)clearAllChildren;
- (void)removeChild:(id)arg1;
- (void)addChild:(id)arg1;
@property(retain, nonatomic) NSString *tag;
@property(retain, nonatomic) NSString *cid;
@property(retain, nonatomic) NSMutableDictionary *fields;
@property(nonatomic) _Bool editable;
@property(readonly, copy) NSString *description;
- (id)initWithData:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

