//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBJSONModel.h"

@class NSArray, NSString;

@interface TBComboItem : TBJSONModel
{
    NSString *_mealId;	// 8 = 0x8
    NSString *_mealName;	// 16 = 0x10
    NSString *_mealPrice;	// 24 = 0x18
    NSString *_savedMoney;	// 32 = 0x20
    NSString *_buyCount;	// 40 = 0x28
    NSArray *_itemList;	// 48 = 0x30
    NSArray *_mealIdList;	// 56 = 0x38
}

+ (id)modelWithJSONDictionary:(id)arg1;
@property(retain, nonatomic) NSArray *mealIdList; // @synthesize mealIdList=_mealIdList;
@property(retain, nonatomic) NSArray *itemList; // @synthesize itemList=_itemList;
@property(retain, nonatomic) NSString *buyCount; // @synthesize buyCount=_buyCount;
@property(retain, nonatomic) NSString *savedMoney; // @synthesize savedMoney=_savedMoney;
@property(retain, nonatomic) NSString *mealPrice; // @synthesize mealPrice=_mealPrice;
@property(retain, nonatomic) NSString *mealName; // @synthesize mealName=_mealName;
@property(retain, nonatomic) NSString *mealId; // @synthesize mealId=_mealId;
- (void).cxx_destruct;
- (id)toDictionary;

@end

