//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBExtBuyBaseCell.h"

@class TBTradeInstallmentPickerModel, UILabel;

@interface TBExtBuyInstallmentPickerCell : TBExtBuyBaseCell
{
    UILabel *_titleLabel;	// 8 = 0x8
    UILabel *_descLabel;	// 16 = 0x10
    TBTradeInstallmentPickerModel *_model;	// 24 = 0x18
}

+ (double)cellHeight:(id)arg1 withCellWidth:(double)arg2;
@property(nonatomic) __weak TBTradeInstallmentPickerModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)cellDidSelected;
- (void)bindData:(id)arg1;
- (void)layoutSubviews;
- (void)initCell;

@end

