//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface TBHTPageTrackInfo : NSObject
{
    NSString *_name;	// 8 = 0x8
    double _prepare;	// 16 = 0x10
    double _network;	// 24 = 0x18
    double _render;	// 32 = 0x20
    double _cache;	// 40 = 0x28
    double _allCost;	// 48 = 0x30
}

@property(nonatomic) double allCost; // @synthesize allCost=_allCost;
@property(nonatomic) double cache; // @synthesize cache=_cache;
@property(nonatomic) double render; // @synthesize render=_render;
@property(nonatomic) double network; // @synthesize network=_network;
@property(nonatomic) double prepare; // @synthesize prepare=_prepare;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)description;

@end

