//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSURL, UITableViewCell, UIView;
@protocol TBIMChatCell, TBIMMessageAdapter;

@protocol TBIMChatCellDelegate <NSObject>

@optional
- (void)messageViewCell:(UITableViewCell<TBIMChatCell> *)arg1 urlDidTapped:(NSURL *)arg2;
- (void)messageViewCell:(UITableViewCell<TBIMChatCell> *)arg1 needBindSPMView:(UIView *)arg2 chatCellSPMType:(unsigned long long)arg3;
- (void)messageViewCell:(UITableViewCell<TBIMChatCell> *)arg1 collectDidTapped:(id <TBIMMessageAdapter>)arg2;
- (void)messageViewCell:(UITableViewCell<TBIMChatCell> *)arg1 updateCollectStatus:(id <TBIMMessageAdapter>)arg2;
- (void)messageViewCell:(UITableViewCell<TBIMChatCell> *)arg1 likeDidTapped:(id <TBIMMessageAdapter>)arg2;
- (void)messageViewCell:(UITableViewCell<TBIMChatCell> *)arg1 itemLinkDidTapped:(id <TBIMMessageAdapter>)arg2;
- (void)messageViewCell:(UITableViewCell<TBIMChatCell> *)arg1 cellDidTapped:(id <TBIMMessageAdapter>)arg2;
- (void)messageViewCell:(UITableViewCell<TBIMChatCell> *)arg1 headImageDidTapped:(id <TBIMMessageAdapter>)arg2;
- (void)messageViewCell:(UITableViewCell<TBIMChatCell> *)arg1 bubbleDidLongTapped:(id <TBIMMessageAdapter>)arg2;
- (void)messageViewCell:(UITableViewCell<TBIMChatCell> *)arg1 bubbleDidTapped:(id)arg2;
- (void)messageViewCell:(UITableViewCell<TBIMChatCell> *)arg1 reSendIMMessage:(id <TBIMMessageAdapter>)arg2;
- (void)messageViewCell:(UITableViewCell<TBIMChatCell> *)arg1 forwardingIMMessage:(id <TBIMMessageAdapter>)arg2;
- (void)messageViewCell:(UITableViewCell<TBIMChatCell> *)arg1 deleteIMMessage:(id <TBIMMessageAdapter>)arg2;
- (void)messageViewCell:(UITableViewCell<TBIMChatCell> *)arg1 copyIMMessage:(id <TBIMMessageAdapter>)arg2;
@end

