//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSString, UIButton, UIImageView, UILabel, UIView;
@protocol TBIMShareCellDelegate;

@interface TBIMShareViewCell : UITableViewCell
{
    _Bool _bHaveCheckButton;	// 8 = 0x8
    UIButton *_checkButton;	// 16 = 0x10
    UIImageView *_avatarImageView;	// 24 = 0x18
    UILabel *_titleLabel;	// 32 = 0x20
    UIView *_bottomLineView;	// 40 = 0x28
    NSString *_url;	// 48 = 0x30
    id <TBIMShareCellDelegate> _delegate;	// 56 = 0x38
}

@property(nonatomic) __weak id <TBIMShareCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool bHaveCheckButton; // @synthesize bHaveCheckButton=_bHaveCheckButton;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) UIView *bottomLineView; // @synthesize bottomLineView=_bottomLineView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) UIButton *checkButton; // @synthesize checkButton=_checkButton;
- (void).cxx_destruct;
- (void)updateCellWithData:(id)arg1;
- (void)showCheckButton:(_Bool)arg1;
- (void)layoutWithCheckButton:(_Bool)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

