//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel;
@protocol TBIMUserAdapter;

@interface TBIMOfficeUserCell : UITableViewCell
{
    UILabel *_titleLabel;	// 8 = 0x8
    UILabel *_contentLabel;	// 16 = 0x10
    UILabel *_notifyIcon;	// 24 = 0x18
    UIImageView *_headImageView;	// 32 = 0x20
    id <TBIMUserAdapter> _imUser;	// 40 = 0x28
    _Bool _isRemind;	// 48 = 0x30
}

+ (double)heightForCell;
- (void).cxx_destruct;
- (void)didTransitionToState:(unsigned long long)arg1;
- (id)getAllSubview:(id)arg1;
- (void)setUserInfo:(id)arg1 isRemind:(_Bool)arg2;
- (void)prepareForReuse;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

