//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UILabel;

@interface TBIMMoblieContactsFriendsProfileView : UIView
{
    unsigned long long _miniMumFriendsNumber;	// 8 = 0x8
    NSArray *_friendsInContacts;	// 16 = 0x10
    UILabel *_totalFriendsNumberHintLabel;	// 24 = 0x18
    UILabel *_addFriendHintLabel;	// 32 = 0x20
    double _avatorGapWidth;	// 40 = 0x28
}

@property(nonatomic) double avatorGapWidth; // @synthesize avatorGapWidth=_avatorGapWidth;
@property(retain, nonatomic) UILabel *addFriendHintLabel; // @synthesize addFriendHintLabel=_addFriendHintLabel;
@property(retain, nonatomic) UILabel *totalFriendsNumberHintLabel; // @synthesize totalFriendsNumberHintLabel=_totalFriendsNumberHintLabel;
@property(retain, nonatomic) NSArray *friendsInContacts; // @synthesize friendsInContacts=_friendsInContacts;
@property(nonatomic) unsigned long long miniMumFriendsNumber; // @synthesize miniMumFriendsNumber=_miniMumFriendsNumber;
- (void).cxx_destruct;
- (id)friendAvatorViewAtIndex:(unsigned long long)arg1;
- (id)initWithMiniMumFriendsNumber:(unsigned long long)arg1 friendsInContact:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

