//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBJSONModel.h"

@class NSArray, NSDictionary, NSString, TBLiveBroadCasterAccountInfo;
@protocol TBLiveConventionModel, TBLiveDetailProductItemModel, TBLiveURLItemModel;

@interface TBLiveDetailInfoModel : TBJSONModel
{
    NSString *_feedId;	// 8 = 0x8
    NSString *_channelId;	// 16 = 0x10
    NSString *_type;	// 24 = 0x18
    NSString *_status;	// 32 = 0x20
    NSString *_bizStatus;	// 40 = 0x28
    NSString *_title;	// 48 = 0x30
    NSString *_inputStreamUrl;	// 56 = 0x38
    NSString *_coverImg;	// 64 = 0x40
    NSString *_liveUrl;	// 72 = 0x48
    NSString *_liveUrlHls;	// 80 = 0x50
    NSArray<TBLiveURLItemModel> *_liveUrlList;	// 88 = 0x58
    NSArray<TBLiveConventionModel> *_conventionList;	// 96 = 0x60
    NSString *_replayUrl;	// 104 = 0x68
    NSString *_location;	// 112 = 0x70
    NSString *_groupChatNum;	// 120 = 0x78
    NSString *_timeLength;	// 128 = 0x80
    NSString *_startTime;	// 136 = 0x88
    NSString *_endTime;	// 144 = 0x90
    NSString *_endPushStreamTime;	// 152 = 0x98
    NSString *_joinCount;	// 160 = 0xa0
    NSString *_totalJoinCount;	// 168 = 0xa8
    NSString *_parseCount;	// 176 = 0xb0
    NSString *_accountId;	// 184 = 0xb8
    NSString *_nativeFeedDetailUrl;	// 192 = 0xc0
    TBLiveBroadCasterAccountInfo *_broadCaster;	// 200 = 0xc8
    NSString *_appointmentTime;	// 208 = 0xd0
    NSString *_isPlayerLow;	// 216 = 0xd8
    NSString *_inputCodeLevel;	// 224 = 0xe0
    NSString *_roomNum;	// 232 = 0xe8
    NSArray<TBLiveDetailProductItemModel> *_itemList;	// 240 = 0xf0
    NSString *_popupWindowUrl;	// 248 = 0xf8
    NSDictionary *_videoCoreSettings;	// 256 = 0x100
    NSDictionary *_responeDict;	// 264 = 0x108
}

+ (id)modelWithJSONDictionary:(id)arg1;
@property(retain, nonatomic) NSDictionary *responeDict; // @synthesize responeDict=_responeDict;
@property(retain, nonatomic) NSDictionary *videoCoreSettings; // @synthesize videoCoreSettings=_videoCoreSettings;
@property(copy, nonatomic) NSString *popupWindowUrl; // @synthesize popupWindowUrl=_popupWindowUrl;
@property(retain, nonatomic) NSArray<TBLiveDetailProductItemModel> *itemList; // @synthesize itemList=_itemList;
@property(copy, nonatomic) NSString *roomNum; // @synthesize roomNum=_roomNum;
@property(copy, nonatomic) NSString *inputCodeLevel; // @synthesize inputCodeLevel=_inputCodeLevel;
@property(copy, nonatomic) NSString *isPlayerLow; // @synthesize isPlayerLow=_isPlayerLow;
@property(copy, nonatomic) NSString *appointmentTime; // @synthesize appointmentTime=_appointmentTime;
@property(retain, nonatomic) TBLiveBroadCasterAccountInfo *broadCaster; // @synthesize broadCaster=_broadCaster;
@property(copy, nonatomic) NSString *nativeFeedDetailUrl; // @synthesize nativeFeedDetailUrl=_nativeFeedDetailUrl;
@property(copy, nonatomic) NSString *accountId; // @synthesize accountId=_accountId;
@property(copy, nonatomic) NSString *parseCount; // @synthesize parseCount=_parseCount;
@property(copy, nonatomic) NSString *totalJoinCount; // @synthesize totalJoinCount=_totalJoinCount;
@property(copy, nonatomic) NSString *joinCount; // @synthesize joinCount=_joinCount;
@property(copy, nonatomic) NSString *endPushStreamTime; // @synthesize endPushStreamTime=_endPushStreamTime;
@property(copy, nonatomic) NSString *endTime; // @synthesize endTime=_endTime;
@property(copy, nonatomic) NSString *startTime; // @synthesize startTime=_startTime;
@property(copy, nonatomic) NSString *timeLength; // @synthesize timeLength=_timeLength;
@property(copy, nonatomic) NSString *groupChatNum; // @synthesize groupChatNum=_groupChatNum;
@property(copy, nonatomic) NSString *location; // @synthesize location=_location;
@property(copy, nonatomic) NSString *replayUrl; // @synthesize replayUrl=_replayUrl;
@property(retain, nonatomic) NSArray<TBLiveConventionModel> *conventionList; // @synthesize conventionList=_conventionList;
@property(retain, nonatomic) NSArray<TBLiveURLItemModel> *liveUrlList; // @synthesize liveUrlList=_liveUrlList;
@property(copy, nonatomic) NSString *liveUrlHls; // @synthesize liveUrlHls=_liveUrlHls;
@property(copy, nonatomic) NSString *liveUrl; // @synthesize liveUrl=_liveUrl;
@property(copy, nonatomic) NSString *coverImg; // @synthesize coverImg=_coverImg;
@property(copy, nonatomic) NSString *inputStreamUrl; // @synthesize inputStreamUrl=_inputStreamUrl;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *bizStatus; // @synthesize bizStatus=_bizStatus;
@property(copy, nonatomic) NSString *status; // @synthesize status=_status;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *channelId; // @synthesize channelId=_channelId;
@property(copy, nonatomic) NSString *feedId; // @synthesize feedId=_feedId;
- (void).cxx_destruct;

@end

