//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, TBLiveGoodsView, UITableView, UIView;

@interface TBLiveGoodsProcessor : NSObject
{
    UITableView *_goodsTableView;	// 8 = 0x8
    NSMutableArray *_goodsList;	// 16 = 0x10
    UIView *_mainView;	// 24 = 0x18
    TBLiveGoodsView *_goodsItemView;	// 32 = 0x20
    UIView *_skuParentView;	// 40 = 0x28
}

@property(nonatomic) __weak UIView *skuParentView; // @synthesize skuParentView=_skuParentView;
@property(retain, nonatomic) TBLiveGoodsView *goodsItemView; // @synthesize goodsItemView=_goodsItemView;
@property(retain, nonatomic) UIView *mainView; // @synthesize mainView=_mainView;
@property(retain, nonatomic) NSMutableArray *goodsList; // @synthesize goodsList=_goodsList;
@property(retain, nonatomic) UITableView *goodsTableView; // @synthesize goodsTableView=_goodsTableView;
- (void).cxx_destruct;
- (void)closeView;
- (void)showGoodsListWithSuperView:(id)arg1;

@end

