//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TBMirrorSkuViewHeadDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSString, TBMirrorDetailModel, TBMirrorSkuPropsModel, TBMirrorSkuViewHead, UILabel, UITableView;
@protocol TBMirrorSkuViewDelegate;

@interface TBMirrorSkuView : UIView <UITableViewDataSource, UITableViewDelegate, TBMirrorSkuViewHeadDelegate>
{
    double TBMIRROR_SKUVIEW_UNFOLD_ORIGIN_Y;	// 8 = 0x8
    id <TBMirrorSkuViewDelegate> _delegate;	// 16 = 0x10
    TBMirrorDetailModel *_itemModel;	// 24 = 0x18
    TBMirrorSkuPropsModel *_fristPropsModel;	// 32 = 0x20
    TBMirrorSkuPropsModel *_secondPropsModel;	// 40 = 0x28
    TBMirrorSkuViewHead *_headView;	// 48 = 0x30
    UILabel *_fristPropNameLabel;	// 56 = 0x38
    UITableView *_fristTableView;	// 64 = 0x40
    UILabel *_secondPropNameLabel;	// 72 = 0x48
    UITableView *_secondTableView;	// 80 = 0x50
    NSString *_fristTablePreClickPropId;	// 88 = 0x58
    long long _fristTablePreClickIndex;	// 96 = 0x60
    UILabel *_fristTablePreClickBtn;	// 104 = 0x68
    NSString *_secondTablePreClickPropId;	// 112 = 0x70
    long long _secondTablePreClickIndex;	// 120 = 0x78
    UILabel *_secondTablePreClickBtn;	// 128 = 0x80
    CDUnknownBlockType _callback;	// 136 = 0x88
}

@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
@property(retain, nonatomic) UILabel *secondTablePreClickBtn; // @synthesize secondTablePreClickBtn=_secondTablePreClickBtn;
@property(nonatomic) long long secondTablePreClickIndex; // @synthesize secondTablePreClickIndex=_secondTablePreClickIndex;
@property(retain, nonatomic) NSString *secondTablePreClickPropId; // @synthesize secondTablePreClickPropId=_secondTablePreClickPropId;
@property(retain, nonatomic) UILabel *fristTablePreClickBtn; // @synthesize fristTablePreClickBtn=_fristTablePreClickBtn;
@property(nonatomic) long long fristTablePreClickIndex; // @synthesize fristTablePreClickIndex=_fristTablePreClickIndex;
@property(retain, nonatomic) NSString *fristTablePreClickPropId; // @synthesize fristTablePreClickPropId=_fristTablePreClickPropId;
@property(retain, nonatomic) UITableView *secondTableView; // @synthesize secondTableView=_secondTableView;
@property(retain, nonatomic) UILabel *secondPropNameLabel; // @synthesize secondPropNameLabel=_secondPropNameLabel;
@property(retain, nonatomic) UITableView *fristTableView; // @synthesize fristTableView=_fristTableView;
@property(retain, nonatomic) UILabel *fristPropNameLabel; // @synthesize fristPropNameLabel=_fristPropNameLabel;
@property(retain, nonatomic) TBMirrorSkuViewHead *headView; // @synthesize headView=_headView;
@property(retain, nonatomic) TBMirrorSkuPropsModel *secondPropsModel; // @synthesize secondPropsModel=_secondPropsModel;
@property(retain, nonatomic) TBMirrorSkuPropsModel *fristPropsModel; // @synthesize fristPropsModel=_fristPropsModel;
@property(retain, nonatomic) TBMirrorDetailModel *itemModel; // @synthesize itemModel=_itemModel;
@property(retain, nonatomic) id <TBMirrorSkuViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)buyBtnClicked;
- (void)arrowBtnClicked:(_Bool)arg1;
- (void)makeUpMirrorSkuModel:(id)arg1;
- (id)getCurrentSkuModel;
- (void)makeUp;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)getCellLabelWithTitle:(id)arg1 indexPath:(id)arg2 tableView:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)setUpView;
- (void)removeUnSupportDataWithPropModel:(id)arg1;
- (void)setItemModel:(id)arg1 callBack:(CDUnknownBlockType)arg2;
- (void)clear;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

