//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface TBModelStatusInfo : NSObject
{
    CDUnknownBlockType _actionTitleBlock;	// 8 = 0x8
    CDUnknownBlockType _titleBlock;	// 16 = 0x10
    CDUnknownBlockType _subtitleBlock;	// 24 = 0x18
}

@property(copy, nonatomic) CDUnknownBlockType subtitleBlock; // @synthesize subtitleBlock=_subtitleBlock;
@property(copy, nonatomic) CDUnknownBlockType titleBlock; // @synthesize titleBlock=_titleBlock;
@property(copy, nonatomic) CDUnknownBlockType actionTitleBlock; // @synthesize actionTitleBlock=_actionTitleBlock;
- (void).cxx_destruct;
- (_Bool)isCongestionControlForError:(id)arg1;
- (id)actionButtonTitleForError:(id)arg1;
- (id)subTitleForError:(id)arg1;
- (id)titleForError:(id)arg1;
- (id)iconfontImageForEmpty;
- (id)iconfontImageForError:(id)arg1;
- (id)imageForError:(id)arg1;
- (id)imageForEmpty;
- (id)actionButtonTitleForEmpty;
- (id)subTitleForEmpty;
- (id)titleForEmpty;

@end

