//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface TBMPostMessageConfigurationItem : NSObject
{
    NSString *_messageName;	// 8 = 0x8
    NSString *_messageCode;	// 16 = 0x10
}

@property(readonly, nonatomic) NSString *messageCode; // @synthesize messageCode=_messageCode;
@property(readonly, nonatomic) NSString *messageName; // @synthesize messageName=_messageName;
- (void).cxx_destruct;
- (id)initWithPostMessageConfiguration:(id)arg1;

@end

