//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBJSONModel.h"

@class NSString;

@interface TBOAction : TBJSONModel
{
    int _actionId;	// 8 = 0x8
    NSString *_actionName;	// 16 = 0x10
    NSString *_menuName;	// 24 = 0x18
}

@property(retain, nonatomic) NSString *menuName; // @synthesize menuName=_menuName;
@property(retain, nonatomic) NSString *actionName; // @synthesize actionName=_actionName;
@property(nonatomic) int actionId; // @synthesize actionId=_actionId;
- (void).cxx_destruct;

@end

