//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TBCycleScrollViewDatasource-Protocol.h"
#import "TBCycleScrollViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString, TBCycleScrollView, TBOSimplePhotoBrowserController;

@interface TBOBannerView : UIView <TBCycleScrollViewDatasource, TBCycleScrollViewDelegate, UIScrollViewDelegate>
{
    unsigned long long _imageScaleType;	// 8 = 0x8
    TBCycleScrollView *_bannerView;	// 16 = 0x10
    NSMutableDictionary *_bannerItemDict;	// 24 = 0x18
    NSMutableArray *_firstViewPoint;	// 32 = 0x20
    TBOSimplePhotoBrowserController *_simpleBrower;	// 40 = 0x28
    NSMutableArray *_bannerItems;	// 48 = 0x30
}

@property(retain, nonatomic) NSMutableArray *bannerItems; // @synthesize bannerItems=_bannerItems;
@property(retain, nonatomic) TBOSimplePhotoBrowserController *simpleBrower; // @synthesize simpleBrower=_simpleBrower;
@property(retain, nonatomic) NSMutableArray *firstViewPoint; // @synthesize firstViewPoint=_firstViewPoint;
@property(retain, nonatomic) NSMutableDictionary *bannerItemDict; // @synthesize bannerItemDict=_bannerItemDict;
@property(retain, nonatomic) TBCycleScrollView *bannerView; // @synthesize bannerView=_bannerView;
@property(nonatomic) unsigned long long imageScaleType; // @synthesize imageScaleType=_imageScaleType;
- (void).cxx_destruct;
- (void)didClickPage:(id)arg1 atIndex:(long long)arg2;
- (id)createdItem:(long long)arg1;
- (id)csView:(id)arg1 pageAtIndex:(long long)arg2;
- (long long)numberOfPages:(id)arg1;
- (void)setBannerViewCurCount:(long long)arg1;
- (void)layoutSubviews;
- (void)setItem:(id)arg1;
- (void)pageControlNeedUpdate:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

