//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBOBaseListViewModel.h"

#import "ITBOActions-Protocol.h"

@class NSMutableArray, NSString;
@protocol TBOAction;

@interface TBOCommentListViewModel : TBOBaseListViewModel <ITBOActions>
{
    NSString *_cursor;	// 8 = 0x8
    _Bool _hasMore;	// 16 = 0x10
    NSString *_feedId;	// 24 = 0x18
    NSString *_topicId;	// 32 = 0x20
    NSMutableArray<TBOAction> *_actions;	// 40 = 0x28
}

+ (id)initWithFeedId:(id)arg1 andTopicId:(id)arg2;
@property(retain, nonatomic) NSMutableArray<TBOAction> *actions; // @synthesize actions=_actions;
@property(readonly, nonatomic) NSString *topicId; // @synthesize topicId=_topicId;
@property(readonly, nonatomic) NSString *feedId; // @synthesize feedId=_feedId;
- (void).cxx_destruct;
- (_Bool)hasMore;
- (void)onload;
- (id)initWithFeedId:(id)arg1 andTopicId:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

