//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBCycleScrollView.h"

#import "TBCycleScrollViewDatasource-Protocol.h"

@class NSMutableArray, NSString;

@interface TBOCommunityScrollView : TBCycleScrollView <TBCycleScrollViewDatasource>
{
    NSMutableArray *_views;	// 8 = 0x8
    double _height;	// 16 = 0x10
}

- (void).cxx_destruct;
- (id)csView:(id)arg1 pageAtIndex:(long long)arg2;
- (long long)numberOfPages:(id)arg1;
- (void)reloadForModel:(id)arg1;
- (void)setModel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

