//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBOBaseCard.h"

@class NSDictionary;

@interface TBORecommendCommunityListCard : TBOBaseCard
{
    NSDictionary *_jsonData;	// 32 = 0x20
}

@property(retain, nonatomic) NSDictionary *jsonData; // @synthesize jsonData=_jsonData;
- (void).cxx_destruct;
- (id)initWithJSONDictionary:(id)arg1 error:(id *)arg2;

@end

