//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBOrderObject.h"

@class NSString;

@interface TBOrderPayItemInfo : TBOrderObject
{
    NSString *_payItemType;	// 8 = 0x8
}

@property(retain, nonatomic) NSString *payItemType; // @synthesize payItemType=_payItemType;
- (void).cxx_destruct;
- (id)des;
- (id)suffix;
- (id)prefix;
- (id)value;

@end

