//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBJSONModel.h"

@class NSString;

@interface TBOrderRefundPageMetaModel : TBJSONModel
{
    _Bool _showMenuApply;	// 8 = 0x8
    _Bool _showTaobaoTab;	// 9 = 0x9
    NSString *_page;	// 16 = 0x10
    NSString *_total;	// 24 = 0x18
    NSString *_pagesize;	// 32 = 0x20
}

@property(nonatomic) _Bool showTaobaoTab; // @synthesize showTaobaoTab=_showTaobaoTab;
@property(nonatomic) _Bool showMenuApply; // @synthesize showMenuApply=_showMenuApply;
@property(retain, nonatomic) NSString *pagesize; // @synthesize pagesize=_pagesize;
@property(retain, nonatomic) NSString *total; // @synthesize total=_total;
@property(retain, nonatomic) NSString *page; // @synthesize page=_page;
- (void).cxx_destruct;

@end

