//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface TBPluginBundleConfigLoder : NSObject
{
    NSString *_pluginBundleVersion;	// 8 = 0x8
    unsigned long long _envronment;	// 16 = 0x10
}

+ (void)createPathAndRemoveOldPath;
+ (id)pluginBundleImageVersionForBundleName:(id)arg1;
+ (void)setPluginBundleImageVersionForBundleName:(id)arg1;
+ (id)pluginBundleVesion;
+ (id)unzipFilePathWithBundleName:(id)arg1;
+ (id)unZipFileHomePath;
+ (void)downloadRunPluginImageForBundle:(id)arg1;
+ (void)setPluginBundleVersion:(id)arg1 envronment:(unsigned long long)arg2;
+ (id)urlStringForImageName:(id)arg1 model:(unsigned long long)arg2 bundle:(id)arg3;
+ (id)sharedInstance;
@property(nonatomic) unsigned long long envronment; // @synthesize envronment=_envronment;
@property(retain, nonatomic) NSString *pluginBundleVersion; // @synthesize pluginBundleVersion=_pluginBundleVersion;
- (void).cxx_destruct;
- (void)pluginBundleImageStartDownLoad:(id)arg1;
- (id)tempPatchDir;
- (id)tempZipFilePathWithBundleName:(id)arg1;
- (void)cleanTempFileForBundleName:(id)arg1;
- (_Bool)unzipVerifyRunFile:(id)arg1 bundle:(id)arg2;

@end

