//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class TBQGRequestModel;
@protocol TBQGRequestModelDelegate;

@interface TBQGService : NSObject
{
    id <TBQGRequestModelDelegate> _delegate;	// 8 = 0x8
    TBQGRequestModel *_requestModel;	// 16 = 0x10
}

@property(retain, nonatomic) TBQGRequestModel *requestModel; // @synthesize requestModel=_requestModel;
@property(nonatomic) __weak id <TBQGRequestModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)cancelRequest;
- (void)loadWeatherData:(id)arg1 batchId:(id)arg2;
- (void)loadNovelData:(id)arg1;
- (void)loadPersonalizedItemsWithBatchId:(id)arg1 pageSize:(long long)arg2 currentPage:(long long)arg3;
- (void)loadRecommendItem;
- (void)loadFollowItemWithIds:(id)arg1;
- (void)loadHotItemWithTabId:(long long)arg1 juIds:(id)arg2;
- (void)loadHotItemWithTabId:(long long)arg1;
- (void)loadBatchItemWithCategoryId:(id)arg1 childCategoryId:(id)arg2 offset:(long long)arg3 limit:(long long)arg4;
- (void)loadBatchItemWithBatchId:(id)arg1 contentId:(id)arg2;
- (void)loadHomePageItem;
- (void)loadCategoryWithStartedBlock:(CDUnknownBlockType)arg1 successedBlock:(CDUnknownBlockType)arg2 failedBlock:(CDUnknownBlockType)arg3;

@end

