//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class TBLayout, TBQGDoubleCellStateActionControl, TBQGDoubleCellStockProgressLabel, UIDoubleLabelStrikeThrough, UIImageView, UILabel, UIView;

@interface TBQGDoubleGoodsTableViewCell : UITableViewCell
{
    _Bool _touchOnLeft;	// 8 = 0x8
    TBLayout *_layoutItem;	// 16 = 0x10
    UIImageView *_leftGoodsImageView;	// 24 = 0x18
    UIImageView *_rightGoodsImageView;	// 32 = 0x20
    UILabel *_leftTitleLabel;	// 40 = 0x28
    UILabel *_leftSoldInfoLabel;	// 48 = 0x30
    UIDoubleLabelStrikeThrough *_leftOriginalPriceLabel;	// 56 = 0x38
    UILabel *_leftDiscountPriceLabel;	// 64 = 0x40
    TBQGDoubleCellStateActionControl *_leftStateActionControl;	// 72 = 0x48
    TBQGDoubleCellStockProgressLabel *_leftStockProgressLabel;	// 80 = 0x50
    UIView *_leftBannerView;	// 88 = 0x58
    UIView *_rightBannerView;	// 96 = 0x60
    UILabel *_leftSoldOutMessageLabel;	// 104 = 0x68
    UILabel *_rightSoldOutMessageLabel;	// 112 = 0x70
    UILabel *_rightTitleLabel;	// 120 = 0x78
    UILabel *_rightSoldInfoLabel;	// 128 = 0x80
    UIDoubleLabelStrikeThrough *_rightOriginalPriceLabel;	// 136 = 0x88
    UILabel *_rightDiscountPriceLabel;	// 144 = 0x90
    TBQGDoubleCellStateActionControl *_rightStateActionControl;	// 152 = 0x98
    TBQGDoubleCellStockProgressLabel *_rightStockProgressLabel;	// 160 = 0xa0
}

+ (id)placeholderImage;
@property(retain, nonatomic) TBQGDoubleCellStockProgressLabel *rightStockProgressLabel; // @synthesize rightStockProgressLabel=_rightStockProgressLabel;
@property(retain, nonatomic) TBQGDoubleCellStateActionControl *rightStateActionControl; // @synthesize rightStateActionControl=_rightStateActionControl;
@property(retain, nonatomic) UILabel *rightDiscountPriceLabel; // @synthesize rightDiscountPriceLabel=_rightDiscountPriceLabel;
@property(retain, nonatomic) UIDoubleLabelStrikeThrough *rightOriginalPriceLabel; // @synthesize rightOriginalPriceLabel=_rightOriginalPriceLabel;
@property(retain, nonatomic) UILabel *rightSoldInfoLabel; // @synthesize rightSoldInfoLabel=_rightSoldInfoLabel;
@property(retain, nonatomic) UILabel *rightTitleLabel; // @synthesize rightTitleLabel=_rightTitleLabel;
@property(retain, nonatomic) UILabel *rightSoldOutMessageLabel; // @synthesize rightSoldOutMessageLabel=_rightSoldOutMessageLabel;
@property(retain, nonatomic) UILabel *leftSoldOutMessageLabel; // @synthesize leftSoldOutMessageLabel=_leftSoldOutMessageLabel;
@property(retain, nonatomic) UIView *rightBannerView; // @synthesize rightBannerView=_rightBannerView;
@property(retain, nonatomic) UIView *leftBannerView; // @synthesize leftBannerView=_leftBannerView;
@property(retain, nonatomic) TBQGDoubleCellStockProgressLabel *leftStockProgressLabel; // @synthesize leftStockProgressLabel=_leftStockProgressLabel;
@property(retain, nonatomic) TBQGDoubleCellStateActionControl *leftStateActionControl; // @synthesize leftStateActionControl=_leftStateActionControl;
@property(retain, nonatomic) UILabel *leftDiscountPriceLabel; // @synthesize leftDiscountPriceLabel=_leftDiscountPriceLabel;
@property(retain, nonatomic) UIDoubleLabelStrikeThrough *leftOriginalPriceLabel; // @synthesize leftOriginalPriceLabel=_leftOriginalPriceLabel;
@property(retain, nonatomic) UILabel *leftSoldInfoLabel; // @synthesize leftSoldInfoLabel=_leftSoldInfoLabel;
@property(retain, nonatomic) UILabel *leftTitleLabel; // @synthesize leftTitleLabel=_leftTitleLabel;
@property(nonatomic, getter=wasTouchOnLeft) _Bool touchOnLeft; // @synthesize touchOnLeft=_touchOnLeft;
@property(retain, nonatomic) UIImageView *rightGoodsImageView; // @synthesize rightGoodsImageView=_rightGoodsImageView;
@property(retain, nonatomic) UIImageView *leftGoodsImageView; // @synthesize leftGoodsImageView=_leftGoodsImageView;
@property(retain, nonatomic) TBLayout *layoutItem; // @synthesize layoutItem=_layoutItem;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)changeStyleWithCell:(id)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)updateImageViewWithCellModel:(id)arg1;
- (void)updateStockProgressWithCellModel:(id)arg1;
- (id)processPriceDecimalPoint:(id)arg1 priceColor:(id)arg2 fontSize:(double)arg3;
- (void)updateWithCellModel:(id)arg1;
- (id)substringTitle:(id)arg1;
- (id)priceFontWithSize:(double)arg1;
- (void)prepareForReuse;
- (_Bool)tag:(long long)arg1 class:(Class)arg2;
- (void)mapViewWithTag;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

@end

