//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBRDisposable.h"

@interface TBRSerialDisposable : TBRDisposable
{
    TBRDisposable *_disposable;	// 8 = 0x8
    _Bool _disposed;	// 16 = 0x10
    int _spinLock;	// 20 = 0x14
}

+ (id)serialDisposableWithDisposable:(id)arg1;
- (void).cxx_destruct;
- (void)dispose;
- (id)swapInDisposable:(id)arg1;
- (void)dealloc;
- (id)initWithBlock:(CDUnknownBlockType)arg1;
@property(retain) TBRDisposable *disposable;
- (_Bool)isDisposed;

@end

