//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSString;

@interface TBScanCodeExpressModel : NSObject
{
    NSString *_number;	// 8 = 0x8
    NSString *_companyName;	// 16 = 0x10
    NSArray *_stepInfo;	// 24 = 0x18
}

@property(retain, nonatomic) NSArray *stepInfo; // @synthesize stepInfo=_stepInfo;
@property(retain, nonatomic) NSString *companyName; // @synthesize companyName=_companyName;
@property(retain, nonatomic) NSString *number; // @synthesize number=_number;
- (void).cxx_destruct;
- (id)initWithNumber:(id)arg1 companyName:(id)arg2 stepInfo:(id)arg3;

@end

