//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface TBSDKCacheFile : NSObject
{
}

+ (void)clearAllCache;
+ (id)fileNameByKey:(id)arg1;
+ (id)cacheFilePath:(id)arg1;
+ (_Bool)cacheFileDelete:(id)arg1;
+ (_Bool)cacheFileExists:(id)arg1;
+ (_Bool)cacheFileExpired:(id)arg1 expiredSecond:(long long)arg2;
+ (id)cacheFileGetNSdata:(id)arg1;
+ (id)cacheFileGet:(id)arg1;
+ (_Bool)cacheFileSetNsdata:(id)arg1 contents:(id)arg2;
+ (_Bool)cacheFileSet:(id)arg1 contents:(id)arg2;

@end

