//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBJSONModel.h"

@class NSMutableArray, NSString;
@protocol TBSearchRelatedRecommendTagItemModel;

@interface TBSearchRelatedRecommendModel : TBJSONModel
{
    NSString *_tipContent;	// 8 = 0x8
    NSMutableArray<TBSearchRelatedRecommendTagItemModel> *_tagList;	// 16 = 0x10
}

+ (_Bool)strictMode;
@property(retain, nonatomic) NSMutableArray<TBSearchRelatedRecommendTagItemModel> *tagList; // @synthesize tagList=_tagList;
@property(retain, nonatomic) NSString *tipContent; // @synthesize tipContent=_tipContent;
- (void).cxx_destruct;

@end

