//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBSearchWapItemBase.h"

@class NSArray, NSDictionary, NSString;

@interface TBSearchSpuItem : TBSearchWapItemBase
{
    int _sold;	// 8 = 0x8
    NSString *_title;	// 16 = 0x10
    double _price;	// 24 = 0x18
    double _scoref;	// 32 = 0x20
    NSString *_pic_path;	// 40 = 0x28
    NSString *_sellerCount;	// 48 = 0x30
    NSString *_commentCount;	// 56 = 0x38
    NSString *_tagInfo;	// 64 = 0x40
    NSString *_spuId;	// 72 = 0x48
    NSString *_iconList;	// 80 = 0x50
    NSString *_spuProp;	// 88 = 0x58
    NSArray *_spuParams;	// 96 = 0x60
    NSDictionary *_priceShow;	// 104 = 0x68
    NSArray *_icons;	// 112 = 0x70
}

@property(retain, nonatomic) NSArray *icons; // @synthesize icons=_icons;
@property(retain, nonatomic) NSDictionary *priceShow; // @synthesize priceShow=_priceShow;
@property(retain, nonatomic) NSArray *spuParams; // @synthesize spuParams=_spuParams;
@property(retain, nonatomic) NSString *spuProp; // @synthesize spuProp=_spuProp;
@property(retain, nonatomic) NSString *iconList; // @synthesize iconList=_iconList;
@property(copy, nonatomic) NSString *spuId; // @synthesize spuId=_spuId;
@property(copy, nonatomic) NSString *tagInfo; // @synthesize tagInfo=_tagInfo;
@property(retain, nonatomic) NSString *commentCount; // @synthesize commentCount=_commentCount;
@property(retain, nonatomic) NSString *sellerCount; // @synthesize sellerCount=_sellerCount;
@property(nonatomic) int sold; // @synthesize sold=_sold;
@property(copy, nonatomic) NSString *pic_path; // @synthesize pic_path=_pic_path;
@property(nonatomic) double scoref; // @synthesize scoref=_scoref;
@property(nonatomic) double price; // @synthesize price=_price;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)pic_url;

@end

