//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface TBShopCalendarHelper : NSObject
{
}

+ (void)removeWithBusinessId:(id)arg1 sourceId:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)addWithBusinessId:(id)arg1 param:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (_Bool)checkStatusWithBusinessId:(id)arg1 sourceId:(id)arg2;
+ (id)calendarService;
+ (id)userId;

@end

