//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, TBCartEventContext;

@protocol TBShopCartModelDelegate <NSObject>
- (_Bool)showInvalid;
- (_Bool)handleEvent:(NSString *)arg1 withContext:(TBCartEventContext *)arg2;

@optional
- (double)serverTimeOffset;
@end

