//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@interface TBSNSCommonAccountHeadView : UIControl
{
}

- (void)setTitleFont:(id)arg1 titleColor:(id)arg2 descFont:(id)arg3 descColor:(id)arg4;
- (void)setAccountIconWithURL:(id)arg1 placeholderImage:(id)arg2;
- (void)setAccountIcon:(id)arg1;
- (void)setTitle:(id)arg1 description:(id)arg2 andGTypeTag:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

