//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBSNSCardView.h"

@class NSArray, NSMutableArray, NSString, TBSNSCard9ImageShowMorePicView;

@interface TBSNSCard9ImageWithPrice : TBSNSCardView
{
    _Bool _needShowMoreLabelFlag;	// 8 = 0x8
    NSMutableArray *_subs;	// 16 = 0x10
    unsigned long long _imgCount;	// 24 = 0x18
    NSArray *_imgURLStrings;	// 32 = 0x20
    CDUnknownBlockType _clickHandler;	// 40 = 0x28
    NSString *_morePicCountText;	// 48 = 0x30
    TBSNSCard9ImageShowMorePicView *_morePicView;	// 56 = 0x38
}

+ (struct CGSize)fixedSize;
+ (double)getImgWH:(unsigned long long)arg1;
+ (unsigned long long)getRowsWithImgCount:(unsigned long long)arg1;
+ (unsigned long long)getColsWithImgCount:(unsigned long long)arg1;
+ (unsigned long long)getMaxColsWithImgCount:(unsigned long long)arg1;
+ (struct CGSize)maxSizeWithImgCount:(unsigned long long)arg1;
+ (struct CGSize)getDynamicSingleImageSizeBySize:(struct CGSize)arg1 andUrl:(id)arg2;
+ (struct CGSize)getDynamicSizeByImgCount:(unsigned long long)arg1;
@property(retain, nonatomic) TBSNSCard9ImageShowMorePicView *morePicView; // @synthesize morePicView=_morePicView;
@property(copy, nonatomic) NSString *morePicCountText; // @synthesize morePicCountText=_morePicCountText;
@property(nonatomic) _Bool needShowMoreLabelFlag; // @synthesize needShowMoreLabelFlag=_needShowMoreLabelFlag;
@property(copy, nonatomic) CDUnknownBlockType clickHandler; // @synthesize clickHandler=_clickHandler;
@property(retain, nonatomic) NSArray *imgURLStrings; // @synthesize imgURLStrings=_imgURLStrings;
@property(nonatomic) unsigned long long imgCount; // @synthesize imgCount=_imgCount;
@property(retain, nonatomic) NSMutableArray *subs; // @synthesize subs=_subs;
- (void).cxx_destruct;
- (void)reset;
- (void)addImageClickHandler:(CDUnknownBlockType)arg1;
- (void)setSingleImageWithUrl:(id)arg1 withSize:(struct CGSize)arg2;
- (void)setImageURLStrings:(id)arg1;
- (id)getImageViews;
- (id)getImageURLStrings;
- (void)imageTap:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGSize)cardSize;

@end

