//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface TBSNSCustomRichTextUtils : NSObject
{
}

+ (struct CGSize)proposedSizeWithAttributeText:(id)arg1 constrainedSize:(struct CGSize)arg2 attachmentBounds:(struct CGRect)arg3 infos:(id)arg4;

@end

