//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "TBSNSCardListDelegate-Protocol.h"
#import "TBWeitaoServiceIntermediatePageProtocol-Protocol.h"

@class NSString, TBSNSCardListDataRequest, TBSNSIntermediatePageDataContainer, TBSNSIntermediatePageListViewController, TBSNSWeexListView;

@interface TBSNSIntermediatePageBridger : NSObject <TBSNSCardListDelegate, TBWeitaoServiceIntermediatePageProtocol>
{
    _Bool _middle;	// 8 = 0x8
    int _curPage;	// 12 = 0xc
    TBSNSIntermediatePageListViewController *_cardListVC;	// 16 = 0x10
    TBSNSIntermediatePageDataContainer *_dataContainer;	// 24 = 0x18
    TBSNSCardListDataRequest *_dataRequset;	// 32 = 0x20
    TBSNSWeexListView *_weexList;	// 40 = 0x28
    unsigned long long _accountId;	// 48 = 0x30
    NSString *_pageName;	// 56 = 0x38
    CDUnknownBlockType _svOnFinish;	// 64 = 0x40
    struct CGPoint _contentOffset;	// 72 = 0x48
    struct CGRect _viewFrame;	// 88 = 0x58
}

@property(copy, nonatomic) CDUnknownBlockType svOnFinish; // @synthesize svOnFinish=_svOnFinish;
@property(nonatomic) _Bool middle; // @synthesize middle=_middle;
@property(retain, nonatomic) NSString *pageName; // @synthesize pageName=_pageName;
@property(nonatomic) struct CGPoint contentOffset; // @synthesize contentOffset=_contentOffset;
@property(nonatomic) struct CGRect viewFrame; // @synthesize viewFrame=_viewFrame;
@property(nonatomic) unsigned long long accountId; // @synthesize accountId=_accountId;
@property(nonatomic) int curPage; // @synthesize curPage=_curPage;
@property(retain, nonatomic) TBSNSWeexListView *weexList; // @synthesize weexList=_weexList;
@property(retain, nonatomic) TBSNSCardListDataRequest *dataRequset; // @synthesize dataRequset=_dataRequset;
@property(retain, nonatomic) TBSNSIntermediatePageDataContainer *dataContainer; // @synthesize dataContainer=_dataContainer;
@property(retain, nonatomic) TBSNSIntermediatePageListViewController *cardListVC; // @synthesize cardListVC=_cardListVC;
- (void).cxx_destruct;
- (void)dealloc;
- (void)serviceFinishForCardList:(id)arg1 withFirstPage:(_Bool)arg2 withError:(id)arg3;
- (void)scrollEventForCardList:(id)arg1 withContentOffset:(struct CGPoint)arg2;
- (id)recoverView;
- (void)releaseView;
- (void)refreshData:(id)arg1;
- (id)createView:(_Bool)arg1;
- (void)setupWeexList;
- (void)getScrollViewWithCompletion:(CDUnknownBlockType)arg1;
- (id)createViewWithFrame:(struct CGRect)arg1 query:(id)arg2;
- (id)dataForUserTrack;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

