//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBJSONModel.h"

@class NSArray, NSString, TBTakeoutOrderContactModel, TBTakeoutOrderDetailStoreModel, TBTakeoutOrderFeeModel, TBTakeoutOrderServiceAddressModel, TBTakeoutOrderTradeModel;

@interface TBTakeoutOrderDetailModel : TBJSONModel
{
    _Bool _payOnDelivery;	// 8 = 0x8
    _Bool _hasDeliver;	// 9 = 0x9
    NSString *_outOrderId;	// 16 = 0x10
    NSString *_status;	// 24 = 0x18
    NSString *_statusDesc;	// 32 = 0x20
    NSString *_statusInterval;	// 40 = 0x28
    NSString *_processNodeId;	// 48 = 0x30
    NSString *_appointOrderId;	// 56 = 0x38
    NSString *_deliveryTime;	// 64 = 0x40
    NSString *_buyerMessage;	// 72 = 0x48
    NSString *_invoice;	// 80 = 0x50
    NSArray *_processInfo;	// 88 = 0x58
    TBTakeoutOrderServiceAddressModel *_serviceAddress;	// 96 = 0x60
    TBTakeoutOrderDetailStoreModel *_storeInfo;	// 104 = 0x68
    NSArray *_orderItems;	// 112 = 0x70
    TBTakeoutOrderFeeModel *_orderFee;	// 120 = 0x78
    TBTakeoutOrderContactModel *_orderContactInfo;	// 128 = 0x80
    TBTakeoutOrderTradeModel *_tradeInfo;	// 136 = 0x88
    NSArray *_buttons;	// 144 = 0x90
}

+ (id)modelWithJSONDictionary:(id)arg1;
@property(nonatomic) _Bool hasDeliver; // @synthesize hasDeliver=_hasDeliver;
@property(copy, nonatomic) NSArray *buttons; // @synthesize buttons=_buttons;
@property(retain, nonatomic) TBTakeoutOrderTradeModel *tradeInfo; // @synthesize tradeInfo=_tradeInfo;
@property(retain, nonatomic) TBTakeoutOrderContactModel *orderContactInfo; // @synthesize orderContactInfo=_orderContactInfo;
@property(retain, nonatomic) TBTakeoutOrderFeeModel *orderFee; // @synthesize orderFee=_orderFee;
@property(copy, nonatomic) NSArray *orderItems; // @synthesize orderItems=_orderItems;
@property(retain, nonatomic) TBTakeoutOrderDetailStoreModel *storeInfo; // @synthesize storeInfo=_storeInfo;
@property(retain, nonatomic) TBTakeoutOrderServiceAddressModel *serviceAddress; // @synthesize serviceAddress=_serviceAddress;
@property(copy, nonatomic) NSArray *processInfo; // @synthesize processInfo=_processInfo;
@property(copy, nonatomic) NSString *invoice; // @synthesize invoice=_invoice;
@property(copy, nonatomic) NSString *buyerMessage; // @synthesize buyerMessage=_buyerMessage;
@property(copy, nonatomic) NSString *deliveryTime; // @synthesize deliveryTime=_deliveryTime;
@property(copy, nonatomic) NSString *appointOrderId; // @synthesize appointOrderId=_appointOrderId;
@property(copy, nonatomic) NSString *processNodeId; // @synthesize processNodeId=_processNodeId;
@property(copy, nonatomic) NSString *statusInterval; // @synthesize statusInterval=_statusInterval;
@property(copy, nonatomic) NSString *statusDesc; // @synthesize statusDesc=_statusDesc;
@property(copy, nonatomic) NSString *status; // @synthesize status=_status;
@property(nonatomic) _Bool payOnDelivery; // @synthesize payOnDelivery=_payOnDelivery;
@property(copy, nonatomic) NSString *outOrderId; // @synthesize outOrderId=_outOrderId;
- (void).cxx_destruct;
- (id)initWithJSONDictionary:(id)arg1;

@end

