//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSString;

@interface TBTakeoutShopFilterItem : NSObject
{
    _Bool _hasSubOption;	// 8 = 0x8
    long long _selectedOptionIndex;	// 16 = 0x10
    NSString *_defaultTitle;	// 24 = 0x18
    NSArray *_options;	// 32 = 0x20
}

@property(copy, nonatomic) NSArray *options; // @synthesize options=_options;
@property(copy, nonatomic) NSString *defaultTitle; // @synthesize defaultTitle=_defaultTitle;
@property(nonatomic) _Bool hasSubOption; // @synthesize hasSubOption=_hasSubOption;
@property(nonatomic) long long selectedOptionIndex; // @synthesize selectedOptionIndex=_selectedOptionIndex;
- (void).cxx_destruct;
- (void)clearSelection;

@end

