//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBTaoPasswordCommonView.h"

@class UIImageView;

@interface TBTaoPasswordShopView : TBTaoPasswordCommonView
{
    UIImageView *_rankLevelView;	// 8 = 0x8
}

@property(retain, nonatomic) UIImageView *rankLevelView; // @synthesize rankLevelView=_rankLevelView;
- (void).cxx_destruct;
- (id)initWithModel:(id)arg1 isSetHideSelfPassword:(_Bool)arg2;

@end

