//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSArray, NSMutableArray, UIColor, UIImage, UIView;

@interface TBTakeoutFilterTitleView : UIControl
{
    unsigned long long _selectedIndex;	// 8 = 0x8
    NSArray *_titles;	// 16 = 0x10
    UIColor *_titleColor;	// 24 = 0x18
    UIColor *_selectedTitleColor;	// 32 = 0x20
    UIImage *_indicatorImage;	// 40 = 0x28
    UIImage *_selectedIndicatorImage;	// 48 = 0x30
    NSMutableArray *_buttons;	// 56 = 0x38
    NSMutableArray *_imageViews;	// 64 = 0x40
    UIView *_bottomLine;	// 72 = 0x48
}

@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(copy, nonatomic) NSMutableArray *imageViews; // @synthesize imageViews=_imageViews;
@property(copy, nonatomic) NSMutableArray *buttons; // @synthesize buttons=_buttons;
@property(retain, nonatomic) UIImage *selectedIndicatorImage; // @synthesize selectedIndicatorImage=_selectedIndicatorImage;
@property(retain, nonatomic) UIImage *indicatorImage; // @synthesize indicatorImage=_indicatorImage;
@property(retain, nonatomic) UIColor *selectedTitleColor; // @synthesize selectedTitleColor=_selectedTitleColor;
@property(retain, nonatomic) UIColor *titleColor; // @synthesize titleColor=_titleColor;
@property(copy, nonatomic) NSArray *titles; // @synthesize titles=_titles;
@property(nonatomic) unsigned long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
- (void).cxx_destruct;
- (void)setTitle:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)filterItemPressed:(id)arg1;
- (void)updateFilterButtons;
- (void)reloadFilterButtons;
- (void)layoutSubviews;
- (void)commonInit;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 titles:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

