//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBTradeDetailViewBuilder.h"

@interface TBTradeDetailViewBuilder (ConfigView)
- (void)setupTbMoreCustomItems;
- (void)configErrorNaviBar;
- (void)configDetailNavBar;
- (void)appendToUpScrollView:(id)arg1;
- (void)configBottomBar;
- (void)confingContentView;
- (void)configNavBar;
@end

