//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class TBTradeDetailVCDataSource, TBTradeDetailViewController;

@interface TBTradeDetailMessageCenter : NSObject
{
    TBTradeDetailViewController *_detailVC;	// 8 = 0x8
    TBTradeDetailVCDataSource *_dataSource;	// 16 = 0x10
}

@property(nonatomic) __weak TBTradeDetailVCDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak TBTradeDetailViewController *detailVC; // @synthesize detailVC=_detailVC;
- (void).cxx_destruct;
- (void)shareTaoPasswordWithDetailItemInfoModel:(id)arg1;
- (void)taoPasswordScreenShotDidTakenNotification:(id)arg1;
- (void)didReceiveGotoHotspotQuestionVCNOtifaction;
- (void)didReceiveShowSkuViewNotification;
- (void)didReceiveUpdateViewNotification:(id)arg1;
- (void)didReceiveAreaIdChangedNotification:(id)arg1;
- (void)didReceiveClearReturnIsvTagNotification;
- (void)hideAccessElements:(id)arg1;
- (void)registerMessageListener;
- (id)viewBuilder;
- (void)dealloc;

@end

