//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBTradeRecmdCommonUtil.h"

@interface TBTradeRecmdCommonUtil (DrawUtil)
+ (void)drawLineFromPoint:(struct CGPoint)arg1 toPoint:(struct CGPoint)arg2 inContex:(struct CGContext *)arg3;
@end

