//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBXSearchSortbarItem.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSString, TBXSearchSortbarSortModel, UIButton, UITableView, UIView;

@interface TBXSearchSortbarItemSort : TBXSearchSortbarItem <UITableViewDataSource, UITableViewDelegate>
{
    _Bool _itemSelected;	// 8 = 0x8
    UITableView *_sortTableView;	// 16 = 0x10
    double _sortTableViewItemHeight;	// 24 = 0x18
    NSString *_name;	// 32 = 0x20
    NSString *_alias;	// 40 = 0x28
    long long _type;	// 48 = 0x30
    NSString *_selected;	// 56 = 0x38
    NSString *_defaultColor;	// 64 = 0x40
    UIButton *_itemView;	// 72 = 0x48
    UIView *_maskView;	// 80 = 0x50
    NSString *_topName;	// 88 = 0x58
}

@property(retain, nonatomic) NSString *topName; // @synthesize topName=_topName;
@property(nonatomic) _Bool itemSelected; // @synthesize itemSelected=_itemSelected;
@property(retain, nonatomic) UIView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) UIButton *itemView; // @synthesize itemView=_itemView;
@property(retain, nonatomic) NSString *defaultColor; // @synthesize defaultColor=_defaultColor;
@property(retain, nonatomic) NSString *selected; // @synthesize selected=_selected;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *alias; // @synthesize alias=_alias;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) double sortTableViewItemHeight; // @synthesize sortTableViewItemHeight=_sortTableViewItemHeight;
@property(retain, nonatomic) UITableView *sortTableView; // @synthesize sortTableView=_sortTableView;
- (void).cxx_destruct;
- (_Bool)maskViewIsOpen;
- (_Bool)checkSelectedWithAlias:(id)arg1;
- (void)resetDropListPos;
- (void)setDropListPos;
- (void)maskCloseFloatingLayer:(id)arg1;
- (void)passiveCloseFloatingLayerWithAnimated:(_Bool)arg1;
- (void)onlyCloseFloatingLayerWithAnimated:(_Bool)arg1;
- (void)closeFloatingLayer;
- (void)openFloatingLayer;
- (void)setItemActionChange;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)getTableCellSelectedSign;
- (void)setSelectedStatus:(_Bool)arg1 withTableCell:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)resetToStatusWithAnimated:(_Bool)arg1;
- (void)clearAll;
- (void)setItemToggleActionChange;
- (void)onItemClick:(id)arg1;
- (void)setTheType;
- (void)processData;
- (void)setItemDroplistSelectedStatus:(_Bool)arg1 isExpand:(_Bool)arg2;
- (void)setItemToggleSelectedStatus:(_Bool)arg1;
- (void)setItemSelectedStatus:(_Bool)arg1 isExpand:(_Bool)arg2;
- (id)getInitItemView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) TBXSearchSortbarSortModel *sortbarItemModel; // @dynamic sortbarItemModel;
@property(readonly) Class superclass;

@end

