//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@protocol TBXSearchXFilterSubComponentDelegate
- (void)doFilterSearchFromSubComponent;

@optional
- (void)subComponentExpanedWithUpAnimation;
- (void)reLayoutFilter;
- (void)subComponentExpaned:(_Bool)arg1;
@end

