//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBXSearchXFilterBaseComponent.h"

@class NSArray, NSMutableArray;

@interface TBXSearchXFilterSubLocationComponent : TBXSearchXFilterBaseComponent
{
    NSArray *_modelArr;	// 8 = 0x8
    NSMutableArray *_btnArr;	// 16 = 0x10
}

@property(retain, nonatomic) NSMutableArray *btnArr; // @synthesize btnArr=_btnArr;
@property(retain, nonatomic) NSArray *modelArr; // @synthesize modelArr=_modelArr;
- (void).cxx_destruct;
- (void)renderBtn;
- (void)initWithTitle:(id)arg1 model:(id)arg2;

@end

