//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "TFENetMonitorServiceProtocol-Protocol.h"

@protocol TFENetMonitorServiceProtocol;

@interface TFENetMonitorService : NSObject <TFENetMonitorServiceProtocol>
{
    id <TFENetMonitorServiceProtocol> _serviceInternal;	// 8 = 0x8
}

+ (id)sharedInstance;
@property(retain) id <TFENetMonitorServiceProtocol> serviceInternal; // @synthesize serviceInternal=_serviceInternal;
- (void).cxx_destruct;
@property unsigned long long lastNetworkType;
- (void)addNetworkListener:(CDUnknownBlockType)arg1;
- (id)currentWifiSSID;
- (unsigned long long)currentNetwork;
- (_Bool)isReachable;
- (_Bool)isUseProxy;
- (id)init;

@end

