//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TGBaseModel.h"

@class TGDetailAuthorModel, TGDetailContentModel, TGDetailContextModel;

@interface TGDetailPageModel : TGBaseModel
{
    TGDetailAuthorModel *_author;	// 8 = 0x8
    TGDetailContentModel *_content;	// 16 = 0x10
    TGDetailContextModel *_context;	// 24 = 0x18
}

@property(retain, nonatomic) TGDetailContextModel *context; // @synthesize context=_context;
@property(retain, nonatomic) TGDetailContentModel *content; // @synthesize content=_content;
@property(retain, nonatomic) TGDetailAuthorModel *author; // @synthesize author=_author;
- (void).cxx_destruct;
- (id)initWithParams:(id)arg1;

@end

