//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, TGShareView2DO, TGWebViewController, UIButton, UIImageView, UILabel, UIScrollView, UIView, UIViewController;

@protocol TGFunctionProtocol <NSObject>
- (void)pushDetailToPersonalCenterWith:(NSString *)arg1 andTarget:(UIView *)arg2;
- (void)pushUrlFromCurrentNavigationController:(NSString *)arg1;
- (void)addPullToRefresh:(UIScrollView *)arg1 WithActionHandler:(void (^)(void))arg2;
- (void)goToHomePageTabAtIndex:(long long)arg1 from:(id)arg2;
- (void)tgWebViewLayoutInVC:(TGWebViewController *)arg1;
- (void)updateUserAccountWithNick:(NSString *)arg1;
- (void)setupUserTrackAdapter;
- (_Bool)tbAppLinkOpenURL:(NSString *)arg1;
- (void)layoutVImageInDetail:(UIImageView *)arg1 andAvatarImageView:(UIImageView *)arg2;
- (UILabel *)iconFontLabelWithFrame:(struct CGRect)arg1 fontSize:(long long)arg2 text:(NSString *)arg3;
- (void)detailVCLayoutNavigationbarWithVC:(UIViewController *)arg1;
- (void)shareGroupLayoutInView:(UIView *)arg1 withCommentBtn:(UIButton *)arg2 andLikeButton:(UIButton *)arg3;
- (void)doShare:(TGShareView2DO *)arg1 inVC:(UIViewController *)arg2;
@end

