//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray;

@interface TGImageUrlConfig : NSObject
{
    NSArray *_excludeHosts;	// 8 = 0x8
    double _currentScale;	// 16 = 0x10
}

+ (id)checkURLSchema:(id)arg1;
+ (id)sharedConfig;
@property(nonatomic) double currentScale; // @synthesize currentScale=_currentScale;
@property(retain, nonatomic) NSArray *excludeHosts; // @synthesize excludeHosts=_excludeHosts;
- (void).cxx_destruct;
- (id)getImageScale:(struct CGSize)arg1;
- (id)configImageUrl:(id)arg1;
- (id)configImageUrl:(id)arg1 withSize:(struct CGSize)arg2;
- (id)init;

@end

