//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBJSONModel.h"

@class NSString;

@interface Tip : TBJSONModel
{
    _Bool _isFake;	// 8 = 0x8
    NSString *_id;	// 16 = 0x10
    NSString *_tip;	// 24 = 0x18
    NSString *_keywords;	// 32 = 0x20
}

+ (id)fakeTip;
@property(copy, nonatomic) NSString *keywords; // @synthesize keywords=_keywords;
@property(copy, nonatomic) NSString *tip; // @synthesize tip=_tip;
@property(copy, nonatomic) NSString *id; // @synthesize id=_id;
- (void).cxx_destruct;
- (_Bool)isFakeObject;
- (id)init;
- (id)initFake;

@end

