//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBJSONModel.h"

@class NSMutableArray;

@interface TMCCustomizeModule : TBJSONModel
{
    NSMutableArray *_modules;	// 8 = 0x8
}

+ (Class)componetWithJsonData:(id)arg1;
@property(retain, nonatomic) NSMutableArray *modules; // @synthesize modules=_modules;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1 withComponetClass:(Class)arg2 withCommonData:(id)arg3;
- (id)initWithDictionary:(id)arg1 withCommonData:(id)arg2;

@end

