//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface TMHtmlTemplate : NSObject
{
}

+ (id)htmlwrapper:(id)arg1 body:(id)arg2 backgroundColor:(id)arg3;
+ (id)htmlwrapper:(id)arg1 body:(id)arg2;
+ (id)metaViewport:(double)arg1;

@end

