//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIActivityIndicatorView;

@interface TMMarketDropdownLoadView : UIView
{
    UIActivityIndicatorView *_activityIndicatorView;	// 8 = 0x8
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)init;

@end

