//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UTShareExecutor.h"

@interface UTCopyExecutor : UTShareExecutor
{
}

- (void)shareWithContent:(id)arg1 onStarted:(CDUnknownBlockType)arg2 onFinished:(CDUnknownBlockType)arg3;

@end

