//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "UTMCConfigInterfaceUpdate-Protocol.h"

@class NSString;
@protocol UTMCDispatcher;

@interface UTMCLogBizManager : NSObject <UTMCConfigInterfaceUpdate>
{
    long long uploadInterval;	// 8 = 0x8
    struct dispatch_queue_s *storeQueue;	// 16 = 0x10
    NSObject<UTMCDispatcher> *_dispatcher;	// 24 = 0x18
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedUTMCLogBizManager;
@property(retain, nonatomic) NSObject<UTMCDispatcher> *dispatcher; // @synthesize dispatcher=_dispatcher;
- (void).cxx_destruct;
- (void)flushLogToDB;
- (void)updateSysConfigValue:(id)arg1 sysKey:(id)arg2;
- (void)setUploadInterval:(long long)arg1;
- (void)cleanDebuger;
- (_Bool)addDebugerWithURL:(id)arg1;
- (void)syncAddLog:(id)arg1;
- (void)asyncAddLog:(id)arg1;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

