//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WeAppDataUtils : NSObject
{
}

+ (_Bool)getBoolValueFromObject:(id)arg1;
+ (id)notRounding:(id)arg1 afterPoint:(unsigned long long)arg2;
+ (id)getStringFromNumber:(id)arg1 formatType:(id)arg2 precision:(id)arg3;
+ (id)intervalSinceNow:(unsigned long long)arg1;
+ (id)intervalNearNow:(unsigned long long)arg1;
+ (id)getTimeStringFromStamp:(id)arg1 dictionary:(id)arg2 weAppDataManager:(id)arg3;
+ (id)getStringFromNumber:(id)arg1 dictionary:(id)arg2 weAppDataManager:(id)arg3;
+ (id)getStringAppendString:(id)arg1 dictionary:(id)arg2 weAppDataManager:(id)arg3;
+ (id)getLabelContentWithCAViewItem:(id)arg1 weAppDataManager:(id)arg2;
+ (id)getLabelContentWithCAViewItem:(id)arg1 component:(id)arg2 weAppDataAgent:(id)arg3;
+ (id)getDateString:(id)arg1 byFormate:(id)arg2;

@end

