//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WeAppComponent.h"

@class UIView, WeAppListDataSource, WeAppViewManager;

@interface WeAppTagList : WeAppComponent
{
    _Bool _enableChoise;	// 8 = 0x8
    UIView *_listView;	// 16 = 0x10
    long long _maxLines;	// 24 = 0x18
    WeAppViewManager *_calViewManager;	// 32 = 0x20
    double _maxHeight;	// 40 = 0x28
    WeAppListDataSource *_dataSource;	// 48 = 0x30
    struct CGRect _previousFrame;	// 56 = 0x38
}

@property(retain, nonatomic) WeAppListDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) double maxHeight; // @synthesize maxHeight=_maxHeight;
@property(nonatomic) struct CGRect previousFrame; // @synthesize previousFrame=_previousFrame;
@property(retain, nonatomic) WeAppViewManager *calViewManager; // @synthesize calViewManager=_calViewManager;
@property(nonatomic) _Bool enableChoise; // @synthesize enableChoise=_enableChoise;
@property(nonatomic) long long maxLines; // @synthesize maxLines=_maxLines;
@property(retain, nonatomic) UIView *listView; // @synthesize listView=_listView;
- (void).cxx_destruct;
- (void)touchUpInside:(id)arg1;
- (struct CGRect)getTagFrameWithItemIndex:(long long)arg1;
- (void)constructTagViews;
- (void)dealloc;
- (void)display;
- (id)getSelectedTags;
- (void)setCss;
- (struct CGSize)getContentSize;
- (void)refreshData;
- (void)setupDataValue;
- (void)setupDataValueAndConditon;
- (id)createView;
- (id)initWithComponentItem:(id)arg1;

@end

