//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WVConfigModel.h"

@class NSDictionary;

@interface WVPrefixesConfigModel : WVConfigModel
{
    NSDictionary *_rules;	// 8 = 0x8
}

@property(readonly, nonatomic) NSDictionary *rules; // @synthesize rules=_rules;
- (void).cxx_destruct;
- (void)setRules:(id)arg1;
- (id)initWithVersion:(id)arg1 withType:(long long)arg2 withApps:(id)arg3;
- (id)init;

@end

