//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "WVSerializableProtocol-Protocol.h"

@class NSString, WVPagePerformance;

@interface WVResPerformance : NSObject <WVSerializableProtocol>
{
    _Bool _isHTML;	// 8 = 0x8
    NSString *_url;	// 16 = 0x10
    NSString *_fromType;	// 24 = 0x18
    NSString *_statusCode;	// 32 = 0x20
    NSString *_via;	// 40 = 0x28
    NSString *_protocolType;	// 48 = 0x30
    NSString *_pkgName;	// 56 = 0x38
    NSString *_pkgVersion;	// 64 = 0x40
    NSString *_pkgSeq;	// 72 = 0x48
    double _tcp;	// 80 = 0x50
    double _ssl;	// 88 = 0x58
    unsigned long long _dataSize;	// 96 = 0x60
    double _start;	// 104 = 0x68
    double _end;	// 112 = 0x70
    long long _statusCodeInteger;	// 120 = 0x78
    NSString *_referrer;	// 128 = 0x80
    WVPagePerformance *_page;	// 136 = 0x88
}

+ (id)ignoredMonitorProperties;
+ (id)ignoredProperties;
@property(readonly, nonatomic) __weak WVPagePerformance *page; // @synthesize page=_page;
@property(readonly, nonatomic) _Bool isHTML; // @synthesize isHTML=_isHTML;
@property(readonly, nonatomic) NSString *referrer; // @synthesize referrer=_referrer;
@property(readonly, nonatomic) long long statusCodeInteger; // @synthesize statusCodeInteger=_statusCodeInteger;
@property(readonly, nonatomic) double end; // @synthesize end=_end;
@property(readonly, nonatomic) double start; // @synthesize start=_start;
@property(readonly, nonatomic) unsigned long long dataSize; // @synthesize dataSize=_dataSize;
@property(readonly, nonatomic) double ssl; // @synthesize ssl=_ssl;
@property(readonly, nonatomic) double tcp; // @synthesize tcp=_tcp;
@property(readonly, nonatomic) NSString *pkgSeq; // @synthesize pkgSeq=_pkgSeq;
@property(readonly, nonatomic) NSString *pkgVersion; // @synthesize pkgVersion=_pkgVersion;
@property(readonly, nonatomic) NSString *pkgName; // @synthesize pkgName=_pkgName;
@property(readonly, nonatomic) NSString *protocolType; // @synthesize protocolType=_protocolType;
@property(readonly, nonatomic) NSString *via; // @synthesize via=_via;
@property(readonly, nonatomic) NSString *statusCode; // @synthesize statusCode=_statusCode;
@property(readonly, nonatomic) NSString *fromType; // @synthesize fromType=_fromType;
@property(readonly, nonatomic) NSString *url; // @synthesize url=_url;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (_Bool)isStatusSuccess;
- (_Bool)isFromNetwork;
- (double)loadTime;
- (void)recordHeader:(id)arg1;
- (void)recordNetStat:(id)arg1;
- (void)recordStatusCode:(long long)arg1 fromType:(long long)arg2;
- (void)setReferrer:(id)arg1;
- (void)setEnd:(double)arg1;
- (void)setStart:(double)arg1;
- (void)setDataSize:(unsigned long long)arg1;
- (id)initWithURL:(id)arg1 withPage:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

