//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSData;

@interface WXEmoticonObject : NSObject
{
    NSData *emoticonData;	// 8 = 0x8
}

+ (id)object;
@property(retain, nonatomic) NSData *emoticonData; // @synthesize emoticonData;
- (void)dealloc;
- (id)init;

@end

