//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDictionary, NSError, NSString, WXContactProfileV2, WXPersonProfile, WXUserBackgroundImageSetting, WXUserSetting, WXUserSizeData;

@protocol WXHttpRequestManagerDelegate <NSObject>

@optional
- (void)didGetCustomUserConfigString:(NSString *)arg1 withError:(NSError *)arg2;
- (void)didUploadCustomUserConfigStringWithError:(NSError *)arg1;
- (void)didUpdateUserBodySizeData:(WXUserSizeData *)arg1 withError:(NSError *)arg2;
- (void)didGetUserBodySizeData:(WXUserSizeData *)arg1 withError:(NSError *)arg2;
- (void)didUpgradeVersionConfig:(_Bool)arg1 withError:(NSError *)arg2;
- (void)didUpdateUserProfileBgImageSetting:(WXUserBackgroundImageSetting *)arg1 withError:(NSError *)arg2;
- (void)didSubmitReferrer:(NSString *)arg1 withError:(NSError *)arg2;
- (void)didGetContactsInfo:(NSDictionary *)arg1 withError:(NSError *)arg2;
- (void)didGetWangWangPersonsOnlineStatus:(NSDictionary *)arg1 andError:(NSError *)arg2;
- (void)didGetBatchWangWangUsersProfile:(NSArray *)arg1 andError:(NSError *)arg2;
- (void)didGetSingleWangWangUserProfileV2:(WXContactProfileV2 *)arg1 andError:(NSError *)arg2;
- (void)didModifyUserLoginPasswordWithError:(NSError *)arg1;
- (void)didClearUserSelfDescriptionWithError:(NSError *)arg1;
- (void)didGetSelfProfile:(WXPersonProfile *)arg1 withError:(NSError *)arg2;
- (void)didModifySelfProfileWithError:(NSError *)arg1;
- (void)didGetUserSetting:(WXUserSetting *)arg1 andError:(NSError *)arg2;
- (void)didUpdateUserSettingWithError:(NSDictionary *)arg1 errorObj:(NSError *)arg2;
- (void)didUpdateUserAvatarImage:(NSString *)arg1 andError:(NSError *)arg2;
- (void)didRemoveDeviceTokenWithError:(NSError *)arg1;
- (void)didUploadDeviceTokenWithError:(NSError *)arg1;
@end

