//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface WXKeyDataUtil : NSObject
{
    NSMutableDictionary *_keyDataStoreDic;	// 8 = 0x8
}

+ (_Bool)deleteItemForUsername:(id)arg1;
+ (_Bool)storeUsername:(id)arg1 andPassword:(id)arg2;
+ (id)getPasswordForUsername:(id)arg1;
+ (_Bool)storeDictionaryData:(id)arg1;
+ (id)generateDictionaryData;
+ (_Bool)writeKeyData:(id)arg1;
+ (id)readKeyData;
+ (id)keyDataFilePath;
+ (id)deserializationDictionaryData:(id)arg1;
+ (id)serializtionDictionaryData:(id)arg1;
+ (id)decryptData:(id)arg1;
+ (id)encryptData:(id)arg1;
+ (id)encrypDataKey;
+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *keyDataStoreDic; // @synthesize keyDataStoreDic=_keyDataStoreDic;
- (void).cxx_destruct;
- (_Bool)deleteStringValueForKey:(id)arg1;
- (_Bool)storeStringValue:(id)arg1 forKey:(id)arg2;
- (id)stringValueForKey:(id)arg1;
- (_Bool)clearLocalDataStroreIfNeed;
- (void)dealloc;
- (id)init;

@end

