//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableData;

@interface WXNetworkCallbackInfo : NSObject
{
    CDUnknownBlockType _sendDataCallback;	// 8 = 0x8
    CDUnknownBlockType _responseCallback;	// 16 = 0x10
    CDUnknownBlockType _receiveDataCallback;	// 24 = 0x18
    NSMutableData *_data;	// 32 = 0x20
    CDUnknownBlockType _compeletionCallback;	// 40 = 0x28
}

@property(copy, nonatomic) CDUnknownBlockType compeletionCallback; // @synthesize compeletionCallback=_compeletionCallback;
@property(retain, nonatomic) NSMutableData *data; // @synthesize data=_data;
@property(copy, nonatomic) CDUnknownBlockType receiveDataCallback; // @synthesize receiveDataCallback=_receiveDataCallback;
@property(copy, nonatomic) CDUnknownBlockType responseCallback; // @synthesize responseCallback=_responseCallback;
@property(copy, nonatomic) CDUnknownBlockType sendDataCallback; // @synthesize sendDataCallback=_sendDataCallback;
- (void).cxx_destruct;

@end

