//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSError;

@protocol WXRoamingBizLogicV2Delegate <NSObject>

@optional
- (void)didRoamBatchTribeChatLogWithError:(NSError *)arg1;
- (void)didRoamBatchP2PChatLogExForSellerWithError:(NSError *)arg1;
- (void)didRoamBatchP2PChatLogExForBuyerWithError:(NSError *)arg1;
- (void)didRoamBatchP2PChatLogWithError:(NSError *)arg1;
- (void)didDeleteAllRecentContactsWithError:(NSError *)arg1;
- (void)didDeleteRecentContactsForSellerWithError:(NSError *)arg1;
- (void)didDeleteRecentContactsWithError:(NSError *)arg1;
- (void)didRoamRecentContactsForSellerWithError:(NSError *)arg1;
- (void)didRoamRecentContactsWithError:(NSError *)arg1;
- (void)didRoamTribeChatLogWithError:(NSError *)arg1 otherInfo:(NSDictionary *)arg2;
- (void)didRoamP2PChatLogExForSellerWithError:(NSError *)arg1 otherInfo:(NSDictionary *)arg2;
- (void)didRoamP2PChatLogExForBuyerWithError:(NSError *)arg1 otherInfo:(NSDictionary *)arg2;
- (void)didRoamP2PChatLogWithError:(NSError *)arg1 otherInfo:(NSDictionary *)arg2;
- (void)didSetPasswordOfQueryChatLogWithError:(NSError *)arg1;
- (void)didCheckPasswordOfQueryChatLogWithError:(NSError *)arg1;
- (void)didSetServiceStateWithError:(NSError *)arg1;
- (void)didGetServiceState:(long long)arg1 andError:(NSError *)arg2;
@end

