//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBViewController.h"

@class BaseViewModel;

@interface XBaseViewController : TBViewController
{
    BaseViewModel *_viewModel;	// 16 = 0x10
    unsigned long long _viewDidLoadNum;	// 24 = 0x18
}

@property(readonly, nonatomic) unsigned long long viewDidLoadNum; // @synthesize viewDidLoadNum=_viewDidLoadNum;
@property(retain, nonatomic) BaseViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (void)viewModelDataChanged;
- (void)viewModelStateChanged;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
@property(readonly, nonatomic) _Bool isFirstViewDidLoad;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

