//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AudioSender.h"

@interface AudioSender (InternalMethod)
- (_Bool)prepareSend:(id)arg1;
- (void)MainThreadAddMsg:(id)arg1;
- (_Bool)deleteMessageFromDB:(id)arg1;
- (_Bool)updateMessageStatus:(id)arg1;
- (_Bool)updateMessageToDB:(id)arg1;
- (_Bool)addMessageToDB:(id)arg1;
- (id)getTmpAudioFileName:(unsigned int)arg1;
- (id)getAudioFileName:(id)arg1 LocalID:(unsigned int)arg2;
- (id)getChatName:(id)arg1;
@end

