//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding.h"

@class NSString;

@interface DeviceRankRecordItem : MMObject <PBCoding>
{
    unsigned int _uiRankScore;
    NSString *_nsTitle;
}

@property(nonatomic) unsigned int uiRankScore; // @synthesize uiRankScore=_uiRankScore;
@property(retain, nonatomic) NSString *nsTitle; // @synthesize nsTitle=_nsTitle;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

