//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseMessageNodeView.h"

#import "IMsgExt.h"
#import "IMsgRevokeExt.h"
#import "IVOIPUILogicMgrExt.h"
#import "IVideoExt.h"
#import "IWXVideoPlayerViewExt.h"
#import "SightIconViewDelegate.h"
#import "SightPlayerViewDelegate.h"

@class MMAVPlayerItemWrap, NSString, SightIconView, SightPlayerView, UIImageView, UIView;

@interface ShortVideoMessageNodeView : BaseMessageNodeView <IVOIPUILogicMgrExt, IWXVideoPlayerViewExt, IMsgRevokeExt, IVideoExt, IMsgExt, SightPlayerViewDelegate, SightIconViewDelegate>
{
    UIImageView *m_thumbImg;
    SightPlayerView *m_playerView;
    MMAVPlayerItemWrap *m_playerWrap;
    SightIconView *m_progressView;
    UIView *m_transparentCoverView;
    UIView *m_coverMask;
    struct CGRect m_vedioFrame;
    int m_currMaskType;
    _Bool m_isLoading;
    _Bool m_isClickDownload;
    unsigned long long _sightLegalityType;
    _Bool _mayBeIllegalAD;
}

+ (_Bool)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
- (void).cxx_destruct;
- (void)checkLegalityWithCompletionHandler:(CDUnknownBlockType)arg1;
- (_Bool)canAutoPlaySettingFromServer;
- (_Bool)isInFlowControl;
- (_Bool)shouldAutoDownload;
- (_Bool)shouldAutoPlay;
- (void)onWXVideoPlayerViewPlay:(id)arg1;
- (void)onVideoVoipViewDisappear;
- (void)onVideoVoipViewDidAppear:(id)arg1;
- (id)getMessageDisplayView;
- (void)clearShortVideo;
- (void)stopPlayShortVideo;
- (void)playShortVideo;
- (void)onResume;
- (void)onStack;
- (void)onItemCleared;
- (void)setProgress:(unsigned int)arg1;
- (void)UpdateVideoMsg:(id)arg1;
- (void)OnUpdateVideoStatus:(id)arg1 MsgWrap:(id)arg2;
- (void)OnThumbDownloadOK:(id)arg1;
- (void)onProgressEnd;
- (void)OnVideoGetIntoUploadQueue:(id)arg1;
- (id)thumbImage;
- (void)onClick;
- (void)onTouchUpInside;
- (void)hideCoverMaskWithAnim:(_Bool)arg1;
- (void)showCoverMask:(int)arg1;
- (void)initCoverMask;
- (id)makeSenderMaskLayer;
- (id)makeRecieverMaskLayer;
- (id)makeRecieverPath:(double)arg1;
- (id)makeSenderPath:(double)arg1;
- (void)OnMsgRevoked:(id)arg1 n64MsgId:(long long)arg2 SysMsg:(id)arg3;
- (void)onAppear;
- (void)showOpearation;
- (void)onMoreOperate:(id)arg1;
- (void)onFavoriteAdd:(id)arg1;
- (void)onForward:(id)arg1;
- (void)onLongTouch;
- (_Bool)isSendFailed;
- (void)layoutSubviewsInternal;
- (void)reLayoutSubviews;
- (void)layoutSubviews;
- (struct CGSize)videoSizeForThumbSize:(struct CGSize)arg1;
- (struct CGSize)sizeForFrame:(struct CGRect)arg1;
- (void)willMoveToSuperview:(id)arg1;
- (void)dealloc;
- (void)commonInit;
- (id)initWithMessageWrap:(id)arg1 Contact:(id)arg2 ChatContact:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

