//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCCardPackageViewController.h"

#import "IWCCardPkgExt.h"
#import "PBMessageObserverDelegate.h"
#import "WCCardDataControllerDelegate.h"

@class NSString;

@interface WCCardPackageViewController (MyCard) <IWCCardPkgExt, WCCardDataControllerDelegate, PBMessageObserverDelegate>
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)updateTableFooterHasMore:(_Bool)arg1;
- (void)stopActivityLoading;
- (void)scrollToShareCard;
- (void)stopLoadMoreAnimation;
- (void)onLoadMoreMyCardData;
- (id)getMyCardTableView;
- (void)onCardPackageViewSelectCardItem:(id)arg1;
- (double)getViewHeight;
- (_Bool)isFromAddEntrance;
- (_Bool)hasUnreadMessage;
- (_Bool)hasEnterCardListBefore;
- (void)showLoadingView;
- (void)showTableView;
- (id)getViewController;
- (void)onWCCardTips;
- (void)onGetCardLayoutStop;
- (void)onGetCardLayout;
- (void)onWCCardUpdate:(id)arg1;
- (void)onGetNextPageWCCardList:(id)arg1 ErrCode:(int)arg2 HasMore:(_Bool)arg3 HasBatchGeting:(_Bool)arg4;
- (void)onGetFirstPageWCCardList:(id)arg1 ErrCode:(int)arg2 HasMore:(_Bool)arg3 HasBatchGeting:(_Bool)arg4;
- (void)onSyncEnd:(_Bool)arg1;
- (void)onDeleteCardIDList:(id)arg1 ErrCode:(int)arg2;
- (void)loadMoreMyCard;
- (void)initMyCardLoadingView;
- (void)initMyCardTableView;
- (void)initMyCardData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

